delete from abm_plantillas where canal='pieza';
insert into abm_plantillas (giro,canal,nombre,orden,asunto,cuerpo,formato,objetivo,ruta) values
('renta','pieza','pieza',1,'El calendario de una pieza','<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;background-color:#ffffff;border:1px solid #ececec;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">
<tr>
<td width="4" bgcolor="#9B8CFA" style="background-color:#9B8CFA;width:4px;font-size:1px;line-height:1px;">&nbsp;</td>
<td bgcolor="#ffffff" style="background-color:#ffffff;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr><td style="padding:13px 14px 11px 14px;background-color:#ffffff;color:#3a3a44;font-size:16px;font-weight:bold;line-height:20px;">Vestido largo verde &middot; RNT-0421<br><span style="font-size:14px;font-weight:normal;color:#8a8a92;">Sucursal Centro &middot; 1 sola pieza en existencia</span></td></tr>
<tr><td style="padding:0 8px 4px 8px;background-color:#ffffff;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:separate;border-spacing:3px 0;">
<tr><td width="25%" align="center" bgcolor="#FFF4E5" style="background-color:#FFF4E5;border:1px solid #E8A838;padding:9px 2px;color:#9a6a10;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Vie 12</b><br>Sale 6pm</td><td width="25%" align="center" bgcolor="#EAF8F2" style="background-color:#EAF8F2;border:1px solid #4FBF95;padding:9px 2px;color:#1E8A63;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Sab 13</b><br>Rentado</td><td width="25%" align="center" bgcolor="#EAF8F2" style="background-color:#EAF8F2;border:1px solid #4FBF95;padding:9px 2px;color:#1E8A63;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Dom 14</b><br>Rentado</td><td width="25%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;border:1px solid #9B8CFA;padding:9px 2px;color:#5B4BD6;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Lun 15</b><br>Vuelve 11 am</td></tr>
  </table>
</td></tr>
<tr><td style="padding:12px 14px 4px 14px;background-color:#ffffff;color:#3a3a44;font-size:14px;line-height:20px;">Apart&oacute;: <b>Ana Ruiz</b> &middot; 55 1234 5678<br>Dep&oacute;sito <b style="color:#1E8A63;">$1,200 cobrado</b> &middot; renta $2,400</td></tr>
<tr><td style="padding:10px 14px 14px 14px;background-color:#ffffff;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr>
  <td bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-left:3px solid #E8A838;padding:9px 11px;color:#9a6a10;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Otras <b>2 clientas</b> pidieron esta misma pieza para el s&aacute;b 13. El sistema no deja apartarla dos veces.</td>
  </tr></table>
</td></tr>
</table>
</td></tr>
</table>','html','Los cuatro dias de una sola prenda: cuando sale, quien la tiene, que dias ya estan cobrados y a que hora vuelve.','ambas'),
('zapaterias','pieza','pieza',1,'La curva de tallas de un modelo','<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;background-color:#ffffff;border:1px solid #ececec;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">
<tr>
<td width="4" bgcolor="#9B8CFA" style="background-color:#9B8CFA;width:4px;font-size:1px;line-height:1px;">&nbsp;</td>
<td bgcolor="#ffffff" style="background-color:#ffffff;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr><td colspan="5" style="padding:13px 14px 11px 14px;background-color:#ffffff;color:#3a3a44;font-size:16px;font-weight:bold;line-height:20px;">Mocas&iacute;n piel caf&eacute; &middot; MOC-118<br><span style="font-size:14px;font-weight:normal;color:#8a8a92;">Pares por talla, por tienda</span></td></tr>
<tr><td width="28%" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 6px 8px 14px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Talla</td><td width="18%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">24</td><td width="18%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">25</td><td width="18%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">26</td><td width="18%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">27</td></tr>
<tr><td bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Centro</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">3</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">2</td><td align="center" bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-top:1px solid #ececec;padding:9px 4px;color:#9a6a10;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">0</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">1</td></tr>
<tr><td bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Plaza</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">1</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">4</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">2</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">3</td></tr>
<tr><td bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Outlet</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">0</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">1</td><td align="center" bgcolor="#EAF8F2" style="background-color:#EAF8F2;border-top:1px solid #ececec;padding:9px 4px;color:#1E8A63;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">4</td><td align="center" bgcolor="#ffffff" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">2</td></tr>
<tr><td colspan="5" style="padding:12px 14px 14px 14px;background-color:#ffffff;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr>
  <td bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-left:3px solid #E8A838;padding:9px 11px;color:#9a6a10;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">La <b>26</b> es 4 de cada 10 pares que vendes y en Centro est&aacute; en cero. Hay <b>4</b> paradas en Outlet.</td>
  </tr></table>
</td></tr>
</table>
</td></tr>
</table>','html','Un modelo, sus tallas y cuantos pares hay en cada tienda: se ve de un jalon que la talla que mas se vende esta en cero justo donde se vende.','ambas'),
('joyeria','pieza','pieza',1,'El precio que no siguio al oro','<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;background-color:#ffffff;border:1px solid #ececec;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">
<tr>
<td width="4" bgcolor="#9B8CFA" style="background-color:#9B8CFA;width:4px;font-size:1px;line-height:1px;">&nbsp;</td>
<td bgcolor="#ffffff" style="background-color:#ffffff;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr><td colspan="3" style="padding:13px 14px 11px 14px;background-color:#ffffff;color:#3a3a44;font-size:16px;font-weight:bold;line-height:20px;">Esclava oro 14k &middot; 8 g<br><span style="font-size:14px;font-weight:normal;color:#8a8a92;">El precio de mostrador lleva 60 d&iacute;as igual</span></td></tr>
<tr><td width="44%" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 6px 8px 14px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">&nbsp;</td><td width="28%" align="right" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 6px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Hace 60 d</td><td width="28%" align="right" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 14px 8px 6px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Hoy</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Gramo de oro</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$1,180</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 6px;color:#3a3a44;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$1,342</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Costo de la pieza</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$9,440</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 6px;color:#3a3a44;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$10,736</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Precio de mostrador</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$15,200</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 6px;color:#3a3a44;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$15,200</td></tr>
<tr><td bgcolor="#FEF0EF" style="background-color:#FEF0EF;border-top:1px solid #ececec;padding:10px 6px 10px 14px;color:#C0554E;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Te queda</td><td align="right" bgcolor="#FEF0EF" style="background-color:#FEF0EF;border-top:1px solid #ececec;padding:10px 6px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$5,760<br>38%</td><td align="right" bgcolor="#FEF0EF" style="background-color:#FEF0EF;border-top:1px solid #ececec;padding:10px 14px 10px 6px;color:#C0554E;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$4,464<br>29%</td></tr>
<tr><td colspan="3" style="padding:12px 14px 14px 14px;background-color:#ffffff;color:#3a3a44;font-size:14px;line-height:19px;">Son <b style="color:#C0554E;">$1,296 menos</b> por pieza, sin que nadie en el mostrador se entere. Con el precio atado al gramo, sube solo.</td></tr>
</table>
</td></tr>
</table>','html','La misma pieza hace 60 dias y hoy: el gramo subio, el precio de mostrador no se movio y el margen se comio la diferencia.','ambas'),
('telas','pieza','pieza',1,'Lo que queda de cada rollo','<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;background-color:#ffffff;border:1px solid #ececec;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">
<tr>
<td width="4" bgcolor="#9B8CFA" style="background-color:#9B8CFA;width:4px;font-size:1px;line-height:1px;">&nbsp;</td>
<td bgcolor="#ffffff" style="background-color:#ffffff;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr><td style="padding:13px 14px 11px 14px;background-color:#ffffff;color:#3a3a44;font-size:16px;font-weight:bold;line-height:20px;">Gabardina stretch negra<br><span style="font-size:14px;font-weight:normal;color:#8a8a92;">Metros vivos por rollo</span></td></tr>
<tr><td style="padding:2px 14px 0 14px;background-color:#ffffff;color:#3a3a44;font-size:14px;line-height:20px;">Rollo A-14 &middot; <b style="color:#1E8A63;">38.5 m</b> de 60 m</td></tr>
<tr><td style="padding:4px 14px 10px 14px;background-color:#ffffff;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr><td width="64%" bgcolor="#4FBF95" style="background-color:#4FBF95;font-size:1px;line-height:12px;height:12px;">&nbsp;</td><td width="36%" bgcolor="#ececec" style="background-color:#ececec;font-size:1px;line-height:12px;height:12px;">&nbsp;</td></tr></table></td></tr>
<tr><td style="padding:2px 14px 0 14px;background-color:#ffffff;color:#3a3a44;font-size:14px;line-height:20px;">Rollo A-15 &middot; <b style="color:#9a6a10;">6.2 m</b> de 60 m &nbsp;<span style="color:#9a6a10;">se acaba</span></td></tr>
<tr><td style="padding:4px 14px 10px 14px;background-color:#ffffff;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr><td width="10%" bgcolor="#E8A838" style="background-color:#E8A838;font-size:1px;line-height:12px;height:12px;">&nbsp;</td><td width="90%" bgcolor="#ececec" style="background-color:#ececec;font-size:1px;line-height:12px;height:12px;">&nbsp;</td></tr></table></td></tr>
<tr><td style="padding:2px 14px 0 14px;background-color:#ffffff;color:#3a3a44;font-size:14px;line-height:20px;">Rollo B-02 &middot; <b style="color:#1E8A63;">52.0 m</b> de 60 m</td></tr>
<tr><td style="padding:4px 14px 12px 14px;background-color:#ffffff;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr><td width="87%" bgcolor="#4FBF95" style="background-color:#4FBF95;font-size:1px;line-height:12px;height:12px;">&nbsp;</td><td width="13%" bgcolor="#ececec" style="background-color:#ececec;font-size:1px;line-height:12px;height:12px;">&nbsp;</td></tr></table></td></tr>
<tr><td style="padding:0 14px 14px 14px;background-color:#ffffff;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr>
  <td bgcolor="#FEF0EF" style="background-color:#FEF0EF;border-left:3px solid #EF7A72;padding:10px 11px;color:#C0554E;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Merma del mes: 11.3 m</b> (4.8% de lo cortado)<br><span style="color:#3a3a44;">Puntas, sobrantes y cortes mal medidos. Al costo del rollo son <b style="color:#C0554E;">$2,486</b>.</span></td>
  </tr></table>
</td></tr>
</table>
</td></tr>
</table>','html','Metros vivos por rollo con barra de avance, y los metros que se fueron en merma de corte este mes.','ambas'),
('novias','pieza','pieza',1,'La linea de tiempo de un vestido','<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;background-color:#ffffff;border:1px solid #ececec;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">
<tr>
<td width="4" bgcolor="#9B8CFA" style="background-color:#9B8CFA;width:4px;font-size:1px;line-height:1px;">&nbsp;</td>
<td bgcolor="#ffffff" style="background-color:#ffffff;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr><td colspan="3" style="padding:13px 14px 11px 14px;background-color:#ffffff;color:#3a3a44;font-size:16px;font-weight:bold;line-height:20px;">Mariana Cervantes &middot; boda 18 oct<br><span style="font-size:14px;font-weight:normal;color:#8a8a92;">Vestido corte sirena &middot; NOV-0288</span></td></tr>
<tr><td width="7" bgcolor="#4FBF95" style="background-color:#4FBF95;width:7px;font-size:1px;line-height:1px;border-top:1px solid #ececec;">&nbsp;</td><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 12px;color:#3a3a44;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Apartado</b> &middot; 4 jun</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 6px;color:#1E8A63;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$8,000</td></tr>
<tr><td bgcolor="#4FBF95" style="background-color:#4FBF95;font-size:1px;line-height:1px;border-top:1px solid #ececec;">&nbsp;</td><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 12px;color:#3a3a44;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>1a prueba</b> &middot; 2 ago</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 6px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">hecha</td></tr>
<tr><td bgcolor="#E8A838" style="background-color:#E8A838;font-size:1px;line-height:1px;border-top:1px solid #ececec;">&nbsp;</td><td bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-top:1px solid #ececec;padding:9px 6px 9px 12px;color:#9a6a10;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Ajustes con Lupita</b> &middot; vence 6 sep</td><td align="right" bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-top:1px solid #ececec;padding:9px 14px 9px 6px;color:#9a6a10;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">en 2 d</td></tr>
<tr><td bgcolor="#ececec" style="background-color:#ececec;font-size:1px;line-height:1px;border-top:1px solid #ececec;">&nbsp;</td><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 12px;color:#8a8a92;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b style="color:#3a3a44;">2a prueba</b> &middot; 20 sep</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 6px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">agendada</td></tr>
<tr><td bgcolor="#9B8CFA" style="background-color:#9B8CFA;font-size:1px;line-height:1px;border-top:1px solid #ececec;">&nbsp;</td><td bgcolor="#EEECFE" style="background-color:#EEECFE;border-top:1px solid #ececec;padding:10px 6px 10px 12px;color:#5B4BD6;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Liquida</b> &middot; antes del 11 oct</td><td align="right" bgcolor="#EEECFE" style="background-color:#EEECFE;border-top:1px solid #ececec;padding:10px 14px 10px 6px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">$14,500</td></tr>
<tr><td colspan="3" style="padding:12px 14px 14px 14px;background-color:#ffffff;color:#3a3a44;font-size:14px;line-height:19px;">Son <b>23 novias</b> a la vez con esta misma fila. El sistema avisa el que se atrasa; la libreta no.</td></tr>
</table>
</td></tr>
</table>','html','Los cinco momentos de un vestido de novia -apartado, pruebas, ajustes, anticipos y liquidacion- con el saldo y la fecha que no se puede mover.','ambas'),
('western','pieza','pieza',1,'Un modelo se vuelve 36 claves','<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;background-color:#ffffff;border:1px solid #ececec;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">
<tr>
<td width="4" bgcolor="#9B8CFA" style="background-color:#9B8CFA;width:4px;font-size:1px;line-height:1px;">&nbsp;</td>
<td bgcolor="#ffffff" style="background-color:#ffffff;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr><td style="padding:13px 14px 11px 14px;background-color:#ffffff;color:#3a3a44;font-size:16px;font-weight:bold;line-height:20px;">Bota Rodeo 300<br><span style="font-size:14px;font-weight:normal;color:#8a8a92;">Un modelo del cat&aacute;logo</span></td></tr>
<tr><td style="padding:0 11px 8px 11px;background-color:#ffffff;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:separate;border-spacing:3px 3px;">
  <tr><td width="24%" bgcolor="#ffffff" style="background-color:#ffffff;padding:7px 3px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Horma</td><td width="38%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 3px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">B</td><td width="38%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 3px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">EE</td></tr>
  <tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding:7px 3px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Piel</td><td align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 3px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Avestruz</td><td align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 3px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Res &middot; Nobuk</td></tr>
  </table>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:separate;border-spacing:3px 3px;">
  <tr><td width="24%" bgcolor="#ffffff" style="background-color:#ffffff;padding:7px 3px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Talla</td><td align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 2px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">25</td><td align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 2px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">26</td><td align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 2px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">27</td><td align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 2px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">28</td><td align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 2px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">29</td><td align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:7px 2px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">30</td></tr>
  </table>
</td></tr>
<tr><td style="padding:2px 14px 10px 14px;background-color:#ffffff;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr>
  <td bgcolor="#EEECFE" style="background-color:#EEECFE;border-left:3px solid #5B4BD6;padding:10px 11px;color:#5B4BD6;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">2 hormas &times; 3 pieles &times; 6 tallas = <b style="font-size:16px;">36 claves</b> de un solo modelo</td>
  </tr></table>
</td></tr>
<tr><td style="padding:0 14px 14px 14px;background-color:#ffffff;color:#3a3a44;font-size:14px;line-height:20px;"><b style="color:#9a6a10;">7</b> claves en cero justo en las tallas que salen &nbsp;&middot;&nbsp; <b style="color:#C0554E;">4</b> sin venderse en 90 d&iacute;as</td></tr>
</table>
</td></tr>
</table>','html','Como horma, talla y tipo de piel multiplican un solo modelo en decenas de claves, y cuantas de esas ya se te fueron.','ambas'),
('scrubs','pieza','pieza',1,'Filipina y pantalon no cuadran','<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;background-color:#ffffff;border:1px solid #ececec;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">
<tr>
<td width="4" bgcolor="#9B8CFA" style="background-color:#9B8CFA;width:4px;font-size:1px;line-height:1px;">&nbsp;</td>
<td bgcolor="#ffffff" style="background-color:#ffffff;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr><td colspan="4" style="padding:13px 14px 11px 14px;background-color:#ffffff;color:#3a3a44;font-size:16px;font-weight:bold;line-height:20px;">Conjunto antifluidos<br><span style="font-size:14px;font-weight:normal;color:#8a8a92;">Filipinas / pantalones en existencia</span></td></tr>
<tr><td width="28%" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 6px 8px 14px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Color</td><td width="24%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">S</td><td width="24%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">M</td><td width="24%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 14px 8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">L</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Quir&uacute;rgico</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">5 / 5</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">8 / 7</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">4 / 4</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Vino</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">3 / 2</td><td align="center" bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-top:1px solid #ececec;padding:9px 4px;color:#9a6a10;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">6 / 2</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">2 / 3</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Negro</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">4 / 4</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">9 / 8</td><td align="center" bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-top:1px solid #ececec;padding:9px 14px 9px 4px;color:#9a6a10;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">7 / 1</td></tr>
<tr><td colspan="4" style="padding:12px 14px 8px 14px;background-color:#ffffff;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr>
  <td bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-left:3px solid #E8A838;padding:9px 11px;color:#9a6a10;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Vino M:</b> 6 filipinas y 2 pantalones. Puedes vender 2 conjuntos, no 6.</td>
  </tr></table>
</td></tr>
<tr><td colspan="4" style="padding:0 14px 14px 14px;background-color:#ffffff;color:#3a3a44;font-size:14px;line-height:20px;">Bordado &laquo;Dra. L&oacute;pez&raquo; <b style="color:#1E8A63;">+$80</b> por prenda &middot; <b>14</b> pedidos esta semana, en la misma venta</td></tr>
</table>
</td></tr>
</table>','html','Piezas de filipina y de pantalon por color y talla: donde se rompe el conjunto y cuanto bordado va encima.','ambas'),
('cadenas','pieza','pieza',1,'La misma prenda en cuatro tiendas','<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;background-color:#ffffff;border:1px solid #ececec;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">
<tr>
<td width="4" bgcolor="#9B8CFA" style="background-color:#9B8CFA;width:4px;font-size:1px;line-height:1px;">&nbsp;</td>
<td bgcolor="#ffffff" style="background-color:#ffffff;padding:0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr><td colspan="4" style="padding:13px 14px 11px 14px;background-color:#ffffff;color:#3a3a44;font-size:16px;font-weight:bold;line-height:20px;">Blusa lino blanca &middot; talla M<br><span style="font-size:14px;font-weight:normal;color:#8a8a92;">La misma prenda en tus 4 tiendas</span></td></tr>
<tr><td width="30%" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 6px 8px 14px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Tienda</td><td width="20%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Pzas</td><td width="22%" align="center" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Vende</td><td width="28%" align="right" bgcolor="#EEECFE" style="background-color:#EEECFE;padding:8px 14px 8px 4px;color:#5B4BD6;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Le dura</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Centro</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">2</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">9/sem</td><td align="right" bgcolor="#FFF4E5" style="background-color:#FFF4E5;border-top:1px solid #ececec;padding:9px 14px 9px 4px;color:#9a6a10;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">2 d&iacute;as</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Sat&eacute;lite</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">18</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">2/sem</td><td align="right" bgcolor="#E3EDFD" style="background-color:#E3EDFD;border-top:1px solid #ececec;padding:9px 14px 9px 4px;color:#2C5FC4;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">9 sem</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Sur</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">6</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">5/sem</td><td align="right" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 14px 9px 4px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">1 sem</td></tr>
<tr><td style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 6px 9px 14px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">Bodega</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#3a3a44;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">11</td><td align="center" style="background-color:#ffffff;border-top:1px solid #ececec;padding:9px 4px;color:#8a8a92;font-size:14px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">&mdash;</td><td align="right" bgcolor="#E3EDFD" style="background-color:#E3EDFD;border-top:1px solid #ececec;padding:9px 14px 9px 4px;color:#2C5FC4;font-size:14px;font-weight:bold;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;">parada</td></tr>
<tr><td colspan="4" style="padding:12px 14px 14px 14px;background-color:#ffffff;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr>
  <td bgcolor="#EEECFE" style="background-color:#EEECFE;border-left:3px solid #5B4BD6;padding:10px 11px;color:#5B4BD6;font-size:14px;line-height:19px;font-family:-apple-system,''Segoe UI'',Roboto,Arial,sans-serif;"><b>Traspaso sugerido:</b> 12 pzas de Sat&eacute;lite a Centro. Son <b>$9,480</b> parados donde no se venden.</td>
  </tr></table>
</td></tr>
</table>
</td></tr>
</table>','html','Existencia contra venta semanal tienda por tienda: donde esta parada la mercancia, donde se esta agotando y el traspaso que lo arregla.','ambas');