insert into abm_cuentas (nombre,giro,subgiro,ciudad,estado_geo,pais,moneda,sucursales,sucursales_confianza,tamano,ruta,sitio,plataforma_web,instagram,ig_seguidores,tiktok,facebook,linkedin,google_rating,google_resenas,contexto,senal_expansion,nota,encaje,etapa) values
('Hernández West','western','Western / botas y accesorios en piel','León','Guanajuato','México','MXN',3,'media','chica','demo','https://hernandezwest.com/','Shopify','https://www.instagram.com/hernandezwestoficial/',5071,'https://www.tiktok.com/@cintoshernandez','https://www.facebook.com/hernandezwestoficial/',null,3.8,13,'Fabricante y distribuidora western: botas, cintos bordados, carteras y sombreros de piel, con venta a mayoristas y emprendedores en todo México. · fabricante + marca con tiendas propias · SAPICA 95 (ago 2026)',null,'Caso de libro: fábrica, vende mayoreo Y opera 3 tiendas propias — inventario partido entre fábrica, mayoreo y piso. Entrarle por el mayoreo: piden por WhatsApp y facturan a mano; el paquete de 12 cintos + 12 huaraches que promocionan es justo el tipo de combo que hoy no saben costear.',24,'sin_tocar'),
('Botas Padilla (Industrial Padilla)','boutiques','Western / calzado industrial de caballero','León','Guanajuato','México','MXN',null,'media','micro','demo','https://tiendabotaspadilla.com/','Shopify','https://www.instagram.com/botaspadilla/',8586,null,'https://www.facebook.com/BotasPadillaIndustriales/',null,4.1,35,'Fabricante desde 1973 de bota industrial y western para caballero con construcción Goodyear Welt. · fabricante + marca con tienda propia · SAPICA 95 (ago 2026)',null,'53 años fabricando: catálogo largo de hormas industriales y numeración amplia, el peor caso para Excel. El correo del contacto es literalmente ''botaspadillashopify@'' — ya viven en Shopify y les falta el back office que le case el inventario.',18,'sin_tocar'),
('KBallo Pasión Equina','western','Western / accesorios ecuestres','León','Guanajuato','México','MXN',1,'media','micro','demo','https://kballo.com/','Tiendanube','https://www.instagram.com/kballopasionequina/',8806,'https://www.tiktok.com/@kballopequina','https://www.facebook.com/KBalloPasionEquina/',null,5,1,'Tienda-fábrica de artículos del mundo equino y vaquero: botas, cintos, joyería y regalos con identidad ranchera; mayoreo y menudeo. · marca con tienda propia · SAPICA 95 (ago 2026)',null,'8.8k seguidores en IG contra 1 reseña en Google: todo el negocio pasa por WhatsApp y mostrador. Mezcla botas por número con joyería y accesorios por pieza — el argumento es un solo inventario para las dos lógicas.',12,'sin_tocar'),
('Desobediente Boots','western','Western / botas de autor','León','Guanajuato','México','MXN',null,'media','micro','demo','https://desobedienteboots.com/','WordPress + WooCommerce','https://www.instagram.com/desobediente.boots/',5852,null,null,null,null,null,'Marca joven de botas vaqueras de piel hechas en León, con venta directa por e-commerce. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'Marca nueva con 5.8k seguidores y WooCommerce: crece por redes y todavía no tiene sistema. Buen momento para entrar antes de que amarren procesos; el gancho es control de tallas por modelo cuando el inventario se vuelve compartido entre feria, web y mayoreo.',18,'sin_tocar'),
('Centaurus Western','western','Western / botas en pieles exóticas','León','Guanajuato','México','MXN',1,'media','micro','demo','https://centauruswestern.com/','Shopify','https://www.instagram.com/centauruswestern/',3795,null,'https://www.facebook.com/centauroboots/',null,5,7,'Fabricación y comercialización de bota vaquera y botín en pieles exóticas 100% originales, más accesorios de moda western. · fabricante + tienda propia · SAPICA 95 (ago 2026)',null,'Piel exótica = piezas de alto valor dónde perder un par duele en pesos, no en unidades. Entrarle por el dueño directo (persona física, decide solo) y por costeo: cada corrida de avestruz o caimán tiene costo distinto y hoy lo promedian.',12,'sin_tocar'),
('Deldhy Western Products','western','Western / sombrerería','San Francisco del Rincón','Guanajuato','México','MXN',null,'media','micro','demo','https://deldhywestern.com/','Shopify','https://www.instagram.com/deldhy.western/',1094,null,null,'https://mx.linkedin.com/in/miguel-angel-del-moral-robledo-9604a3105',5,3,'Fabricante de sombrero vaquero con más de 40 años; líder en exportación y venta al mayoreo. · fabricante / exportador mayorista · SAPICA 95 (ago 2026)',null,'Sombrero se multiplica por talla, copa, ala y color igual que el calzado, y ellos exportan — o sea manejan pedidos grandes con listas de empaque. Entrarle por control de pedido de exportación y por el LinkedIn del directivo, que es de los pocos con perfil visible.',18,'sin_tocar'),
('Trasso Boots','zapaterias','Western / calzado industrial de seguridad','León','Guanajuato','México','MXN',null,'media','micro','demo','https://trassoboots.com/','Shopify','https://www.instagram.com/trasso.boots/',176,'https://www.tiktok.com/@trassoboots','https://www.facebook.com/botastrassomx/',null,5,16,'Fabricante desde 1985 de bota de trabajo y de seguridad de uso rudo, hecha en León; vende a industria y a distribuidores. · fabricante · SAPICA 95 (ago 2026)',null,'Bota industrial se vende por contrato y por talla: pedidos de 200 pares repartidos en 8 números, justo dónde se cae el Excel. Entrarle por surtido de pedido corporativo y trazabilidad de lote.',18,'sin_tocar'),
('Toro Sentado','western','Western / botas y marroquinería','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/toro.sentado/',1026,null,'https://www.facebook.com/torosentad/',null,null,null,'Marca mexicana de botas hechas a mano en pieles exóticas, más carteras, cintos, bolsas y sombreros; exporta a tiendas western de Estados Unidos. · fabricante / marca exportadora · SAPICA 95 (ago 2026)',null,'Sin sitio propio pero ya lo revenden tiendas de Estados Unidos (laherradurawwnc.com): venden por catálogo a distribuidores. Entrarle por lista de precios por cliente y por el control de lo que ya se comprometió contra lo que hay.',18,'sin_tocar'),
('Botas Reyme (Reyme Export)','western','Western / botas de piel','León','Guanajuato','México','MXN',null,'media','micro','demo','https://www.botasreyme.com.mx/','Shopify','https://www.instagram.com/reymeboots_oficial/',3804,'https://www.tiktok.com/@reymeboots','https://www.facebook.com/REYMEoficial/',null,4.7,9,'Fabricante de bota vaquera y botín de piel hecho a mano, con marca propia y venta en línea; razón social Reyme Export S.A. de C.V. · fabricante / exportador con marca propia · SAPICA 95 (ago 2026)',null,'El ''Export'' en la razon social dice que ya venden fuera: pedidos en dólares, corridas completas y guías. Entrarle por control de pedido de exportación; el correo de ventas es gmail, señal de que el back office esta en libretas.',18,'sin_tocar'),
('Botas y Botines Potro Salvaje','zapaterias','Western / botin charro y calzado urbano','León','Guanajuato','México','MXN',null,'media','micro','demo','https://potrosalvaje.mx/','Shopify','https://www.instagram.com/botasybotinespotrosalvaje/',1099,'https://www.tiktok.com/@potrosalvaje_0',null,null,5,1,'Fabricante desde 1981 de botin charro, bota vaquera y calzado urbano para dama y caballero. · fabricante · SAPICA 95 (ago 2026)',null,'45 años fabricando y apenas estrenan Shopify: el catálogo en línea es nuevo y el inventario sigue en el taller. Entrarle mostrando como el mismo par que se vende en la web descuenta de la existencia de fábrica.',18,'sin_tocar'),
('MexaBoot','western','Western / botas','León','Guanajuato','México','MXN',null,'media','micro','demo','https://mexaboot.com.mx/','WordPress + WooCommerce','https://www.instagram.com/calzadomexabootoficial/',null,'https://www.tiktok.com/@botas_mexaboot','https://www.facebook.com/Mexaboot/',null,4.4,10,'Manufacturera Mexaboot: fabricación de bota vaquera y botin de piel, con venta al menudeo, mayoreo y en línea. · fabricante + retail · SAPICA 95 (ago 2026)',null,'Su propio correo dice ''retail'': ya operan piso de venta ademas de fabricar, y en su web separan pagos ''en sucursales'' de los de la tienda en línea. Ese corte entre canales es exactamente el dolor que resuelve el POS con inventario único.',18,'sin_tocar'),
('Botas Gran Líder','western','Western / bota vaquera y maquila','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,null,null,null,'https://www.facebook.com/granliderboots/',null,4,1,'Fábrica de bota vaquera con 24 años, proceso welt artesanal; ademas maquila producto para marcas grandes con presencia nacional. · fabricante + maquilador · SAPICA 95 (ago 2026)',null,'Maquilan para marcas grandes ademas de su propia marca: dos flujos de producción sobre las mismas hormas, y hoy no separan el costo de cada uno. Entrarle por órdenes de producción y costeo por cliente; el reto es que casi no tienen huella digital, hay que buscarlos en piso en SAPICA.',18,'sin_tocar'),
('Arius Boots / Baby Arius','western','Western infantil / bota vaquera de bebe','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/ariusbootsoficial/',null,null,'https://www.facebook.com/p/BABY-ARIUS-Bota-Vaquera-de-Bebe--100064109496935/',null,null,null,'Fabricante con más de 10 años especializado en bota vaquera para bebe y para toda la familia. · fabricante · SAPICA 95 (ago 2026) — logo subido a sapica.com en ago 2026',null,'Nicho perfecto de multiplicacion: bota vaquera de bebe va del 10 al 21 más colores, y con volumen bajo por modelo. Entrarle por mínimos y máximos automaticos, que es dónde un fabricante chico pierde ventas por quedarse sin números de en medio.',18,'sin_tocar'),
('Richard West','western','Western infantil / bota de bebe y niño','León','Guanajuato','México','MXN',null,'media','micro','demo','https://richardwest.com.mx/','WordPress + WooCommerce','https://www.instagram.com/botas_richardwest/',null,null,null,null,null,null,'Fabricante leonés de botas vaqueras para bebe y niño; caso difundido por la Camara del Calzado y el gobierno estatal. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'Empresa de dueña identificada y con historia publica de crecimiento apoyada por CICEG: decide una sola persona y ya adopto WooCommerce. El correo de pedidos es gmail — hoy el pedido llega por WhatsApp y se captura a mano dos veces.',18,'sin_tocar'),
('Moksman Hats','western','Western / sombrerería','San Francisco del Rincón','Guanajuato','México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/moksmanhats_oficial/',168,null,'https://www.facebook.com/MoksmanOficial/',null,null,null,'Empresa familiar fundada en 1975 por Rafael Liñán; fabricación artesanal de sombrero vaquero, referente del ramo sombrerero de San Francisco del Rincón. · fabricante familiar · SAPICA 95 (ago 2026)',null,'Medio siglo de empresa familiar y toda la operacion cabe en un correo ''pedidos@gmail''. El sombrero se multiplica por talla, copa y color igual que el calzado. Entrarle por relevo generacional: quien hereda quiere números, no libretas.',18,'sin_tocar'),
('RAM Wild Hats','western','Western / sombrerería','San Francisco del Rincón','Guanajuato','México','MXN',null,'media','micro','demo',null,null,null,null,null,'https://www.facebook.com/61573191274449/',null,null,null,'Marca de sombrero vaquero de San Francisco del Rincón; vende por catálogo de WhatsApp Business y redes. · fabricante / marca joven · SAPICA 95 (ago 2026)',null,'Marca nacida en 2025 que vende con el catálogo de WhatsApp Business: cero sistema, todo en el teléfono. Es el perfil que más rapido cierra porque no hay nada que migrar; el gancho es catálogo + precios + inventario en un solo lugar.',18,'sin_tocar'),
('Catalina Vargas (Impulsora COMCA)','fabricantes','Dama','Guadalajara','Jalisco','México','MXN',8,'media','mediana','diagnostico','https://catalinavargas.com/','Tiendanube','https://www.instagram.com/catalina.vargas.tiendas/',2061,null,'https://www.facebook.com/CatalinaVargasTiendas/',null,4.6,8,'Marca y cadena de zapaterías de calzado de moda para dama; vende en toda la república desde Guadalajara. · marca con tiendas propias · SAPICA 95 (ago 2026)',null,'El prospecto ideal del brief: 8 tiendas en 4 ciudades más Tiendanube, o sea traspasos entre sucursales y un e-commerce que se surte del mismo stock. Entrarle por el traspaso: hoy mueven pares entre Guadalajara, Cuernavaca y Acapulco sin saber dónde está cada número.',36,'sin_tocar'),
('Calzado Jakuna','tallas','Infantil / dama','León','Guanajuato','México','MXN',3,'media','chica','demo','https://www.calzadojakuna.com/','Shopify','https://www.instagram.com/calzadojakuna/',9736,'https://www.tiktok.com/@calzadojakunafabrica',null,null,4.8,44,'Fabricante leonés de calzado infantil y de dama (''Solo para princesas''), con tiendas propias y venta en línea. · fabricante + marca con tiendas propias · SAPICA 95 (ago 2026)',null,'Fábrica + 3 tiendas + Shopify + 9.7k seguidores y 4.8 en Google: crecimiento sano y desordenado. Su TikTok se llama ''calzadojakunafabrica'', ellos mismos se venden como fábrica; el gancho es un solo inventario entre fábrica, las 3 tiendas y la web.',24,'sin_tocar'),
('Maquech (Lady Carolina)','western','Dama / western urbano','León','Guanajuato','México','MXN',3,'media','chica','demo','https://maquechshoes.com/','Shopify',null,null,null,null,null,null,null,'Marca mexicana de botas, botines, texanas, sneakers, bolsos y ropa; fabricación en León con showroom y tiendas propias. · fabricante + marca con tiendas propias · SAPICA 95 (ago 2026)',null,'Tres ciudades (León, Queretaro, CDMX) y ademas venden ropa y bolsos: catálogo mixto por talla de calzado y talla de prenda, más accesorios por pieza. Entrarle por la tienda de Queretaro y CDMX, que operan lejos de la fábrica y hoy se surten a ciegas.',24,'sin_tocar'),
('Zapatos Karsten','tallas','Infantil / escolar','León','Guanajuato','México','MXN',null,'media','micro','demo','https://zapatoskarsten.com/','WordPress + WooCommerce',null,null,null,'https://www.facebook.com/zapatoskarsten/',null,4.8,8,'Fabricante leonés de calzado infantil escolar y casual para niño y niña, con sucursales propias y e-commerce. · fabricante + marca con tiendas propias · SAPICA 95 (ago 2026)',null,'Escolar = temporada brutal: julio-agosto se juega el ano y hoy corren promos ''1 par 10%, 2 pares 15%'' sin control de margen por par. 14 mil seguidores en Facebook. Entrarle justo después del regreso a clases, cuando les duele el saldo de números sueltos.',18,'sin_tocar'),
('Jarking Shoes','boutiques','Confort dama y caballero','León','Guanajuato','México','MXN',null,'media','micro','demo','https://jarking.com/','Shopify','https://www.instagram.com/jarkingshoes/',4613,'https://www.tiktok.com/@jarking_shoes','https://www.facebook.com/JarkingShoes/',null,4.1,30,'Fabricante leonés con 35 años de calzado de confort premium hecho a mano, piel genuina y plantilla de memory foam; opera boutiques propias. · fabricante + marca con boutiques propias · SAPICA 95 (ago 2026)',null,'En su ficha de producto ofrecen ''Notificarme'' en talla 23, 23.5, 24, 24.5, 25, 25.5 y 26: estan agotados en TODA la corrida de un modelo. Ese pantallazo es la venta — es exactamente lo que resuelven los mínimos y máximos automaticos.',18,'sin_tocar'),
('Calzado Elefante (Fábrica de Calzado Plascencia)','tallas','Infantil','León','Guanajuato','México','MXN',null,'media','micro','demo','https://elefante.com.mx/','Shopify','https://www.instagram.com/calzadoelefante/',4205,null,'https://www.facebook.com/tienda.elefante.com.mx/',null,4.4,76,'Fabricante de calzado infantil con 75 años de historia; venta en línea propia y presencia en outlet. · fabricante + marca con tienda propia · SAPICA 95 (ago 2026)',null,'75 años, tallas 18 a 26 por modelo y color: el catálogo infantil es el que más SKUs genera por peso de venta. Entrarle por el correo de ventas online, que es dónde ya sienten el descuadre entre la web y la fábrica.',18,'sin_tocar'),
('Calzado Bambino (Calzado Baja)','tallas','Infantil','León','Guanajuato','México','MXN',null,'media','micro','demo','https://calzadobambino.com.mx/','Shopify','https://www.instagram.com/calzadobambino/',3423,null,'https://www.facebook.com/calzadobambino/',null,null,null,'Empresa fundada en 1947; la marca Bambino nace en 1982 para diseño, fabricación y comercialización de calzado infantil. · fabricante con marca propia · SAPICA 95 (ago 2026)',null,'79 años de empresa y ya tienen puesto de ''ecommerce'' con correo propio: hay alguien dedicado al canal digital, que es quien primero sufre el inventario desfasado. Ese correo es la puerta de entrada.',18,'sin_tocar'),
('Verdetabaco (Grupo Rimar)','boutiques','Confort / caballero','San Francisco del Rincón','Guanajuato','México','MXN',null,'media','micro','demo','https://verdetabaco.mx/','Shopify',null,null,null,null,null,4.6,119,'Fabricante de calzado de piel fundado en 1996 en San Francisco del Rincón; entre 101 y 250 empleados, con tienda en línea propia. · fabricante + marca con tienda propia · SAPICA 95 (ago 2026)',null,'119 reseñas con 4.6 es la mejor reputación medida de esta lista, y con 100+ empleados ya son planta formal. Ese tamano es el que justifica un sistema completo (producción, almacén, punto de venta) y no solo un POS.',18,'sin_tocar'),
('Calzado Yuyin (Grupo Yuyin / Recalza Stores)','tallas','Infantil / escolar','León','Guanajuato','México','MXN',null,'media','micro','demo','https://calzadoyuyin.com.mx/','Shopify','https://www.instagram.com/yuyinoficial/',null,'https://www.tiktok.com/@yuyinoficial','https://www.facebook.com/CalzadoYuyin/',null,4.2,45,'Fabricante y comercializador leonés de calzado infantil escolar, tenis y sandalias, con lineas licenciadas (Minecraft, Pokemon, BT21, Free Fire) y tiendas fisicas propias. · fabricante + marca con tiendas propias · SAPICA 95 (ago 2026)',null,'Manejan licencias (Pokemon, Minecraft, Free Fire) que caducan por contrato: producto con fecha de muerte comercial que hoy se les queda en piso. Entrarle por rotación y liquidación de línea licenciada, ademas del pico escolar.',18,'sin_tocar'),
('Gino Cherruti (Diseños Carlo Venuty)','boutiques','Caballero / vestir','León','Guanajuato','México','MXN',null,'media','micro','demo','https://ginocherruti.mx/','WordPress + WooCommerce','https://www.instagram.com/ginocherruti/',1005,null,'https://www.facebook.com/calzado.ginocherruti/',null,4.8,6,'Fabricante leonés de calzado de vestir y casual de caballero con marca propia y tiendas. · fabricante + marca con tiendas propias · SAPICA 95 (ago 2026)',null,'Razon social distinta de la marca (Diseños Carlo Venuty opera Gino Cherruti): señal clasica de que facturan por un lado y venden por otro. Su localizador de tiendas ya truena (404) — el sitio está abandonado y ahi se entra.',18,'sin_tocar'),
('Lobo Solo','boutiques','Caballero / confort','León','Guanajuato','México','MXN',null,'media','micro','demo','https://lobosolo.com.mx/','Shopify','https://www.instagram.com/lobosolooficial/',null,'https://www.tiktok.com/@lobosolooficial','https://www.facebook.com/lobosolocalzado/',null,5,4,'Empresa mexicana de calzado de piel fundada en 1996, especialista en construcción OPANKA hecha a mano. · fabricante + marca con tienda propia · SAPICA 95 (ago 2026)',null,'Construcción OPANKA es artesanal y lenta: producir de más cuesta carísimo y quedarse corto pierde la venta. Es el caso perfecto para mínimos y máximos por horma y número, no por modelo.',18,'sin_tocar'),
('Cammina','fabricantes','Confort dama','León','Guanajuato','México','MXN',null,'media','micro','demo','https://cammina.mx/','Shopify','https://www.instagram.com/cammina.mx/',null,null,'https://www.facebook.com/camminamx/',null,null,null,'Marca mexicana de zapatos de confort para mujer con venta directa en línea. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'Marca digital pura: todo el volumen pasa por Shopify y por eso el desfase de stock se vuelve devolución inmediata. Entrarle por integración catálogo-inventario y por cuánto les cuesta cada cancelación por ''ya no habia tu número''.',18,'sin_tocar'),
('Dr. Hosue','zapaterias','Confort / calzado de alto confort y diabético','León','Guanajuato','México','MXN',null,'media','micro','demo','https://drhosue.com/','WordPress + WooCommerce','https://www.instagram.com/dr.hosue/',478,null,'https://www.facebook.com/Dr.Hosue/',null,4.3,23,'Fabricante leonés de calzado de alto confort, con línea ortopédica y para pie diabético. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'Confort médico se vende por ancho ademas de número: el SKU se multiplica el doble que en calzado normal. Ademas venden a farmacias y podólogos, o sea listas de precio distintas por canal.',18,'sin_tocar'),
('Gôsh','boutiques','Dama / caballero, moda joven','León','Guanajuato','México','MXN',null,'media','micro','demo','https://www.gosh.com.mx/',null,null,null,null,null,null,4.2,54,'Marca leonesa de calzado de moda para gente de ''mente joven''; ademas comercializa en México marcas de prestigio de terceros. · fabricante + comercializador de marcas de terceros · SAPICA 95 (ago 2026)',null,'Doble negocio: marca propia más distribución de marcas ajenas (aparecen registros de ''GOSH LEVIS''). Eso obliga a manejar costo propio y costo de compra en el mismo almacén — el argumento más facil de aterrizar.',18,'sin_tocar'),
('Alfredo Shoes de México','boutiques','Caballero / dama, calzado de lujo','León','Guanajuato','México','MXN',null,'media','micro','demo','https://alfredoshoes.com/',null,null,null,null,'https://www.facebook.com/alfredoshoesmexico/',null,4.6,80,'Marca de calzado de lujo para hombre y mujer que fusiona elegancia clasica y confort, con materiales de alta calidad y manufactura artesanal. · fabricante con marca propia · SAPICA 95 (ago 2026)',null,'80 reseñas con 4.6: reputación solida y ticket alto por ser lujo. En ese segmento el par parado es capital muerto caro; entrarle por antiguedad de inventario y margen por modelo, no por volumen.',18,'sin_tocar'),
('Calzado Armada (Grupo Industrial Armada del Bajío)','fabricantes','Industrial / seguridad','León','Guanajuato','México','MXN',2,'media','chica','demo','https://www.calzadoarmada.com/','Wix',null,null,null,null,null,4.5,101,'Fabricante de calzado industrial y de seguridad, con venta a empresas y dos tiendas propias. · fabricante + marca con tiendas propias · SAPICA 95 (ago 2026)',null,'101 reseñas y tienda en Naucalpan: ya operan fuera de Guanajuato, o sea inventario en dos estados. Ademas venden a empresas, que exigen factura y orden de compra — el gancho es surtir un pedido corporativo por números sin llamar a la fábrica.',24,'sin_tocar'),
('Calzado Doreli','fabricantes','Dama','Tepatitlán de Morelos','Jalisco','México','MXN',null,'media','micro','demo','https://www.doreli.com.mx/','Shopify','https://www.instagram.com/calzadodoreli/',6092,null,'https://www.facebook.com/calzadodoreli/',null,4.5,20,'Fabricante de calzado de dama con marca propia y tienda en línea; envíos a toda la república. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'6 mil seguidores y su bio dice literal ''Fabricando para ti'': venden directo al consumidor lo que ellos mismos producen. Entrarle por el descuadre entre la corrida que sale de producción y lo que la tienda en línea promete.',18,'sin_tocar'),
('Zapatos Sary','tallas','Dama / infantil','Zapopan','Jalisco','México','MXN',null,'media','micro','demo','https://sary.com.mx/','WordPress + WooCommerce','https://www.instagram.com/zapatossary/',315,null,'https://www.facebook.com/ZapatosSary/',null,4.1,7,'Empresa con más de 40 años que desarrolla calzado para dama y niñas; participa también en Modama (Guadalajara). · fabricante con marca propia · SAPICA 95 (ago 2026); también expone en Modama',null,'Fabricante de Jalisco que va a las dos ferias (SAPICA y Modama): venden por catálogo a zapaterías, con muestrario y pedidos de temporada. Entrarle por levantamiento de pedido en feria — hoy lo hacen en papel y lo capturan al regresar.',18,'sin_tocar'),
('Renatta Scottos','fabricantes','Dama','León','Guanajuato','México','MXN',null,'media','micro','demo','https://www.renattascottos.com/','Jimdo','https://www.instagram.com/renattascottos_mx/',3585,null,'https://www.facebook.com/renattascottosonline/',null,5,2,'Marca mexicana de sandalias, zapatillas y calzado de dama con diseño y fabricación propia. · fabricante / marca DTC · SAPICA 95 (ago 2026) — logo subido a sapica.com en jul 2026',null,'Su tienda corre sobre Jimdo, o sea el escalon más basico posible de e-commerce: no hay integración de inventario ni con la fábrica. Marca joven con 3.5k seguidores creciendo; entrarle antes de que compren un ERP grande.',18,'sin_tocar'),
('Soy THEA','zapaterias','Dama / calzado inclusivo','León','Guanajuato','México','MXN',null,'media','micro','demo','https://soythea.com/','WordPress + WooCommerce','https://www.instagram.com/soytheamx/',888,null,'https://www.facebook.com/61576987052600/',null,null,null,'Marca leonesa que debuto en SAPICA 95 con una propuesta de calzado inclusivo y comodo; prepara colección en colaboración con Wendy Guevara. · marca nueva / fabricante · SAPICA 95 (ago 2026) — lanzamiento oficial en la feria',null,'Se lanzo EN esta edicion con meet and greet propio en el escenario principal y colaboración con Wendy Guevara: van a tener un pico de demanda enorme sin operacion detras. Entrarle ya, antes de la colaboración, o los revienta el primer drop.',18,'sin_tocar'),
('Milagros Shoes','fabricantes','Dama','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/milagrosshoes/',2801,null,'https://www.facebook.com/people/Almacenes-de-calzado-milagros/100064027184310/',null,null,null,'Empresa leonesa dedicada a la fabricación de calzado para dama, con énfasis en el oficio artesanal. · fabricante · SAPICA 95 (ago 2026)',null,'Tienen página de ''Talento Humano'' en Facebook: ya son planta con nómina, no taller. Sin sitio web ni sistema visible — el hueco es total. Entrarle por control de producción y almacén antes que por punto de venta.',18,'sin_tocar'),
('Mímar Fashion Shoes','fabricantes','Dama','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/mimar_shoes/',2372,null,'https://www.facebook.com/MimarShoes/',null,4.5,11,'Fabricante leonés de calzado de moda para dama. · fabricante · SAPICA 95 (ago 2026)',null,'Fabricante mediano con presencia en redes y buena calificación pero sin sitio propio: viven de mayoreo a zapaterías. Ese perfil es el que compra sistema para dejar de contestar ''¿tienes del 24?'' por WhatsApp una por una.',18,'sin_tocar'),
('JJ Studio','fabricantes','Dama','México',null,'México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/calzadojj_oficial/',6650,null,'https://www.facebook.com/p/JJStudiocalzado-100084017491108/',null,null,null,'Marca mexicana de calzado de dama con presencia principalmente en redes sociales. · fabricante / marca · SAPICA 95 (ago 2026)',null,'6.6k seguidores sin sitio web ni ficha de Google: todo el negocio vive en Instagram y WhatsApp. Es el caso dónde el catálogo en línea de SACS vale más que el POS — y el único camino de contacto es DM o el piso de la feria.',18,'sin_tocar'),
('Raúl Coss (Innova Calzado)','boutiques','Dama / caballero','Guadalajara','Jalisco','México','MXN',null,'media','micro','demo','https://raulcoss.com/','Magento','https://www.instagram.com/raulcossmexico/',809,null,'https://www.facebook.com/raulcossmexico/',null,4.4,22,'Fabricante de calzado con marca propia; opera tienda en línea sobre Magento desde Jalisco. · fabricante con marca propia · SAPICA 95 (ago 2026)',null,'Corren Magento, que es caro de mantener y casi nadie en el ramo lo soporta bien: hay dolor y costo fijo que ya estan pagando. Argumento directo de ahorro, no de novedad.',18,'sin_tocar'),
('Agavero by Arco Humming (Calzado Arco)','western','Western / botas','León','Guanajuato','México','MXN',null,'media','micro','demo','https://calzadoarco.com/',null,'https://www.instagram.com/calzado_arco/',3224,null,'https://www.facebook.com/ARCOBOOTS.COM.MX/',null,null,null,'Fabricante de bota vaquera de piel con la marca Agavero; producto que ya se revende en el mercado de Estados Unidos. · fabricante / marca exportadora · SAPICA 95 (ago 2026)',null,'La marca Agavero ya circula en reventa en Estados Unidos (Poshmark): exportan sin controlar el canal. Dos identidades (Calzado Arco fábrica, Agavero marca) que hoy seguro llevan en catálogos separados — ese es el enganche.',18,'sin_tocar'),
('Tenis Pontiac','fabricantes','Deportivo','San Francisco del Rincón','Guanajuato','México','MXN',null,'media','micro','demo','https://www.tenispontiac.com/',null,'https://www.instagram.com/tenispontiac_oficial/',1237,'https://www.tiktok.com/@tenispontiac_oficial','https://www.facebook.com/tenispontiacaxl/',null,4.6,25,'Fabricante con más de 30 años de calzado deportivo 100% mexicano; vende directo de fábrica con tienda oficial en línea. · fabricante + marca DTC · SAPICA 95 (ago 2026)',null,'Deportivo mexicano compitiendo contra marcas globales: su ventaja es vender directo de fábrica, y eso exige que el stock en línea sea real. Entrarle por el número de WhatsApp que publican, que es por dónde entra todo el pedido.',18,'sin_tocar'),
('Moderof','boutiques','Dama / caballero','León','Guanajuato','México','MXN',null,'media','micro','demo','https://moderofenlinea.com/',null,null,null,null,'https://www.facebook.com/Moderof/',null,4.5,141,'Fabricante leonés de calzado con tienda de fábrica propia y venta en línea al mayoreo y menudeo. · fabricante + marca con tienda propia · SAPICA 95 (ago 2026)',null,'141 reseñas en su tienda de fábrica: es la que más tráfico de mostrador tiene de toda la lista, y eso significa POS de verdad, con filas y cortes de caja. Entrarle por punto de venta, no por catálogo.',18,'sin_tocar'),
('Calzado Blasito','tallas','Infantil','León','Guanajuato','México','MXN',null,'media','micro','demo','https://blasito.mx/','Shopify','https://www.instagram.com/blasitomx/',4453,'https://www.tiktok.com/@blasitomx',null,null,3.6,18,'Fabricante leonés de calzado infantil con marca propia, tienda en línea y presencia fuerte en redes. · fabricante + marca con tienda propia · SAPICA 95 (ago 2026)',null,'3.6 de calificación con 18 reseñas es la peor de la lista: hay dolor operativo real que ya le esta costando reputación. Su correo sigue siendo @prodigy.net.mx, o sea infraestructura de hace 20 años. Entrarle por ahi, sin rodeos.',18,'sin_tocar'),
('Calzado Zull','fabricantes','Dama','León','Guanajuato','México','MXN',null,'media','micro','demo','https://calzadozull.com/','Shopify','https://www.instagram.com/zullcalzado/',5957,'https://www.tiktok.com/@zullcalzado',null,null,null,null,'Fabricante leonés de calzado de dama con marca propia y tienda en línea. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'6 mil seguidores en Instagram y TikTok activo, pero el correo de contacto sigue siendo hotmail: venden moderno y administran a la antigua. Perfil que compra rapido porque el dolor ya es diario.',18,'sin_tocar'),
('King Walker','boutiques','Caballero','León','Guanajuato','México','MXN',null,'media','micro','demo','https://www.kingwalkercalzado.mx/','Shopify','https://www.instagram.com/kingwalker.mx/',2822,'https://www.tiktok.com/@kingwalker.mx','https://www.facebook.com/kingwalker.mx/',null,4.7,15,'Fabricante leonés de calzado de caballero con marca propia y tienda en línea. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'Tenemos el correo de DIRECCION y el nombre de la dueña: se llega al que decide en un solo correo, sin filtro de compras. Fábrica de caballero con tres canales (web, TikTok, mayoreo) y un solo inventario que sostenerlos.',18,'sin_tocar'),
('Castelli Leather','zapaterias','Marroquinería / calzado en piel','León','Guanajuato','México','MXN',null,'media','micro','demo','https://www.castellileather.com/','Wix','https://www.instagram.com/castellileathermx/',272,null,'https://www.facebook.com/CastelliLeatherAuthentic/',null,5,9,'Fabricante leonés de articulos de piel autentica con marca propia y venta en línea. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'5 estrellas limpias con 9 reseñas: cuidan al cliente pero el sitio está en Wix con plantilla sin terminar (todavia tiene el correo de ejemplo ''ejemplo@misitio.com'' visible). Entrarle por profesionalizar el catálogo antes que por el POS.',18,'sin_tocar'),
('Savvy & Savvy','boutiques','Dama / boutique','León','Guanajuato','México','MXN',null,'media','micro','demo','https://savvy-savvy.com.mx/','Tiendanube','https://www.instagram.com/savvysavvyfashionboutique/',null,'https://www.tiktok.com/@savvysavvyboutique',null,null,4.8,42,'Boutique de moda y calzado dentro del Mulza Outlet del Calzado, con tienda en línea propia. · comercializador / boutique con tienda propia · SAPICA 95 (ago 2026)',null,'No fabrican: compran a los fabricantes del piso de SAPICA y revenden en outlet y en línea. 4.8 con 42 reseñas. Sirve doble — como cliente de POS y como puerta a sus proveedores, que son el resto de esta lista.',18,'sin_tocar'),
('Bucéfalo Boots','western','Western / botas vaqueras','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/bucefaloboots/',3003,null,null,null,null,null,'Fabricante leonés de botas vaqueras hechas en México (''caminando sin limites''), con venta directa por redes. · fabricante · Afiliado CICEG (organizadora de SAPICA) — presencia en SAPICA 95 no confirmada por logo',null,'Persona fisica con nombre y correo directos: el dueño contesta el, sin intermediarios. 3 mil seguidores vendiendo bota por Instagram y cero sistema — el ciclo de venta más corto de la lista.',18,'sin_tocar'),
('Piedra Angular','boutiques','Dama / caballero','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/piedrangularmex/',2495,null,null,null,null,null,'Fábrica leonesa de calzado (Calzado Piedra Angular S.A. de C.V.) con marca propia; distribuye también via Moderna Online. · fabricante con marca propia · Afiliado CICEG (organizadora de SAPICA)',null,'Venden por su cuenta y ademas a traves de un marketplace (Moderna Online): dos canales con el mismo stock y ninguna forma de reservarlo. Ojo: el correo que publican trae un typo (''piedrangunlar'') — hablar por teléfono.',18,'sin_tocar'),
('Botas Bull Rider (Grupo Dosgon)','western','Western / botas','León','Guanajuato','México','MXN',null,'media','micro','demo','https://botasbullrideroficial.com/','GoDaddy',null,null,null,null,null,null,null,'Fabricante leonés de bota vaquera con marca propia Bull Rider y tienda en línea. · fabricante con marca propia · Afiliado CICEG (organizadora de SAPICA)',null,'El único contacto publicado es el de contabilidad: ahi la conversacion empieza por costos y facturación, no por marketing. Su tienda corre en el constructor de GoDaddy, o sea sin inventario real detras.',18,'sin_tocar'),
('Pietro Alessandro','boutiques','Caballero / vestir','México','Jalisco','México','MXN',null,'media','micro','demo','https://pietroalessandro.mx/','Shopify','https://www.instagram.com/pietroalessandrooficcial/',6063,null,'https://www.facebook.com/Calzadopietroalessandrojal/',null,4.8,4,'Marca de calzado de vestir para caballero con tienda en línea propia. · fabricante / marca DTC · SAPICA 95 (ago 2026)',null,'6 mil seguidores y Shopify pero solo 4 reseñas en Google: negocio 100% digital sin piso. El dolor va a ser la devolución por talla; el gancho es matriz de tallas por horma y control de cambios.',18,'sin_tocar'),
('Sohrelia (Daniel Cázarez Pérez)','boutiques','Multimarca / moda y accesorios','México',null,'México','MXN',null,'media','micro','demo','https://www.sohrelia.com/','Shopify','https://www.instagram.com/sohrelia/',null,'https://www.tiktok.com/@sohrelia','https://www.facebook.com/Sohrelia/',null,null,null,'Grupo comercializador multimarca que representa y distribuye marcas de moda (Barabas, Platini, GFTD, JC Hats) y opera su propia tienda en línea; también surte a Suburbia. · comercializador / distribuidor multimarca · SAPICA 95 (ago 2026); también expone en Intermoda con 10 stands',null,'Distribuidor, no fabricante: maneja cuatro marcas ajenas más la propia y vende a Suburbia, o sea EDI, etiquetado y órdenes de compra de cadena. Vale doble porque cada marca que representa es otro prospecto; entrarle por el dueño, que registra los stands a su nombre.',18,'sin_tocar'),
('Ruditos Joe','tallas','Infantil / escolar','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,null,null,null,'https://www.facebook.com/RuditosJoe/',null,null,null,'Fabricante con 20 años de experiencia en zapato escolar, casual y de descanso 100% piel para niño y niña. · fabricante · SAPICA 95 (ago 2026)',null,'El correo es el nombre del dueño en el dominio de la empresa: se le escribe directo y decide el mismo. Escolar de piel del 15 al 25 en dos hormas — el catálogo más repetitivo y el que más se descuadra en temporada.',18,'sin_tocar'),
('Calzado Brenda Paulina (De Faty)','fabricantes','Dama','León','Guanajuato','México','MXN',null,'media','micro','demo',null,null,'https://www.instagram.com/calzadobrendapaulina/',686,null,'https://www.facebook.com/CalzadoBrendaPaulina/',null,3,2,'Fabricante leonesa de calzado de dama con marca propia y venta por redes. · fabricante · SAPICA 95 (ago 2026)',null,'Fábrica chica con marca a nombre de la dueña: decisiones rapidas y presupuesto acotado, ideal para el plan de entrada. Correo hotmail y cero web — venden por Facebook y WhatsApp.',18,'sin_tocar'),
('Correrd','fabricantes','Deportivo','México',null,'México','MXN',null,'media','micro','demo',null,null,null,null,null,null,null,5,2,'Marca mexicana de calzado deportivo y tenis. · fabricante / marca · SAPICA 95 (ago 2026)',null,'Marca de tenis con casi nula huella digital: hay que levantarla en piso de feria. El deportivo se vende por número y por talla juvenil, con corridas más largas que el resto — el caso más duro de Excel.',18,'sin_tocar')
on conflict (lower(nombre), coalesce(ciudad,'')) do nothing;
insert into abm_canales (cuenta_id,tipo,valor,confianza)
select c.id, v.tipo, v.valor, v.conf
from (values
('Hernández West','León','email_generico','logisticahernandezwest@gmail.com','alta'),
('Hernández West','León','whatsapp_tienda','+52 477 398 9557','alta'),
('Hernández West','León','telefono','+52 477 398 9557','alta'),
('Hernández West','León','dm_ig','https://instagram.com/https://www.instagram.com/hernandezwestoficial/','media'),
('Hernández West','León','dm_fb','https://www.facebook.com/hernandezwestoficial/','media'),
('Botas Padilla (Industrial Padilla)','León','email_generico','botaspadillashopify@gmail.com','alta'),
('Botas Padilla (Industrial Padilla)','León','telefono','+52 477 132 1298','alta'),
('Botas Padilla (Industrial Padilla)','León','dm_ig','https://instagram.com/https://www.instagram.com/botaspadilla/','media'),
('Botas Padilla (Industrial Padilla)','León','dm_fb','https://www.facebook.com/BotasPadillaIndustriales/','media'),
('KBallo Pasión Equina','León','whatsapp_tienda','+52 477 107 3740','alta'),
('KBallo Pasión Equina','León','telefono','+52 477 107 3740','alta'),
('KBallo Pasión Equina','León','dm_ig','https://instagram.com/https://www.instagram.com/kballopasionequina/','media'),
('KBallo Pasión Equina','León','dm_fb','https://www.facebook.com/KBalloPasionEquina/','media'),
('Desobediente Boots','León','whatsapp_tienda','+52 1 477 703 4526','alta'),
('Desobediente Boots','León','dm_ig','https://instagram.com/https://www.instagram.com/desobediente.boots/','media'),
('Centaurus Western','León','email_generico','contacto@centauruswestern.com','alta'),
('Centaurus Western','León','dm_ig','https://instagram.com/https://www.instagram.com/centauruswestern/','media'),
('Centaurus Western','León','dm_fb','https://www.facebook.com/centauroboots/','media'),
('Deldhy Western Products','San Francisco del Rincón','dm_ig','https://instagram.com/https://www.instagram.com/deldhy.western/','media'),
('Trasso Boots','León','email_generico','info@trassoboots.com','alta'),
('Trasso Boots','León','telefono','+52 477 890 0715','alta'),
('Trasso Boots','León','dm_ig','https://instagram.com/https://www.instagram.com/trasso.boots/','media'),
('Trasso Boots','León','dm_fb','https://www.facebook.com/botastrassomx/','media'),
('Toro Sentado','León','dm_ig','https://instagram.com/https://www.instagram.com/toro.sentado/','media'),
('Toro Sentado','León','dm_fb','https://www.facebook.com/torosentad/','media'),
('Botas Reyme (Reyme Export)','León','email_generico','ventas.reymeoficial@gmail.com','alta'),
('Botas Reyme (Reyme Export)','León','dm_ig','https://instagram.com/https://www.instagram.com/reymeboots_oficial/','media'),
('Botas Reyme (Reyme Export)','León','dm_fb','https://www.facebook.com/REYMEoficial/','media'),
('Botas y Botines Potro Salvaje','León','email_generico','botinespotrosalvaje@gmail.com','alta'),
('Botas y Botines Potro Salvaje','León','telefono','+52 477 714 5482','alta'),
('Botas y Botines Potro Salvaje','León','dm_ig','https://instagram.com/https://www.instagram.com/botasybotinespotrosalvaje/','media'),
('MexaBoot','León','email_generico','retailmexaboot@gmail.com','alta'),
('MexaBoot','León','telefono','+52 477 715 1012','alta'),
('MexaBoot','León','dm_ig','https://instagram.com/https://www.instagram.com/calzadomexabootoficial/','media'),
('MexaBoot','León','dm_fb','https://www.facebook.com/Mexaboot/','media'),
('Botas Gran Líder','León','dm_fb','https://www.facebook.com/granliderboots/','media'),
('Arius Boots / Baby Arius','León','dm_ig','https://instagram.com/https://www.instagram.com/ariusbootsoficial/','media'),
('Arius Boots / Baby Arius','León','dm_fb','https://www.facebook.com/p/BABY-ARIUS-Bota-Vaquera-de-Bebe--100064109496935/','media'),
('Richard West','León','email_generico','pedidosrw@gmail.com','alta'),
('Richard West','León','whatsapp_tienda','+52 477 598 5709','alta'),
('Richard West','León','telefono','+52 477 598 5709','alta'),
('Richard West','León','dm_ig','https://instagram.com/https://www.instagram.com/botas_richardwest/','media'),
('Moksman Hats','San Francisco del Rincón','email_generico','pedidos.moksmanhats@gmail.com','alta'),
('Moksman Hats','San Francisco del Rincón','dm_ig','https://instagram.com/https://www.instagram.com/moksmanhats_oficial/','media'),
('Moksman Hats','San Francisco del Rincón','dm_fb','https://www.facebook.com/MoksmanOficial/','media'),
('RAM Wild Hats','San Francisco del Rincón','whatsapp_tienda','+52 1 476 107 8046','alta'),
('RAM Wild Hats','San Francisco del Rincón','dm_fb','https://www.facebook.com/61573191274449/','media'),
('Catalina Vargas (Impulsora COMCA)','Guadalajara','whatsapp_tienda','+52 33 1736 7353','alta'),
('Catalina Vargas (Impulsora COMCA)','Guadalajara','telefono','+52 33 1736 7353','alta'),
('Catalina Vargas (Impulsora COMCA)','Guadalajara','dm_ig','https://instagram.com/https://www.instagram.com/catalina.vargas.tiendas/','media'),
('Catalina Vargas (Impulsora COMCA)','Guadalajara','dm_fb','https://www.facebook.com/CatalinaVargasTiendas/','media'),
('Calzado Jakuna','León','email_generico','marketingjakuna@gmail.com','alta'),
('Calzado Jakuna','León','telefono','+52 479 389 4980','alta'),
('Calzado Jakuna','León','dm_ig','https://instagram.com/https://www.instagram.com/calzadojakuna/','media'),
('Maquech (Lady Carolina)','León','email_generico','lady_carolina@live.com.mx','alta'),
('Maquech (Lady Carolina)','León','whatsapp_tienda','+52 477 937 6088','alta'),
('Maquech (Lady Carolina)','León','telefono','+52 477 937 6088','alta'),
('Zapatos Karsten','León','email_generico','mktkarsten2020@gmail.com','alta'),
('Zapatos Karsten','León','telefono','+52 477 564 8166','alta'),
('Zapatos Karsten','León','dm_fb','https://www.facebook.com/zapatoskarsten/','media'),
('Jarking Shoes','León','email_generico','servicioalcliente@jarking.com.mx','alta'),
('Jarking Shoes','León','whatsapp_tienda','+52 477 628 9382','alta'),
('Jarking Shoes','León','telefono','+52 477 771 5655 (fábrica)','alta'),
('Jarking Shoes','León','dm_ig','https://instagram.com/https://www.instagram.com/jarkingshoes/','media'),
('Jarking Shoes','León','dm_fb','https://www.facebook.com/JarkingShoes/','media'),
('Calzado Elefante (Fábrica de Calzado Plascencia)','León','email_generico','ventasonline@elefante.com.mx','alta'),
('Calzado Elefante (Fábrica de Calzado Plascencia)','León','whatsapp_tienda','+52 477 564 6374','alta'),
('Calzado Elefante (Fábrica de Calzado Plascencia)','León','telefono','+52 477 564 6374','alta'),
('Calzado Elefante (Fábrica de Calzado Plascencia)','León','dm_ig','https://instagram.com/https://www.instagram.com/calzadoelefante/','media'),
('Calzado Elefante (Fábrica de Calzado Plascencia)','León','dm_fb','https://www.facebook.com/tienda.elefante.com.mx/','media'),
('Calzado Bambino (Calzado Baja)','León','email_generico','ecommerce@calzadobambino.com.mx','alta'),
('Calzado Bambino (Calzado Baja)','León','telefono','+52 477 114 7889','alta'),
('Calzado Bambino (Calzado Baja)','León','dm_ig','https://instagram.com/https://www.instagram.com/calzadobambino/','media'),
('Calzado Bambino (Calzado Baja)','León','dm_fb','https://www.facebook.com/calzadobambino/','media'),
('Verdetabaco (Grupo Rimar)','San Francisco del Rincón','email_generico','tienda@verdetabaco.com.mx','alta'),
('Verdetabaco (Grupo Rimar)','San Francisco del Rincón','telefono','+52 476 757 5555','alta'),
('Calzado Yuyin (Grupo Yuyin / Recalza Stores)','León','email_generico','mkt@grupoyuyin.com.mx','alta'),
('Calzado Yuyin (Grupo Yuyin / Recalza Stores)','León','dm_ig','https://instagram.com/https://www.instagram.com/yuyinoficial/','media'),
('Calzado Yuyin (Grupo Yuyin / Recalza Stores)','León','dm_fb','https://www.facebook.com/CalzadoYuyin/','media'),
('Gino Cherruti (Diseños Carlo Venuty)','León','email_generico','contacto@ginocherruti.com','alta'),
('Gino Cherruti (Diseños Carlo Venuty)','León','dm_ig','https://instagram.com/https://www.instagram.com/ginocherruti/','media'),
('Gino Cherruti (Diseños Carlo Venuty)','León','dm_fb','https://www.facebook.com/calzado.ginocherruti/','media'),
('Lobo Solo','León','dm_ig','https://instagram.com/https://www.instagram.com/lobosolooficial/','media'),
('Lobo Solo','León','dm_fb','https://www.facebook.com/lobosolocalzado/','media'),
('Cammina','León','email_generico','info@cammina.mx','alta'),
('Cammina','León','dm_ig','https://instagram.com/https://www.instagram.com/cammina.mx/','media'),
('Cammina','León','dm_fb','https://www.facebook.com/camminamx/','media'),
('Dr. Hosue','León','email_generico','ventas@drhosue.com.mx','alta'),
('Dr. Hosue','León','telefono','+52 477 746 3267','alta'),
('Dr. Hosue','León','dm_ig','https://instagram.com/https://www.instagram.com/dr.hosue/','media'),
('Dr. Hosue','León','dm_fb','https://www.facebook.com/Dr.Hosue/','media'),
('Gôsh','León','email_generico','contacto@gosh.com','alta'),
('Gôsh','León','telefono','+52 477 114 7809','alta'),
('Alfredo Shoes de México','León','email_generico','ventas@alfredoshoes.com','alta'),
('Alfredo Shoes de México','León','telefono','+52 477 711 6237','alta'),
('Alfredo Shoes de México','León','dm_fb','https://www.facebook.com/alfredoshoesmexico/','media'),
('Calzado Armada (Grupo Industrial Armada del Bajío)','León','email_generico','info@calzadoarmada.com','alta'),
('Calzado Armada (Grupo Industrial Armada del Bajío)','León','telefono','+52 477 144 5588','alta'),
('Calzado Doreli','Tepatitlán de Morelos','dm_ig','https://instagram.com/https://www.instagram.com/calzadodoreli/','media'),
('Calzado Doreli','Tepatitlán de Morelos','dm_fb','https://www.facebook.com/calzadodoreli/','media'),
('Zapatos Sary','Zapopan','email_generico','contacto@sary.com.mx','alta'),
('Zapatos Sary','Zapopan','telefono','+52 33 3672 0909','alta'),
('Zapatos Sary','Zapopan','dm_ig','https://instagram.com/https://www.instagram.com/zapatossary/','media'),
('Zapatos Sary','Zapopan','dm_fb','https://www.facebook.com/ZapatosSary/','media'),
('Renatta Scottos','León','dm_ig','https://instagram.com/https://www.instagram.com/renattascottos_mx/','media'),
('Renatta Scottos','León','dm_fb','https://www.facebook.com/renattascottosonline/','media'),
('Soy THEA','León','dm_ig','https://instagram.com/https://www.instagram.com/soytheamx/','media'),
('Soy THEA','León','dm_fb','https://www.facebook.com/61576987052600/','media'),
('Milagros Shoes','León','dm_ig','https://instagram.com/https://www.instagram.com/milagrosshoes/','media'),
('Milagros Shoes','León','dm_fb','https://www.facebook.com/people/Almacenes-de-calzado-milagros/100064027184310/','media'),
('Mímar Fashion Shoes','León','dm_ig','https://instagram.com/https://www.instagram.com/mimar_shoes/','media'),
('Mímar Fashion Shoes','León','dm_fb','https://www.facebook.com/MimarShoes/','media'),
('JJ Studio','México','dm_ig','https://instagram.com/https://www.instagram.com/calzadojj_oficial/','media'),
('JJ Studio','México','dm_fb','https://www.facebook.com/p/JJStudiocalzado-100084017491108/','media'),
('Raúl Coss (Innova Calzado)','Guadalajara','email_generico','contacto@raulcoss.com','alta'),
('Raúl Coss (Innova Calzado)','Guadalajara','telefono','+52 33 3366 2393','alta'),
('Raúl Coss (Innova Calzado)','Guadalajara','dm_ig','https://instagram.com/https://www.instagram.com/raulcossmexico/','media'),
('Raúl Coss (Innova Calzado)','Guadalajara','dm_fb','https://www.facebook.com/raulcossmexico/','media'),
('Agavero by Arco Humming (Calzado Arco)','León','dm_ig','https://instagram.com/https://www.instagram.com/calzado_arco/','media'),
('Agavero by Arco Humming (Calzado Arco)','León','dm_fb','https://www.facebook.com/ARCOBOOTS.COM.MX/','media'),
('Tenis Pontiac','San Francisco del Rincón','email_generico','ventas@tenispontiac.com','alta'),
('Tenis Pontiac','San Francisco del Rincón','whatsapp_tienda','+52 476 139 1992','alta'),
('Tenis Pontiac','San Francisco del Rincón','telefono','+52 476 139 1992','alta'),
('Tenis Pontiac','San Francisco del Rincón','dm_ig','https://instagram.com/https://www.instagram.com/tenispontiac_oficial/','media'),
('Tenis Pontiac','San Francisco del Rincón','dm_fb','https://www.facebook.com/tenispontiacaxl/','media'),
('Moderof','León','email_generico','pedidos@moderof.com','alta'),
('Moderof','León','telefono','+52 477 719 8511','alta'),
('Moderof','León','dm_fb','https://www.facebook.com/Moderof/','media'),
('Calzado Blasito','León','email_generico','blasito@prodigy.net.mx','alta'),
('Calzado Blasito','León','telefono','+52 477 711 1115','alta'),
('Calzado Blasito','León','dm_ig','https://instagram.com/https://www.instagram.com/blasitomx/','media'),
('Calzado Zull','León','email_generico','zapateriazull@hotmail.com','alta'),
('Calzado Zull','León','dm_ig','https://instagram.com/https://www.instagram.com/zullcalzado/','media'),
('King Walker','León','email_generico','direccion@kingwalkershoes.com.mx','alta'),
('King Walker','León','telefono','+52 477 211 1983','alta'),
('King Walker','León','dm_ig','https://instagram.com/https://www.instagram.com/kingwalker.mx/','media'),
('King Walker','León','dm_fb','https://www.facebook.com/kingwalker.mx/','media'),
('Castelli Leather','León','email_generico','ventas@castellileather.com','alta'),
('Castelli Leather','León','telefono','+52 477 773 1555','alta'),
('Castelli Leather','León','dm_ig','https://instagram.com/https://www.instagram.com/castellileathermx/','media'),
('Castelli Leather','León','dm_fb','https://www.facebook.com/CastelliLeatherAuthentic/','media'),
('Savvy & Savvy','León','email_generico','hola@savvy-savvy.com','alta'),
('Savvy & Savvy','León','whatsapp_tienda','+52 477 264 8465','alta'),
('Savvy & Savvy','León','telefono','+52 477 712 1255','alta'),
('Savvy & Savvy','León','dm_ig','https://instagram.com/https://www.instagram.com/savvysavvyfashionboutique/','media'),
('Bucéfalo Boots','León','email_generico','bucefaloboots@gmail.com','alta'),
('Bucéfalo Boots','León','dm_ig','https://instagram.com/https://www.instagram.com/bucefaloboots/','media'),
('Piedra Angular','León','email_generico','contacto@piedrangunlar.com','alta'),
('Piedra Angular','León','telefono','+52 477 231 1636','alta'),
('Piedra Angular','León','dm_ig','https://instagram.com/https://www.instagram.com/piedrangularmex/','media'),
('Botas Bull Rider (Grupo Dosgon)','León','email_generico','contabilidad@grupodosgon.com','alta'),
('Pietro Alessandro','México','dm_ig','https://instagram.com/https://www.instagram.com/pietroalessandrooficcial/','media'),
('Pietro Alessandro','México','dm_fb','https://www.facebook.com/Calzadopietroalessandrojal/','media'),
('Sohrelia (Daniel Cázarez Pérez)','México','dm_ig','https://instagram.com/https://www.instagram.com/sohrelia/','media'),
('Sohrelia (Daniel Cázarez Pérez)','México','dm_fb','https://www.facebook.com/Sohrelia/','media'),
('Ruditos Joe','León','email_generico','enrique_aldana@ruditosjoe.com.mx','alta'),
('Ruditos Joe','León','telefono','+52 477 707 0122','alta'),
('Ruditos Joe','León','dm_fb','https://www.facebook.com/RuditosJoe/','media'),
('Calzado Brenda Paulina (De Faty)','León','email_generico','cbrendapaulina@hotmail.com','alta'),
('Calzado Brenda Paulina (De Faty)','León','whatsapp_tienda','+52 477 288 5437','alta'),
('Calzado Brenda Paulina (De Faty)','León','telefono','+52 477 288 5437','alta'),
('Calzado Brenda Paulina (De Faty)','León','dm_ig','https://instagram.com/https://www.instagram.com/calzadobrendapaulina/','media'),
('Calzado Brenda Paulina (De Faty)','León','dm_fb','https://www.facebook.com/CalzadoBrendaPaulina/','media')
) as v(nom,ciu,tipo,valor,conf)
join abm_cuentas c on lower(c.nombre)=lower(v.nom) and coalesce(c.ciudad,'')=coalesce(v.ciu,'');
insert into abm_personas (cuenta_id,nombre,cargo,es_dueno,linkedin)
select c.id, v.pn, v.cg, true, v.li
from (values
('Hernández West','León','Jesús Hernández','Fundador',null),
('Centaurus Western','León','Marco Antonio Miguel Ángel Zavala Martínez','Propietario (persona física registrada en CICEG)',null),
('Deldhy Western Products','San Francisco del Rincón','Miguel Ángel del Moral Robledo','Directivo (perfil ligado a Deldhy Western Products S.A. de C.V.)','https://mx.linkedin.com/in/miguel-angel-del-moral-robledo-9604a3105'),
('Richard West','León','Gloria González','Fundadora',null),
('Moksman Hats','San Francisco del Rincón','Saturnino Liñán Vázquez','Titular (registrado como persona fisica en CICEG); empresa fundada por Rafael Liñán en 1975',null),
('King Walker','León','Emma Miroslava Rodríguez Solórzano','Titular (persona física registrada en CICEG)',null),
('Bucéfalo Boots','León','Alejandro Emilio Reynoso Aranda','Titular (persona física registrada en CICEG)',null),
('Sohrelia (Daniel Cázarez Pérez)','México','Daniel Cázarez Pérez','Titular del grupo (nombre con el que registra stands en ferias)',null),
('Ruditos Joe','León','Juan Enrique Aldana Zermeño','Titular / dueño (persona física registrada en CICEG)',null)
) as v(nom,ciu,pn,cg,li)
join abm_cuentas c on lower(c.nombre)=lower(v.nom) and coalesce(c.ciudad,'')=coalesce(v.ciu,'');
insert into abm_fuentes (cuenta_id,campo,url,metodo,confianza)
select c.id, 'general', v.url, 'investigacion', 'media'
from (values
('Hernández West','León','https://www.ciceg.org/site/es/Hernandez_West'),
('Botas Padilla (Industrial Padilla)','León','https://www.ciceg.org/site/es/BOTAS_PADILLA_SA_DE_CV'),
('KBallo Pasión Equina','León','https://sapica.com/expositores/'),
('Desobediente Boots','León','https://sapica.com/expositores/'),
('Centaurus Western','León','https://www.ciceg.org/site/es/MARCO_ANTONIO_MIGUEL_ANGEL_ZAVALA_MARTINEZ'),
('Deldhy Western Products','San Francisco del Rincón','https://sapica.com/expositores/'),
('Trasso Boots','León','https://www.ciceg.org/site/es/Trasso_Boots'),
('Toro Sentado','León','https://sapica.com/expositores/'),
('Botas Reyme (Reyme Export)','León','https://sapica.com/expositores/'),
('Botas y Botines Potro Salvaje','León','https://www.ciceg.org/site/es/Botas_y_Botines_Potro_Salvaje'),
('MexaBoot','León','https://www.ciceg.org/site/es/MexaBoots'),
('Botas Gran Líder','León','https://sapica.com/expositores/'),
('Arius Boots / Baby Arius','León','https://sapica.com/wp-content/uploads/2026/08/152_ARIUS_BOOTS3.png'),
('Richard West','León','https://sapica.com/expositores/'),
('Moksman Hats','San Francisco del Rincón','https://www.ciceg.org/site/es/SATURNINO_LINAN_VAZQUEZ'),
('RAM Wild Hats','San Francisco del Rincón','https://sapica.com/expositores/'),
('Catalina Vargas (Impulsora COMCA)','Guadalajara','https://catalinavargas.com/sucursales'),
('Calzado Jakuna','León','https://www.calzadojakuna.com/pages/sucursales'),
('Maquech (Lady Carolina)','León','https://www.maquechshoes.com/pages/sucursales'),
('Zapatos Karsten','León','https://www.ciceg.org/site/es/Karsten'),
('Jarking Shoes','León','https://oem.com.mx/elsoldeleon/local/jarking-shoes-35-anos-de-calzado-de-confort-premium-en-mexico-29021528'),
('Calzado Elefante (Fábrica de Calzado Plascencia)','León','https://www.ciceg.org/site/es/FABRICA_DE_CALZADO_PLASCENCIA_SA_DE_CV'),
('Calzado Bambino (Calzado Baja)','León','https://www.ciceg.org/site/es/CALZADO_BAJA_SA_DE_CV'),
('Verdetabaco (Grupo Rimar)','San Francisco del Rincón','https://www.ciceg.org/site/es/VERDETABACO'),
('Calzado Yuyin (Grupo Yuyin / Recalza Stores)','León','https://www.ciceg.org/site/es/RECALZA_STORES_SA_DE_CV'),
('Gino Cherruti (Diseños Carlo Venuty)','León','https://www.ciceg.org/site/es/DISENOS_CARLO_VENUTY_SA_DE_CV'),
('Lobo Solo','León','https://sapica.com/expositores/'),
('Cammina','León','https://sapica.com/expositores/'),
('Dr. Hosue','León','https://www.ciceg.org/site/es/Dr_Hosue'),
('Gôsh','León','https://www.ciceg.org/site/es/Gosh'),
('Alfredo Shoes de México','León','https://www.ciceg.org/site/es/ALFREDO_SHOES_DE_MEXICO_SA_DE_CV'),
('Calzado Armada (Grupo Industrial Armada del Bajío)','León','https://www.ciceg.org/site/es/GRUPO_INDUSTRIAL_ARMADA_DEL_BAJIO_S_DE_RL_DE_CV'),
('Calzado Doreli','Tepatitlán de Morelos','https://sapica.com/expositores/'),
('Zapatos Sary','Zapopan','https://sapica.com/expositores/'),
('Renatta Scottos','León','https://sapica.com/wp-content/uploads/2026/07/131_RENATTA_SCOTTOS-e1785451705649-150x150.png'),
('Soy THEA','León','https://oem.com.mx/elsoldeleon/local/soy-thea-debuta-en-sapica-95-con-calzado-inclusivo-y-colaboracion-con-wendy-guevara-31562114'),
('Milagros Shoes','León','https://sapica.com/expositores/'),
('Mímar Fashion Shoes','León','https://sapica.com/expositores/'),
('JJ Studio','México','https://sapica.com/expositores/'),
('Raúl Coss (Innova Calzado)','Guadalajara','https://sapica.com/expositores/'),
('Agavero by Arco Humming (Calzado Arco)','León','https://sapica.com/expositores/'),
('Tenis Pontiac','San Francisco del Rincón','https://www.ciceg.org/site/es/Pontiac_Tenis_24'),
('Moderof','León','https://www.ciceg.org/site/es/MODEROF'),
('Calzado Blasito','León','https://www.ciceg.org/site/es/CALZADO_BLASITO_SA_DE_CV'),
('Calzado Zull','León','https://www.ciceg.org/site/es/Calzado_Zull'),
('King Walker','León','https://www.ciceg.org/site/es/Emma_Miroslava_Rodriguez_Solorzano'),
('Castelli Leather','León','https://www.ciceg.org/site/es/Castelli_Leather'),
('Savvy & Savvy','León','https://www.ciceg.org/site/es/Savvy__Savvy'),
('Bucéfalo Boots','León','https://www.ciceg.org/site/es/ALEJANDRO_EMILIO_REYNOSO_ARANDA'),
('Piedra Angular','León','https://www.ciceg.org/site/es/Piedra_Angular'),
('Botas Bull Rider (Grupo Dosgon)','León','https://www.ciceg.org/site/es/GRUPO_DOSGON_S_DE_RL_DE_CV'),
('Pietro Alessandro','México','https://sapica.com/expositores/'),
('Sohrelia (Daniel Cázarez Pérez)','México','https://sapica.com/expositores/'),
('Ruditos Joe','León','https://www.ciceg.org/site/es/JUAN_ENRIQUE_ALDANA_ZERMENO'),
('Calzado Brenda Paulina (De Faty)','León','https://www.ciceg.org/site/es/Calzado_Brenda_Paulina_De_Faty'),
('Correrd','México','https://sapica.com/expositores/')
) as v(nom,ciu,url)
join abm_cuentas c on lower(c.nombre)=lower(v.nom) and coalesce(c.ciudad,'')=coalesce(v.ciu,'');
