-- Los primeros tres pasos de "Rezagados · top of mind", uno por carril.
-- Lunes insight, miércoles tip, viernes novedad. Cada carril rota por su cuenta.
begin;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L1 · La curva no es nacional', 'Tu curva de tallas no es una. Son cuatro.', 'Y comprar con una sola es el error más caro de una marca multitienda.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, un lunes de estos vale la pena pensar en algo que casi nadie revisa. 🧠"},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-lunes.jpg","alt":"Interior de una tienda insignia de moda de dos niveles con escalera escultórica","pie":"Cuando creces, no operas más grande. Operas distinto."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"La trampa de la segunda tienda"},{"id":"t2","tipo":"texto","texto":"Una marca con una tienda tiene **una** curva de tallas: lo que se vende ahí es lo que hay que comprar."},{"id":"t3","tipo":"texto","texto":"Con cuatro tiendas la mayoría sigue comprando igual — con una sola curva, la nacional, el promedio de todas."},{"id":"t4","tipo":"texto","texto":"Y ahí está el problema: **el promedio no existe en ninguna tienda.**"},{"id":"t5","tipo":"texto","texto":"La curva de una plaza de zona corporativa no se parece a la de una turística. Ni la de un centro histórico a la de un mall de suburbio. Cambia la talla que manda, cambia el color que sale primero, cambia hasta la semana en que se agota."},{"id":"a1","tipo":"aviso","texto":"Comprar con la curva nacional te deja siempre en el mismo lugar: **sobra en todas y falta en todas, al mismo tiempo.** Y como el total cuadra, en el reporte se ve sano."},{"id":"s1","tipo":"separador"},{"id":"h2","tipo":"encabezado","nivel":2,"texto":"Cómo se ve cuando alguien sí lo mira"},{"id":"t6","tipo":"texto","texto":"Las marcas que crecen bien hacen dos cosas distintas:"},{"id":"l1","tipo":"lista","items":["📐 **Compran por curva de tienda**, no por curva de marca. Aunque sea una sola orden al proveedor, el reparto se decide por destino.","🔁 **Nivelan antes de recomprar.** Primero acomodan lo que ya pagaron entre sus tiendas; lo que falte después, eso sí se compra."]},{"id":"t7","tipo":"texto","texto":"No es más trabajo. Es el mismo trabajo con la información partida por donde de verdad se parte."},{"id":"s2","tipo":"separador"},{"id":"t8","tipo":"texto","texto":"Si quieres platicarlo sobre tus tiendas —no en abstracto— agenda media hora conmigo. Sin costo y sin demo: nada más ver tu caso."},{"id":"b1","tipo":"boton","texto":"📅 Ver los horarios y agendar","href":"https://www.sacscloud.com/agendar/demo","sub":"30 minutos · sin costo · sobre tu operación, no sobre el sistema","align":"center"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Una forma rápida de saber si te está pasando: mira tus dos tiendas que más venden y compara qué talla se agotó primero en cada una. Si es distinta, ya tienes dos curvas."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M1 · El ejercicio de los 20 minutos', '20 minutos, un riel y una libreta', 'El ejercicio que te dice cuánto te está costando lo descabalado.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, hoy algo que puedes hacer esta misma semana. ⏱️"},{"id":"t2","tipo":"texto","texto":"No necesitas sistema ni reporte. Un riel, una libreta y veinte minutos."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-miercoles.jpg","alt":"Riel de ropa ordenado por talla con dos huecos visibles a la mitad de la corrida","pie":"Los huecos de en medio son los que cuestan. Los de las puntas casi nunca."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"El ejercicio"},{"id":"l1","tipo":"lista","items":["1️⃣ **Elige tus cinco estilos que más venden.** Los que sabes de memoria.","2️⃣ **Ordena cada uno por talla en el riel**, de la más chica a la más grande.","3️⃣ **Anota los huecos**, pero solo los de EN MEDIO. Que falte la XS o la XXL es normal; que falte la M o la L en un estilo que sí rota es otra cosa.","4️⃣ **Multiplica** los huecos de en medio por el precio de venta."]},{"id":"t3","tipo":"texto","texto":"Ese número es lo que ese riel **no puede vender esta semana**, aunque tenga piezas colgadas."},{"id":"a1","tipo":"aviso","texto":"Casi siempre sorprende, y por una razón: en el sistema esos estilos aparecen **con existencia**. Tienes piezas. Lo que no tienes es producto — a eso en el ramo se le llama estar **descabalado**, y es la palabra que más duele del negocio."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Si lo haces y el número te incomoda, escríbeme y te digo qué harían con eso las marcas que ya lo resolvieron. Sin agendar nada."},{"id":"b1","tipo":"boton","texto":"💬 Te cuento mi número","href":"https://wa.me/12058920417?text=Hola,%20hice%20el%20ejercicio%20de%20los%2020%20minutos%20y%20quiero%20platicarlo","sub":"Mándame lo que te salió y lo vemos.","align":"center"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si tienes más de una tienda, hazlo en las dos y compara. Ahí es donde casi siempre aparece la pieza que falta aquí y sobra allá."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V1 · Cinco formas de comprar', 'Nuevo en Sacs: la talla agotada ya no cuenta como muerta', 'La misma venta, cuatro compras distintas. Mira la diferencia.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, es viernes, así que te enseño algo nuevo del sistema. ✨"},{"id":"t2","tipo":"texto","texto":"Y este cambia cómo se compra una temporada."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"El problema que resuelve"},{"id":"t3","tipo":"texto","texto":"La M se agotó el día 9. Los otros cincuenta y un días vendió cero — porque no había qué vender."},{"id":"t4","tipo":"texto","texto":"Tu reporte dice que vendió 3 piezas. Igual que la XXL, que estuvo colgada dos meses."},{"id":"t5","tipo":"texto","texto":"**Parecen el mismo dato. Son lo contrario.** Y con ese hueco adentro compras la siguiente corrida."},{"id":"s1","tipo":"separador"},{"id":"h2","tipo":"encabezado","nivel":2,"texto":"Lo que ahora hace Sacs"},{"id":"t6","tipo":"texto","texto":"Detecta que la talla estuvo agotada, estima lo que **habría** vendido, y te deja elegir con qué criterio. Mira cómo cambia la compra del mismo estilo:"},{"id":"i2","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-viernes.gif","alt":"Animación: la misma venta con cuatro métodos distintos de compra y su total cambiando","pie":"El mismo estilo. Entre el método más generoso y el más conservador, 13 piezas de diferencia."},{"id":"l1","tipo":"lista","items":["⚖️ **Promedio de tallas hermanas** — el recomendado para empezar.","🔢 **Mínimo fijo por talla** — tú defines cuántas.","📈 **Histórico de esa talla** — si antes vendía y ahora no había.","📐 **Plantilla de curva por categoría** — tu curva objetivo, S:1 M:3 L:3 XL:2.","🚫 **No estimar** — solo marca el hueco y decides tú."]},{"id":"a1","tipo":"aviso","texto":"El detalle que más nos gusta: si esa categoría no tiene curva definida, el cuarto método **cae solo al promedio** en vez de tronar. Eso no se le ocurre a quien no ha vivido una temporada de compras."},{"id":"i3","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-compra.jpg","alt":"Módulo de órdenes de compra de Sacs con la sugerencia por talla","pie":"Órdenes de compra ▸ Nueva orden. Ahí vive."},{"id":"s2","tipo":"separador"},{"id":"t7","tipo":"texto","texto":"¿Quieres verlo con un estilo tuyo? Mándame el que se te haya descabalado más rápido esta temporada y te enseño cuánto cambia la orden con cada método."},{"id":"b1","tipo":"boton","texto":"💬 Pruébalo con un estilo mío","href":"https://wa.me/12058920417?text=Hola,%20quiero%20ver%20los%20metodos%20de%20compra%20con%20un%20estilo%20mio","sub":"Con tus números, no con un ejemplo.","align":"center"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Esto ya está vivo en todas las cuentas. Si tienes Sacs abierto, está en Inventarios ▸ Órdenes de compra."}]'::jsonb, true) on conflict do nothing;

insert into crm_secuencia_pasos (secuencia_id, orden, dia, dia_semana, canal, email_template_id, activo)
select s.id, p.orden, 1, p.dsem, 'correo', t.id, true
from crm_secuencias s
cross join (values
  (1, 1, 'Rezagados L1 · La curva no es nacional'),
  (2, 3, 'Rezagados M1 · El ejercicio de los 20 minutos'),
  (3, 5, 'Rezagados V1 · Cinco formas de comprar')
) as p(orden, dsem, plantilla)
join email_templates t on t.nombre = p.plantilla
where s.nombre = 'Rezagados · top of mind';
commit;
