-- Secuencia "Prueba gratis · 14 días": del primer login al nivelador.
-- Ocho correos, uno cada dos días. Cada uno enseña DÓNDE está la cosa (con
-- captura del sistema real), para qué sirve, qué hacer hoy y qué viene después.
-- Todos cierran con WhatsApp: la ayuda es el CTA, no la venta.
begin;
delete from crm_secuencia_pasos where secuencia_id in (select id from crm_secuencias where nombre = 'Prueba gratis · 14 días');
delete from email_templates where nombre like 'Prueba % · %';

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Prueba 1 · La Academia', 'Tu prueba empieza ganando $500', 'La Academia te paga por aprender. Literalmente.', 'automatizado', 'simple', 'onboarding',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, ya tienes Sacs abierto. Bienvenida. 🎉"},{"id":"t2","tipo":"texto","texto":"Catorce días para probarlo. Y para que no se te vayan en dar vueltas, te voy a llevar de la mano: un paso por correo, del más simple al más avanzado."},{"id":"t3","tipo":"texto","texto":"Hoy el primero, y es el que más te conviene."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"La Academia te paga por aprender"},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-academia.jpg","alt":"Pantalla de la Academia con el avance en 75%, nivel 4 y 1,500 pesos ganados","pie":"Así se ve cuando llevas cuatro de seis módulos."},{"id":"r1","tipo":"aviso","texto":"📍 **Dónde está:** el menú de la izquierda, arriba del Dashboard. Se llama **Academia**."},{"id":"t4","tipo":"texto","texto":"No son videos sueltos. Son **6 módulos y 59 tareas** que te llevan de cero a operar como los que ya llevan años."},{"id":"t5","tipo":"texto","texto":"Y mientras avanzas, se acumula dinero real:"},{"id":"m1","tipo":"metricas","items":[{"cifra":"$500","texto":"en saldo Sacs por el curso"},{"cifra":"1 licencia","texto":"gratis para regalar"},{"cifra":"6 módulos","texto":"de cero a avanzado"}]},{"id":"t6","tipo":"texto","texto":"El saldo lo cambias por plugins y consultorías. La licencia es para que se la regales a otro empresario que conozcas."},{"id":"a1","tipo":"aviso","texto":"Empieza por el **Curso 1 · Ponte en Marcha**. Son las bases: si haces solo eso, el resto de estos catorce días te va a costar la mitad de trabajo."},{"id":"s1","tipo":"separador"},{"id":"t7","tipo":"texto","texto":"**Lo que sigue:** en dos días te enseño a cargar tu primer producto. Hoy solo entra a la Academia y haz la primera tarea — con una se te enciende la racha. 🔥"},{"id":"b1","tipo":"boton","texto":"💬 ¿Se te complica entrar?","align":"center","sub":"Escríbeme y te acompaño en el primer módulo.","href":"https://wa.me/12058920417?text=Hola%20Andrea,%20estoy%20en%20mi%20prueba%20de%20Sacs%20y%20quiero%20empezar%20la%20Academia"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si prefieres que alguien te lo enseñe en vivo en vez de leer, dímelo por WhatsApp. Hago una llamada corta contigo y avanzamos juntos el primer módulo."}]'::jsonb, true);

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Prueba 2 · Tu primer producto', 'Sube tu primer producto (5 minutos)', 'Uno solo. El más fácil que tengas.', 'automatizado', 'simple', 'onboarding',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, hoy algo corto y concreto: **un producto.**"},{"id":"t2","tipo":"texto","texto":"No tu catálogo entero. Uno."},{"id":"t3","tipo":"texto","texto":"Porque hasta que no ves tu propia prenda dentro del sistema, todo esto es teoría."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-catalogo.jpg","alt":"Encabezado del Catálogo de productos con el botón Nuevo Producto","pie":"Catálogo de productos. El botón azul de la derecha es por donde se empieza."},{"id":"r1","tipo":"aviso","texto":"📍 **Dónde está:** menú izquierdo ▸ **Inventarios ▸ Catálogo de productos** ▸ botón **+ Nuevo Producto**."},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Qué llenar, y qué puedes dejar en blanco"},{"id":"l1","tipo":"lista","items":["✅ **Nombre** — como le dices tú, no como viene en la factura del proveedor.","✅ **Precio de venta** — el de la etiqueta.","✅ **Costo** — lo que te costó. Sin esto no hay margen, y sin margen no hay reportes que sirvan.","⬜ **Todo lo demás** puede esperar. Marca, proveedor, código de barras: se llenan después y se llenan solos cuando cargues el resto."]},{"id":"a1","tipo":"aviso","texto":"Elige un producto **sin tallas** para esta primera vez — un accesorio, una bolsa, un perfume. Las tallas son el paso de pasado mañana y merecen su propio correo."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"**Lo que sigue:** en dos días, el paso que de verdad cambia todo si vendes ropa — una prenda con sus tallas y sus colores."},{"id":"b1","tipo":"boton","texto":"💬 Mándame tu producto y lo reviso","align":"center","sub":"Mándame una captura y te digo si le falta algo.","href":"https://wa.me/12058920417?text=Hola%20Andrea,%20ya%20subi%20mi%20primer%20producto%20y%20quiero%20que%20lo%20revises"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. ¿Tienes tu catálogo en un Excel? No lo captures a mano. Escríbeme y te digo cómo subirlo de un jalón — es de las cosas que hacemos contigo, no algo que te dejemos de tarea."}]'::jsonb, true);

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Prueba 3 · Tallas y colores', 'Una blusa no es un producto. Son 24.', 'Talla × color. El paso que separa un sistema de moda de uno genérico.', 'automatizado', 'simple', 'onboarding',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este es el correo que más importa si vendes ropa."},{"id":"t2","tipo":"texto","texto":"Ayer subiste un producto simple. Hoy uno con **tallas y colores** — y ahí es donde la mayoría de los sistemas se rompen."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Piensa en una blusa. Seis tallas, cuatro colores."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/moda/moda-matriz.png","alt":"Matriz de tallas y colores con siete celdas en cero","pie":"Un solo modelo. Veinticuatro piezas distintas que comprar, guardar y contar."},{"id":"t4","tipo":"texto","texto":"**No es un producto. Son veinticuatro.** Cada uno con su existencia, su código y su venta."},{"id":"t5","tipo":"texto","texto":"Y las que están en cero son, casi siempre, las que te están pidiendo."},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Cómo se carga"},{"id":"r1","tipo":"aviso","texto":"📍 **Dónde está:** **Catálogo de productos ▸ + Nuevo Producto**, y ahí activa las **variantes**. Defines los ejes (talla, color) y el sistema arma la matriz solo."},{"id":"l1","tipo":"lista","items":["🎽 **Un solo producto padre.** «Blusa satinada», no «Blusa satinada negra M».","📐 **Los ejes que tú uses.** Talla y color, o número y ancho si vendes calzado. Tú los defines.","🔢 **Existencia por variante.** Cada talla de cada color lleva su propia cuenta, en cada tienda."]},{"id":"a1","tipo":"aviso","texto":"En el catálogo verás un interruptor que dice **Desglosar variantes**. Préndelo y la lista pasa de enseñarte «una blusa» a enseñarte las veinticuatro. Es la vista que vas a usar todos los días."},{"id":"s1","tipo":"separador"},{"id":"t5b","tipo":"texto","texto":"**Lo que sigue:** en dos días abres caja y vendes esa prenda. Con su talla."},{"id":"b1","tipo":"boton","texto":"💬 Te ayudo a armar tu primera matriz","align":"center","sub":"Es el paso donde más gente se atora. Escríbeme y lo hacemos juntas.","href":"https://wa.me/12058920417?text=Hola%20Andrea,%20quiero%20cargar%20un%20producto%20con%20tallas%20y%20colores"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si vendes calzado, aquí va un detalle que casi ningún sistema hace bien: la talla **22.5** se ordena entre la 22 y la 23, no al final de la lista. Pruébalo."}]'::jsonb, true);

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Prueba 4 · Tu primera venta', 'Abre caja y vende tu primera prenda', 'Con su talla. El momento en que el sistema deja de ser una demo.', 'automatizado', 'simple', 'onboarding',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, ya tienes producto. Hoy lo vendes. 🛍️"},{"id":"t2","tipo":"texto","texto":"Y quiero que lo hagas aunque sea una venta de práctica, porque hasta que no pasa una venta por el sistema, el inventario es una lista bonita que no se mueve."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-pos.jpg","alt":"Punto de venta de Sacs en una boutique","pie":"El punto de venta: donde el inventario deja de ser teoría."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Primero: abre la caja"},{"id":"r1","tipo":"aviso","texto":"📍 **Dónde está:** menú izquierdo ▸ **Punto de Venta**. Si es tu primera vez, te va a recibir una pantalla que dice **«Caja registradora cerrada»**."},{"id":"t3","tipo":"texto","texto":"No es un error. Es el primer control del sistema: te pide **cuánto dinero hay en la caja** antes de dejarte vender."},{"id":"t4","tipo":"texto","texto":"Pon el fondo con el que abres tu día —o cualquier número si estás practicando— y dale **Abrir caja**."},{"id":"a1","tipo":"aviso","texto":"Esto es lo que hace que al final del día el corte cuadre o no cuadre. Si abres sin declarar el fondo, tu corte va a estar mal siempre y nunca vas a saber por qué."},{"id":"h2","tipo":"encabezado","nivel":2,"texto":"Ahora vende"},{"id":"l1","tipo":"lista","items":["🔎 **Busca tu producto** por nombre o pásale el código de barras.","📐 **Elige la talla y el color.** Si cargaste variantes, aquí las vas a ver — y solo las que tienen existencia.","💵 **Cobra.** Efectivo, tarjeta, o mixto.","🧾 **Ticket.** Se imprime o se manda por WhatsApp."]},{"id":"t5","tipo":"texto","texto":"Cuando termines, regresa al catálogo y mira tu producto: **la existencia bajó sola.** Eso es todo el sistema funcionando en una sola línea."},{"id":"s1","tipo":"separador"},{"id":"t6","tipo":"texto","texto":"**Lo que sigue:** en dos días, dónde está cada talla cuando tienes más de una tienda."},{"id":"b1","tipo":"boton","texto":"💬 Acompáñame en mi primera venta","align":"center","sub":"Te acompaño en vivo mientras la haces. Toma cinco minutos.","href":"https://wa.me/12058920417?text=Hola%20Andrea,%20quiero%20hacer%20mi%20primera%20venta%20en%20el%20punto%20de%20venta"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. ¿Vendes también por WhatsApp o Instagram? Esa venta también puede entrar aquí y descontar del mismo inventario. Pregúntame y te enseño cómo se conecta."}]'::jsonb, true);

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Prueba 5 · Dónde está cada talla', '¿Te queda la M? — y la respuesta en 3 segundos', 'Existencia por talla, en cada tienda, sin llamar a nadie.', 'automatizado', 'simple', 'onboarding',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, la pregunta más común de tu mostrador:"},{"id":"t2","tipo":"texto","texto":"**«¿Te queda esta en chica?»**"},{"id":"t3","tipo":"texto","texto":"Y la respuesta honesta hoy, en la mayoría de las marcas, es: *«déjame llamo a la otra tienda».*"},{"id":"t4","tipo":"texto","texto":"Para cuando contestan, la clienta ya se fue."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-existencias.jpg","alt":"Vista de inventario con existencias por sucursal","pie":"Una prenda, todas tus tiendas, cada talla con su número."},{"id":"r1","tipo":"aviso","texto":"📍 **Dónde está:** menú izquierdo ▸ **Inventarios ▸ Existencias por sucursal**. También sale desde el producto, en **Ver más**."},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Para qué sirve de verdad"},{"id":"l1","tipo":"lista","items":["👗 **Contestarle a la clienta con el celular en la mano**, sin llamar a nadie.","🔁 **Ver dónde sobra lo que aquí falta.** Es el primer paso del traspaso.","📉 **Descubrir tus huecos.** Las tallas en cero que tú creías tener."]},{"id":"a1","tipo":"aviso","texto":"Esa venta que se pierde porque la talla estaba en la otra tienda **no aparece en ningún reporte** — una venta que no ocurrió no se registra. Por eso casi nadie sabe cuánto le cuesta."},{"id":"s1","tipo":"separador"},{"id":"t5","tipo":"texto","texto":"**Lo que sigue:** en dos días, cómo se compra la próxima temporada sin repetir los errores de esta."},{"id":"b1","tipo":"boton","texto":"💬 ¿Cuántas tiendas tienes?","align":"center","sub":"Dime cuántas son y te enseño cómo se ve tu tablero.","href":"https://wa.me/12058920417?text=Hola%20Andrea,%20quiero%20ver%20como%20se%20veria%20mi%20inventario%20entre%20tiendas"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si por ahora solo tienes una tienda, esta pantalla igual te sirve: te enseña qué tallas están en cero, que es la mitad de la información para tu próxima compra."}]'::jsonb, true);

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Prueba 6 · Comprar sin repetir el error', 'La talla que vendió cero porque nunca estuvo', 'El error más caro de la moda, y cómo el sistema lo evita.', 'automatizado', 'simple', 'onboarding',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, ya vendiste, ya sabes dónde está tu inventario. Ahora lo caro: **comprar.**"},{"id":"s0","tipo":"separador"},{"id":"t2","tipo":"texto","texto":"La M se agotó el día 9. 📉"},{"id":"t3","tipo":"texto","texto":"Los otros cincuenta y un días vendió cero — no porque nadie la quisiera, sino porque no había."},{"id":"t4","tipo":"texto","texto":"Cuando llega el momento de comprar, tu reporte dice que la M vendió 3 piezas. Y que la XXL vendió 3 piezas."},{"id":"t5","tipo":"texto","texto":"**Parecen el mismo dato. Son lo contrario.**"},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-compra.jpg","alt":"Módulo de órdenes de compra con sugerencia","pie":"La orden de compra: aquí se decide la temporada que viene."},{"id":"r1","tipo":"aviso","texto":"📍 **Dónde está:** menú izquierdo ▸ **Inventarios ▸ Órdenes de compra** ▸ **+ Nueva orden**. Arriba tiene un botón de **Cómo usar**."},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Lo que hace distinto"},{"id":"t6","tipo":"texto","texto":"Cuando el sistema detecta que una talla estuvo agotada, **no la cuenta como talla muerta.** Estima lo que habría vendido, y te deja elegir cómo:"},{"id":"l1","tipo":"lista","items":["⚖️ **Promedio de tallas hermanas** — el recomendado para empezar.","📈 **Histórico de esa talla** — si antes vendía y ahora no había.","📐 **Plantilla de curva por categoría** — tu curva objetivo, S:1 M:3 L:3 XL:2.","🚫 **No estimar** — solo te marca el hueco y decides tú."]},{"id":"a1","tipo":"aviso","texto":"Prueba los cuatro sobre el mismo estilo y mira cómo cambia el total. Entre el más generoso y el más conservador suele haber **más de diez piezas de diferencia — de un solo estilo.**"},{"id":"s1","tipo":"separador"},{"id":"t7","tipo":"texto","texto":"**Lo que sigue:** el último paso, y el que más dinero mueve — mover en vez de comprar."},{"id":"b1","tipo":"boton","texto":"💬 Pruébalo con un estilo tuyo","align":"center","sub":"Tráeme el que se te descabaló más rápido y lo vemos juntas.","href":"https://wa.me/12058920417?text=Hola%20Andrea,%20quiero%20probar%20la%20orden%20de%20compra%20con%20un%20estilo%20de%20mi%20temporada%20pasada"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. «Descabalado» es cuando de un estilo ya solo te quedan la XS y la XXL. Tienes piezas, pero no tienes producto. Es la palabra que más duele del negocio y el sistema la entiende."}]'::jsonb, true);

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Prueba 7 · Mover en vez de comprar', 'No hay que comprar. Hay que mover.', 'El último paso, y el que más dinero devuelve.', 'automatizado', 'simple', 'onboarding',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, llegamos al final del recorrido. Y este es el que más dinero mueve."},{"id":"s0","tipo":"separador"},{"id":"t2","tipo":"texto","texto":"En una tienda falta la M. En otra sobra."},{"id":"t3","tipo":"texto","texto":"La encargada de la primera la pide en la siguiente compra — y hace bien, desde donde ella ve no hay."},{"id":"t4","tipo":"texto","texto":"**Pero ya la pagaste.** Está a cuarenta minutos, colgada, envejeciendo, camino a la rebaja."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-nivelacion.jpg","alt":"Módulo de nivelación con propuesta de traspasos","pie":"La nivelación: el sistema ve el hueco y el excedente, y propone el movimiento."},{"id":"r1","tipo":"aviso","texto":"📍 **Dónde está:** menú izquierdo ▸ **Inventarios ▸ Nivelación** ▸ **+ Nueva nivelación**. El botón **Explorar el mapa** te enseña dónde está todo antes de decidir."},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Qué hace"},{"id":"l1","tipo":"lista","items":["🔁 **Encuentra los pares.** Dónde falta y dónde sobra, talla por talla, color por color.","📋 **Propone el traspaso.** Con su documento, no en la camioneta del gerente.","✅ **Tú apruebas.** Nada se mueve sin que alguien diga que sí."]},{"id":"a1","tipo":"aviso","texto":"Aquí es donde termina la Academia y empieza operar como los que llevan años. Si llegaste hasta este correo haciendo los pasos, ya sabes más de tu inventario que la mayoría de las marcas de tu tamaño."},{"id":"s1","tipo":"separador"},{"id":"t5","tipo":"texto","texto":"**Lo que sigue:** mañana te mando el resumen de lo que lograste en estos catorce días."},{"id":"b1","tipo":"boton","texto":"💬 Quiero ver esto con mi inventario","align":"center","sub":"Con tus tiendas y tus tallas, no con datos de ejemplo.","href":"https://wa.me/12058920417?text=Hola%20Andrea,%20quiero%20ver%20la%20nivelacion%20con%20mi%20inventario%20real"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Este módulo es el que más se usa en las marcas con varias tiendas. Si solo tienes una hoy, guárdalo: el día que abras la segunda, es lo primero que vas a querer prender."}]'::jsonb, true);

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Prueba 8 · Lo que lograste', 'Catorce días. Esto es lo que ya sabes hacer.', 'Y qué pasa mañana con tu cuenta.', 'automatizado', 'simple', 'onboarding',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, hoy se cumplen tus catorce días."},{"id":"t2","tipo":"texto","texto":"Antes de hablar de lo que sigue, mira lo que ya sabes hacer:"},{"id":"l1","tipo":"lista","items":["🎓 Entraste a la **Academia** y empezaste a ganar saldo.","🏷️ Cargaste **tu primer producto**, y luego uno con **tallas y colores**.","🛍️ Abriste caja y **vendiste**, y viste la existencia bajar sola.","🏬 Encontraste **dónde está cada talla** en cada tienda.","🛒 Armaste una **orden de compra** que distingue lo que no gustó de lo que se acabó.","🔁 Viste la **nivelación** proponer traspasos en vez de compras."]},{"id":"t3","tipo":"texto","texto":"Eso no es haber visto un demo. Es haber operado."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Qué pasa ahora"},{"id":"t4","tipo":"texto","texto":"Tu cuenta no se borra. Lo que cargaste se queda: tus productos, tus ventas de práctica, tu avance en la Academia."},{"id":"t5","tipo":"texto","texto":"Lo que cambia es que a partir de mañana necesitas un plan para seguir operando."},{"id":"a1","tipo":"aviso","texto":"Y si algo de estos catorce días no te terminó de convencer, eso es lo que más quiero saber. Dímelo tal cual — sirve más que un «sí, luego lo vemos»."},{"id":"s1","tipo":"separador"},{"id":"h2","tipo":"encabezado","nivel":2,"texto":"Tres formas de seguir"},{"id":"l2","tipo":"lista","items":["🚀 **Arrancamos.** Escríbeme y vemos qué plan te toca según tus tiendas y tu catálogo.","📅 **Necesito más tiempo.** Dímelo y vemos cómo extenderte la prueba — pasa más seguido de lo que crees.","🤔 **Todavía tengo dudas.** Escríbeme cuál y la resolvemos. Sin junta si no quieres."]},{"id":"b1","tipo":"boton","texto":"💬 Hablemos de lo que sigue","align":"center","sub":"Un mensaje y lo resolvemos.","href":"https://wa.me/12058920417?text=Hola%20Andrea,%20terminaron%20mis%2014%20dias%20de%20prueba%20y%20quiero%20platicar"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si terminaste el Curso 1 de la Academia, ganaste una **licencia de Sacs gratis para regalar** a otro empresario. Está en tu cuenta esperando — pregúntame cómo se entrega. 🎁"}]'::jsonb, true);

insert into crm_secuencias (nombre, descripcion, activa, entrada, corte_dias, objetivo, dias_envio, hora_inicio, hora_fin)
values (
  'Prueba gratis · 14 días',
  'Del primer login al nivelador. Ocho correos que enseñan DÓNDE está cada cosa con captura del sistema, para qué sirve y qué hacer hoy — de subir un producto simple a mover inventario entre tiendas. El CTA no es comprar: es que pregunte por WhatsApp.',
  false,
  '{"estatus": ["nuevo", "contactado", "respondio", "agendado"], "lifecycle": ["prueba_gratis"]}'::jsonb,
  16, 'convertido', '[1,2,3,4,5,6]'::jsonb, 9, 19)
on conflict do nothing;

insert into crm_secuencia_pasos (secuencia_id, orden, dia, canal, email_template_id, activo)
select s.id, p.orden, p.dia, 'correo', t.id, true
from crm_secuencias s
cross join (values
  (1, 1, 'Prueba 1 · La Academia'),
  (2, 3, 'Prueba 2 · Tu primer producto'),
  (3, 5, 'Prueba 3 · Tallas y colores'),
  (4, 7, 'Prueba 4 · Tu primera venta'),
  (5, 9, 'Prueba 5 · Dónde está cada talla'),
  (6, 11, 'Prueba 6 · Comprar sin repetir el error'),
  (7, 13, 'Prueba 7 · Mover en vez de comprar'),
  (8, 14, 'Prueba 8 · Lo que lograste')
) as p(orden, dia, plantilla)
join email_templates t on t.nombre = p.plantilla
where s.nombre = 'Prueba gratis · 14 días';
commit;
