-- «Rumbo a la renovación»: los seis correos.
--
-- Usan variables que hasta ahora nadie llenaba: {{fecha_renovacion}},
-- {{monto_renovacion}}, {{monto_10}}, {{ahorro_10}}, {{limite_10}} y sus
-- gemelas del 5%. Las calcula lib/crm/renovacion.ts desde la suscripción real
-- del cliente, en UN solo lugar — si el 10% se calculara en cada plantilla, el
-- correo, el WhatsApp y el mensaje in-app dirían números distintos en cuanto
-- alguien tocara uno.
--
-- Los correos 2, 3 y 4 son los tres de la sesión con consultor, y ninguno
-- repite el argumento del anterior: el primero pregunta qué le cuesta trabajo,
-- el segundo explica que no vemos POR QUÉ no usa lo que no usa, y el tercero
-- dice para qué la queremos de verdad y ofrece dejar de insistir.
--
-- El correo 1 no vende nada. A propósito: es lo único que se manda a 90 días.
begin;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Renovación 1 · Tu año en números', '{{empresa|Tu marca}}: así se ve tu año en Sacs', 'Sin pedirte nada. Solo lo que pasó.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, tu renovación es el **{{fecha_renovacion}}**, así que en los próximos días vamos a platicar de eso."},{"id":"t2","tipo":"texto","texto":"Pero hoy no. Hoy solo quiero enseñarte lo que pasó este año, porque cuando uno está adentro no lo ve."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Lo que hiciste con Sacs"},{"id":"t3","tipo":"texto","texto":"Estos números salen de tu propia cuenta, no de un promedio:"},{"id":"a1","tipo":"aviso","texto":"👉 **Este bloque se arma con los datos reales de cada cliente** —ventas, tickets, productos, usuarios, cortes— desde `uso_sacs`. Aquí va la versión personalizada de cada uno."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Un sistema no se mide por lo que promete sino por cuántas veces lo abriste. Y eso, en tu caso, tiene un número."},{"id":"t5","tipo":"texto","texto":"En unos días te escribo para proponerte media hora de revisión. Por ahora, nada más quería que lo vieras."},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si algo de arriba no te cuadra, dímelo. Prefiero corregir un dato que dejarte con la duda."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Renovación 2 · Media hora para lo que te cuesta trabajo', '¿Qué es lo que más batalla te da hoy?', 'No es soporte. Es la conversación que no cabe en un ticket.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, una pregunta directa: **¿qué es lo que más batalla te da hoy en tu operación?**"},{"id":"t2","tipo":"texto","texto":"No hablo de un error del sistema — para eso está soporte. Hablo de lo otro: eso que resuelves a mano cada semana porque nunca ha habido tiempo de sentarse a verlo."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Para qué sirve la sesión"},{"id":"l1","tipo":"lista","items":["🔍 **Te escuchamos primero.** Qué haces hoy, con qué te tropiezas, qué llevas dos meses posponiendo.","🛠️ **Te decimos qué se puede resolver ya** — a veces es una configuración de diez minutos que nadie te enseñó.","🧭 **Y qué no.** Si algo no lo hace Sacs, es mejor que lo sepas por nosotros."]},{"id":"a1","tipo":"aviso","texto":"Son **30 minutos y no cuestan nada**, ni ahora ni si decides no renovar. No es una junta de ventas: es la que debimos tener hace seis meses."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Agendar la sesión","href":"https://www.sacscloud.com/agendar/consultoria","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si prefieres escribirme la duda y ya, también sirve. Pero casi siempre lo que se cuenta en media hora no cabe en un mensaje."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Renovación 3 · Lo que no se ve desde afuera', 'Hay cosas que no sabemos que te faltan', 'Y solo salen platicando.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, te insisto con la sesión, pero por una razón distinta a la de la vez pasada."},{"id":"t2","tipo":"texto","texto":"Desde aquí vemos **qué módulos usas**. Lo que no vemos es **por qué no usas los otros**."},{"id":"t3","tipo":"texto","texto":"Y esas dos cosas se parecen poco:"},{"id":"l1","tipo":"lista","items":["🚪 A veces no lo usas porque no lo necesitas — perfecto, no hay nada que hacer.","🤷 A veces porque no sabías que existía.","😤 Y a veces porque lo intentaste una vez, no se entendió, y no volviste."]},{"id":"a1","tipo":"aviso","texto":"El tercero es el que nos duele, y es el único que no se ve en ningún reporte. **Solo sale platicando.**"},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Media hora, con alguien que conoce el sistema por dentro y tu giro por fuera."},{"id":"b1","tipo":"boton","texto":"📅 Agendar la sesión","href":"https://www.sacscloud.com/agendar/consultoria","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Puedes traer a quien lo opera contigo. Muchas veces quien mejor sabe qué falta no es quien contrata."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Renovación 4 · La última antes de tu renovación', 'Antes de que decidas, platiquemos', 'Media hora. Aunque al final decidas que no.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, tu renovación es el **{{fecha_renovacion}}** — faltan poco más de cinco semanas."},{"id":"t2","tipo":"texto","texto":"Es la tercera vez que te ofrezco la sesión y también la última, así que voy a ser claro con para qué la quiero."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"**Para saber si te estamos sirviendo.** Si la respuesta es sí, quiero entender en qué para hacerlo más. Si es no, prefiero saberlo ahora y no el día que decidas no renovar, cuando ya no hay nada que arreglar."},{"id":"a1","tipo":"aviso","texto":"La sesión sigue siendo sin costo **aunque al final decidas no continuar**. No es una condición: es que una conversación honesta vale igual en los dos casos."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Agendar los 30 minutos","href":"https://www.sacscloud.com/agendar/consultoria","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"t4","tipo":"texto","texto":"Y si no es momento, con que me contestes «ahorita no» me basta. Dejo de insistir con esto y seguimos."},{"id":"b2","tipo":"boton","texto":"📲 Escribir por WhatsApp","align":"center","sub":"¿Prefieres escribirme? También sirve","href":"https://wa.me/12058920417?text=Hola,%20sobre%20la%20sesion%20antes%20de%20mi%20renovacion"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Renovación 5 · Renueva antes y te ahorras {{ahorro_10|un 10%}}', '{{ahorro_10|10%}} menos si renuevas antes del {{limite_10}}', 'Tu renovación, con descuento por anticipación.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, ahora sí, la parte del dinero."},{"id":"t2","tipo":"texto","texto":"Tu renovación de **{{plan}}** es el **{{fecha_renovacion}}** por **{{monto_renovacion}}**."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Y hay dos formas de pagar menos"},{"id":"m1","tipo":"metricas","items":[{"cifra":"10%","texto":"si renuevas antes del {{limite_10}}"},{"cifra":"5%","texto":"si renuevas antes del {{limite_5}}"}]},{"id":"t3","tipo":"texto","texto":"Con el 10% tu renovación queda en **{{monto_10}}** — te ahorras **{{ahorro_10}}**."},{"id":"a1","tipo":"aviso","texto":"No es una promoción de temporada ni un precio que se negocia. Es simplemente que **renovar con anticipación nos ahorra trabajo a los dos**, y esa parte te la devolvemos."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Si quieres ajustar algo antes de renovar —sucursales de más o de menos, cambiar de plan, agregar o quitar módulos— este es el momento. Escríbeme y lo vemos."},{"id":"b1","tipo":"boton","texto":"📲 Escribir por WhatsApp","align":"center","sub":"Renovar o ajustar tu plan","href":"https://wa.me/12058920417?text=Hola,%20quiero%20renovar%20aprovechando%20el%20descuento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Después del {{limite_10}} el descuento baja a 5%, y después del {{limite_5}} queda el precio normal. Nada más para que lo tengas."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Renovación 6 · Últimos días del 5%', 'Quedan pocos días para el 5% en tu renovación', 'Después de esto, precio normal.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, aviso corto."},{"id":"t2","tipo":"texto","texto":"El 10% ya pasó, pero **hasta el {{limite_5}} tu renovación sale en {{monto_5}}** en vez de {{monto_renovacion}}. Son **{{ahorro_5}}** de diferencia."},{"id":"t3","tipo":"texto","texto":"Tu fecha sigue siendo el **{{fecha_renovacion}}**."},{"id":"a1","tipo":"aviso","texto":"Después de esa fecha no pasa nada malo: renuevas al precio normal y ya. Te lo digo porque preferiría que lo aprovecharas a que te enteres cuando ya no aplica."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Un mensaje y lo dejamos listo."},{"id":"b1","tipo":"boton","texto":"📲 Escribir por WhatsApp","align":"center","sub":"Renovar antes del {{limite_5}}","href":"https://wa.me/12058920417?text=Hola,%20quiero%20renovar%20con%20el%205%"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Y si todavía quieres la media hora de revisión antes de decidir, sigue en pie."}]'::jsonb, true) on conflict do nothing;

commit;
