-- Tres correos más para «Crecimiento · lo que sigue»: subir de plan,
-- el catálogo con IA y la renta de productos.
--
-- EL DEL PLAN ES DINÁMICO. Lee el plan que el cliente tiene hoy y le cuenta el
-- que sigue —vende→controla→fideliza→automatiza— con TRES puntos concretos, no
-- con la tabla comparativa. La descripción del catálogo («todo lo de Controla
-- más…») sirve para una página de precios y no para un correo: a un cliente no
-- le mueve leer una lista de módulos, le mueve saber qué deja de hacer a mano.
--
-- Y si ya está en el tope, el correo NO se manda: el contexto sale null y el
-- paso se salta con motivo. Ofrecerle subir a quien ya está arriba es la forma
-- más rápida de que deje de leerte.
begin;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 8 · Lo que trae el plan que sigue', 'Estás en {{plan_actual|tu plan}}. Esto es lo que trae {{plan_siguiente|el siguiente}}', 'Tres cosas concretas, no una lista de módulos.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, hasta ahora te he mostrado extensiones sueltas. Hoy va lo otro: **el escalón completo**."},{"id":"t2","tipo":"texto","texto":"Estás en **{{plan_actual}}**. El que sigue es **{{plan_siguiente}}**, y no te voy a mandar la tabla comparativa — te digo las tres cosas que de verdad cambian en tu semana:"},{"id":"s0","tipo":"separador"},{"id":"l1","tipo":"lista","items":["✅ **{{punto_1}}**","✅ **{{punto_2}}**","✅ **{{punto_3}}**"]},{"id":"s1","tipo":"separador"},{"id":"a1","tipo":"aviso","texto":"Subir de plan no es empezar de nuevo: **conservas todo** —tu catálogo, tus clientes, tu histórico— y lo que cambia es qué puedes hacer con ello. Lo que implica en tu caso lo vemos contigo, según tus sucursales."},{"id":"t3","tipo":"texto","texto":"Y si con {{plan_actual}} vas bien, dímelo sin pena. No todo el mundo necesita subir, y prefiero decírtelo yo a que lo descubras pagando de más."},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20saber%20que%20trae%20el%20plan%20que%20sigue%20en%20mi%20caso","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si lo que te interesa es una sola cosa del que sigue, a veces se resuelve con una extensión y sale más barato. También te lo digo."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 9 · Tu catálogo, con inteligencia artificial', 'Fotos de modelo y probador virtual, con las prendas que ya tienes', 'Sin sesión de fotos y sin modelo.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este es el que más cara pone la gente cuando lo ve. 📸"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Dos cosas, y las dos salen de tu catálogo"},{"id":"t2","tipo":"texto","texto":"**Modelos con IA.** Subes la foto de la prenda —la de siempre, sobre el maniquí o colgada— y sale puesta en una persona. Distintos cuerpos, distintos tonos de piel, el fondo que quieras. Sin sesión, sin estudio y sin agendar a nadie."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/moda/moda-probador.jpg","alt":"Clienta frente a un espejo de probador con una prenda","pie":"La prenda es la tuya. El modelo, no."},{"id":"t3","tipo":"texto","texto":"**Probador virtual.** Tu clienta ve cómo se le vería a ella, no a una modelo. Y como sale de tu catálogo, lo que se prueba es lo que **sí tienes** en su talla — no una foto bonita de algo agotado."},{"id":"a1","tipo":"aviso","texto":"Lo que resuelve no es el diseño: es el cuello de botella. Publicar deja de depender de que alguien tenga la tarde libre para fotografiar cincuenta prendas nuevas."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Si quieres, mándame una foto de un producto tuyo por WhatsApp y te la regreso hecha. Es la forma más rápida de que veas si te sirve."},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20probar%20las%20fotos%20con%20IA%20con%20un%20producto%20mio","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 10 · Rentar en vez de vender', 'La misma prenda, cobrada muchas veces', 'Otro modelo de negocio con el inventario que ya tienes.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, el último, y es un cambio de modelo más que un módulo. 👗"},{"id":"t2","tipo":"texto","texto":"Una prenda cara se vende una vez. **Rentada deja dinero seis, ocho, doce veces** — y el problema nunca fue la idea, fue llevar la cuenta."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Renta, dentro del mismo sistema"},{"id":"l1","tipo":"lista","items":["📅 **Calendario por prenda**: quién la tiene, qué días está apartada y cuándo regresa.","💵 **Depósito en garantía**, con su movimiento en caja al salir y al volver.","🧵 **Estado a la devolución**: si vuelve dañada, se cobra el ajuste y queda en su ficha.","🔁 **Cuánto lleva generado cada pieza** contra lo que costó."]},{"id":"a1","tipo":"aviso","texto":"Ese último número es el que nadie tiene: **cuánto ha pagado esa prenda de sí misma**. Con eso se decide qué comprar la próxima temporada y qué mandar a liquidación cuando ya se pagó sola."},{"id":"s1","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Y si vendes y rentas a la vez, es el mismo inventario: una prenda apartada para renta no aparece disponible para venta ese fin de semana."},{"id":"t4","tipo":"texto","texto":"Funciona igual para vestidos de gala, trajes, XV años y disfraces de temporada. Todo lo que sale y vuelve."},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20ver%20como%20funciona%20la%20renta%20de%20productos","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

commit;
