-- Los 12 pasos que faltaban de «Rezagados · top of mind» (18 → 30).
-- 4 lunes (insight), 4 miércoles (tip), 4 viernes (novedad).
begin;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L7 · Comprar a ciegas', 'Compras el invierno sin saber cómo te fue en verano', 'Cuatro días en Guadalajara para comprometer seis meses de capital.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, hoy el problema estructural del calendario de la moda. 📅"},{"id":"t2","tipo":"texto","texto":"Intermoda de julio es donde se compra el Otoño-Invierno. Cuatro días en Expo Guadalajara."},{"id":"t3","tipo":"texto","texto":"Y en julio, tu Primavera-Verano **todavía no cierra**."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-feria.jpg","alt":"Compradores recorriendo los stands de una feria de moda","pie":"Cuatro días para comprometer seis meses de capital."},{"id":"t4","tipo":"texto","texto":"Así que compras la siguiente temporada con lo que **recuerdas** de la que está corriendo: los estilos que se te vienen a la cabeza, los que te comentó una encargada, los que viste apilados el último sábado."},{"id":"a1","tipo":"aviso","texto":"El sesgo es predecible: te acuerdas de lo que se agotó rápido —porque duele— y de lo que sobra a la vista. **Se te olvida lo que se vendió constante y sin ruido**, que suele ser tu verdadero negocio."},{"id":"s1","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Lo que sí se puede llevar a la feria"},{"id":"l1","tipo":"lista","items":["📊 **Sell-through parcial por estilo**, aunque la temporada no haya cerrado. A mitad de camino ya se sabe quién va bien.","📐 **La curva real por tienda**, no la nacional.","🕳️ **Los huecos**: qué tallas se agotaron pronto y en cuáles nunca hubo."]},{"id":"t5","tipo":"texto","texto":"Con esas tres hojas impresas, cuatro días en la feria son otra cosa."},{"id":"s2","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Agendar una demo","href":"https://www.sacscloud.com/agendar/demo","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Y quien compra en Asia lo tiene peor: la Canton Fair cae a finales de octubre, justo cuando deberías estar preparando el Buen Fin."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L8 · La merma que sale de adentro', 'El 42.6% de la merma en Latinoamérica es robo interno', 'Al revés que en Europa. Y casi nadie lo dice en voz alta.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, tema incómodo pero necesario. 🔒"},{"id":"t2","tipo":"texto","texto":"Cuando falta mercancía, la conversación va casi siempre al mismo lugar: el cliente."},{"id":"t3","tipo":"texto","texto":"Los datos dicen otra cosa."},{"id":"m1","tipo":"metricas","items":[{"cifra":"42.6%","texto":"de la merma en LatAm es robo interno"},{"cifra":"1.68%","texto":"merma sobre ventas en México"},{"cifra":"1.80%","texto":"en tiendas de ropa"}]},{"id":"t4","tipo":"texto","texto":"En Europa y Asia domina el robo del cliente. **En Latinoamérica, no.** Y México registró la tasa de merma más alta del estudio."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-almacen-conteo.jpg","alt":"Dos empleados haciendo conteo físico de inventario","pie":"El conteo no es desconfianza. Es la única forma de saber."},{"id":"a1","tipo":"aviso","texto":"Esto no se resuelve con cámaras ni con sospechas. Se resuelve con **trazabilidad**: que cada movimiento tenga nombre y hora — quién recibió, quién traspasó, quién ajustó, quién dio el descuento. Cuando todo deja rastro, el problema casi siempre se acaba solo."},{"id":"s1","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Los tres puntos ciegos de siempre"},{"id":"l1","tipo":"lista","items":["📦 **La recepción de mercancía.** Si nadie cuenta contra la factura, la diferencia nunca aparece.","🔁 **El traspaso entre tiendas.** Sale de una y no llega a la otra: en el total de la cadena no se nota.","🏷️ **El ajuste manual de inventario.** Si cualquiera puede corregir la existencia sin dejar razón, ahí se esconde todo."]},{"id":"s2","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Agendar una demo","href":"https://www.sacscloud.com/agendar/demo","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. La referencia pública: Liverpool reportó 0.86% de merma sobre ventas de mercancía en 2025. Si tu número está muy arriba de eso, no es mala suerte."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L9 · El dueño es el sistema', 'Si te vas dos semanas, ¿qué se detiene?', 'La pregunta que define si tienes un negocio o un empleo.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, la pregunta de hoy es incómoda y vale la pena. 🧭"},{"id":"t2","tipo":"texto","texto":"**Si te fueras dos semanas sin señal, ¿qué se detiene?**"},{"id":"t3","tipo":"texto","texto":"En casi todas las marcas de moda que crecen, la respuesta es la misma: la compra."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-equipo.jpg","alt":"Encargada y equipo en junta antes de abrir la tienda","pie":"Lo que solo vive en una cabeza no se puede delegar."},{"id":"t4","tipo":"texto","texto":"Nadie más sabe qué pedir, en qué cantidades ni a qué proveedor exigirle. No porque el equipo no pueda: porque **esa información no está escrita en ningún lado**. Vive en tu cabeza."},{"id":"a1","tipo":"aviso","texto":"Y ahí está el techo real del crecimiento. No es el capital ni el local: es que la decisión más importante del negocio depende de una sola persona que no puede enfermarse, ni tomar vacaciones, ni abrir la cuarta tienda."},{"id":"s1","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Lo que cambia cuando se saca de la cabeza"},{"id":"l1","tipo":"lista","items":["📐 **La curva objetivo por categoría** deja de ser criterio y se vuelve regla escrita.","🔢 **El mínimo por talla y tienda** lo puede revisar cualquiera.","📋 **La sugerencia de compra** llega armada y tú apruebas, en vez de construirla desde cero."]},{"id":"t5","tipo":"texto","texto":"No es quitarte la decisión. Es que la decisión llegue hecha para que tú solo digas sí o no."},{"id":"s2","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Agendar una demo","href":"https://www.sacscloud.com/agendar/demo","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. La prueba: pídele a alguien de tu equipo que arme la próxima orden de compra sin ti. Lo que te pregunte es exactamente lo que falta escribir."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L10 · El costo del metro cuadrado', 'Tu renta es el 10% de tu venta. ¿Lo sabías?', 'Y eso define cuánto tiene que vender cada metro de tu piso.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, hoy la cuenta que casi nadie hace y que ordena todas las demás. 📐"},{"id":"t2","tipo":"texto","texto":"En un centro comercial AAA de México, el costo de ocupación de los inquilinos ronda el **10.7% de sus ventas** — renta fija, renta variable y mantenimiento."},{"id":"t3","tipo":"texto","texto":"Dale la vuelta a esa cifra y aparece una vara: **cuánto tiene que vender cada metro cuadrado tuyo para que el local se pague.**"},{"id":"t4","tipo":"texto","texto":"Con una renta de $700 por metro al mes y un costo de ocupación sano del 12%, cada metro debe vender alrededor de **$70,000 al año**."},{"id":"a1","tipo":"aviso","texto":"Ahora la parte útil: no todos tus metros venden igual. La mesa de entrada y la vitrina venden múltiplos de lo que vende el rincón del fondo. Pero **todos cuestan lo mismo por metro** — y casi siempre es el rincón el que tiene la mercancía que menos rota."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-vitrina-noche.jpg","alt":"Visual merchandiser trabajando el aparador al anochecer","pie":"El metro más caro de tu tienda es el que se ve desde la calle."},{"id":"s1","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"El ejercicio que sale de ahí"},{"id":"l1","tipo":"lista","items":["📍 **Divide tu piso en tres zonas**: entrada, centro, fondo.","💰 **Estima qué porcentaje de tu venta sale de cada una.**","📦 **Mira qué mercancía ocupa el fondo.** Si es la de menor rotación, estás pagando renta AAA por guardar."]},{"id":"t5","tipo":"texto","texto":"Un cambio de zona no cuesta nada y se nota en dos semanas."},{"id":"s2","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Agendar una demo","href":"https://www.sacscloud.com/agendar/demo","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Un local chico de 21 a 60 m² en la Ciudad de México paga alrededor de 45% más por metro que un ancla. Si eres pequeño, cada metro te pesa más."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M7 · Cuenta un solo estilo', 'Cuenta un solo estilo. El más caro que tengas.', 'Diez minutos y sabes si tienes un problema de inventario.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, tip de miércoles, de los que sorprenden. 🔍"},{"id":"t2","tipo":"texto","texto":"Elige **el estilo más caro** de tu tienda. Uno solo."},{"id":"t3","tipo":"texto","texto":"Cuéntalo físicamente, talla por talla, color por color. Anótalo en papel."},{"id":"t4","tipo":"texto","texto":"Ahora compáralo con lo que dice tu sistema."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-almacen-conteo.jpg","alt":"Empleados contando inventario con lector y tableta","pie":"Un estilo, diez minutos. Y casi siempre hay diferencia."},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Si no cuadra, está en uno de tres lugares"},{"id":"l1","tipo":"lista","items":["📦 **La recepción.** Llegaron menos de los que dice la factura y nadie lo revisó.","🔁 **El traspaso.** Salió de otra tienda y no se registró la entrada aquí.","🛒 **La venta.** Se cobró como otro producto, casi siempre por prisa en hora pico."]},{"id":"a1","tipo":"aviso","texto":"Con un solo estilo caro no arreglas tu inventario, pero **sabes si tienes un problema y de qué tipo es**. Y eso decide si hace falta un conteo completo o solo apretar un proceso."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📲 Enviar WhatsApp","align":"center","sub":"¿No te cuadró? Escríbenos y lo revisamos contigo","href":"https://wa.me/12058920417?text=Hola,%20conte%20un%20estilo%20y%20no%20me%20cuadra%20con%20el%20sistema"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Hazlo con el más caro a propósito: ahí una sola pieza de diferencia ya es dinero, y es donde más rápido se justifica arreglar el proceso."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M8 · La talla que pidieron', 'Anota una semana las tallas que te pidieron y no tenías', 'Es la lista de compras más honesta que vas a tener.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este tip cuesta cero y da información que ningún reporte tiene. 📝"},{"id":"t2","tipo":"texto","texto":"Durante una semana, cada vez que alguien pida una talla que no hay, tu equipo anota tres cosas: **estilo, talla y si se la llevó de otro color o se fue**."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-probador.jpg","alt":"Clienta saliendo del probador decidiendo entre dos prendas","pie":"La venta que no ocurrió no se registra en ningún lado. Esta libreta es el único lugar donde existe."},{"id":"t3","tipo":"texto","texto":"Al final de la semana vas a tener dos cosas:"},{"id":"l1","tipo":"lista","items":["🛒 **Tu lista de compras real** — no la del histórico, sino la de la demanda que no pudiste atender.","💸 **El costo de tus huecos** — multiplica cada «se fue» por tu ticket promedio."]},{"id":"a1","tipo":"aviso","texto":"Y aquí está lo importante: esa demanda **no aparece en tu sistema de ventas**. Un producto que no se vendió porque no había se registra exactamente igual que uno que nadie quiso. Con los meses, tu histórico te enseña a comprar cada vez menos de lo que más te piden."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Si la misma talla se repite varias veces, ahí está tu decisión de compra de la próxima temporada — con evidencia, no con corazonada."},{"id":"b1","tipo":"boton","texto":"📲 Enviar WhatsApp","align":"center","sub":"Mándanos tu lista y la leemos contigo","href":"https://wa.me/12058920417?text=Hola,%20hice%20la%20lista%20de%20tallas%20que%20me%20pidieron%20y%20no%20tenia"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si tienes más de una tienda, anota también si la talla estaba en otra sucursal. Casi siempre sí — y esa venta se pudo salvar el mismo día."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M9 · Reordena un riel por color', 'Reordena un riel por color y míralo desde la banqueta', 'Diez minutos. El cambio se nota el mismo día.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, tip visual y rápido. Se hace hoy y se nota hoy. 🎨"},{"id":"t2","tipo":"texto","texto":"Elige el riel que más se ve desde la entrada. Reordénalo **por color**, del más claro al más oscuro, en degradado."},{"id":"t3","tipo":"texto","texto":"Ahora sal a la banqueta y mira tu tienda desde afuera."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/moda/moda-rack-color.jpg","alt":"Vendedora acomodando un riel en degradado de color","pie":"El mismo inventario. Otra tienda."},{"id":"t4","tipo":"texto","texto":"Es el mismo inventario. Pero desde la puerta se lee como una colección pensada, no como mercancía apilada."},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Por qué funciona"},{"id":"l1","tipo":"lista","items":["👁️ **El ojo entiende el degradado antes de leer nada.** Da sensación de abundancia y de orden al mismo tiempo.","🕳️ **Los huecos se vuelven invisibles** cuando hay ritmo de color, y evidentes cuando no lo hay.","👗 **La clienta encuentra su color** sin revisar prenda por prenda."]},{"id":"a1","tipo":"aviso","texto":"Y el efecto secundario que casi nadie espera: **tú también vas a ver tu surtido distinto**. Cuando está por color se nota de inmediato si compraste ocho variantes de lo mismo o si te falta toda una familia."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📲 Enviar WhatsApp","align":"center","sub":"Mándanos la foto de cómo quedó","href":"https://wa.me/12058920417?text=Hola,%20reordene%20un%20riel%20por%20color%20y%20quiero%20contarles%20como%20quedo"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si vendes básicos y moda juntos, prueba separarlos antes de ordenar por color. Mezclados se pelean; separados, cada uno se vende mejor."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M10 · Llama a tres', 'Llama a tres clientas que ya no vuelven', 'No para venderles. Para saber por qué.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este tip da miedo y por eso casi nadie lo hace. 📞"},{"id":"t2","tipo":"texto","texto":"Saca tres clientas que compraban seguido y llevan más de seis meses sin volver."},{"id":"t3","tipo":"texto","texto":"Llámales. **No para venderles nada.**"},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-caja.jpg","alt":"Vendedora atendiendo en el mostrador de una boutique","pie":"La respuesta que buscas no está en ningún reporte."},{"id":"t4","tipo":"texto","texto":"La frase es literalmente esta: *«Hola, soy de la tienda. Vi que hace tiempo que no nos visitas y quería preguntarte si pasó algo o simplemente cambió tu ritmo.»*"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Las respuestas que vas a escuchar"},{"id":"l1","tipo":"lista","items":["😐 **«Nada, es que ando corriendo»** — la más común. Significa que no eres prioridad, y eso se arregla con contacto, no con descuento.","📏 **«Ya no encuentro mi talla»** — la que más duele y la que más rápido se arregla.","🎨 **«Ya no es tanto mi estilo»** — tu surtido se movió y ella no. Ojo si se repite.","😶 **Silencio incómodo** — casi siempre hubo un mal servicio que nadie te contó."]},{"id":"a1","tipo":"aviso","texto":"Tres llamadas de cinco minutos te van a dar más claridad sobre tu marca que cualquier reporte de ventas. Y lo mejor: **la mitad de las veces vuelven**, solo porque alguien se acordó de ellas."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📲 Enviar WhatsApp","align":"center","sub":"Cuéntanos qué te dijeron","href":"https://wa.me/12058920417?text=Hola,%20llame%20a%20tres%20clientas%20que%20no%20volvian%20y%20quiero%20contarles"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Hazlas tú, no las delegues. Que llame la dueña cambia por completo cómo se recibe la llamada — y lo que te contestan."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V7 · Video automático con IA', '🎬 Nuevo: tus productos se vuelven video solos', 'La foto del catálogo entra; el video para redes sale.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}! Viernes de novedad, y esta es de las que dan envidia. 🎬"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Video automático con IA"},{"id":"t2","tipo":"texto","texto":"Tu catálogo ya tiene fotos de cada producto. **Ese es todo el insumo.**"},{"id":"t3","tipo":"texto","texto":"Seleccionas los productos, eliges el formato — vertical para reels y TikTok, cuadrado para el feed — y Sacs arma el video: entradas, transiciones, precio en pantalla y el nombre de tu marca."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-viernes.gif","alt":"Animación de fotos de producto convirtiéndose en un video vertical","pie":"De la ficha del producto al reel, sin diseñador."},{"id":"a1","tipo":"aviso","texto":"El cuello de botella de las redes de una boutique nunca es la idea: es **quién se sienta a editar**. Cuando el video sale del mismo catálogo que ya mantienes, publicar deja de depender de que alguien tenga la tarde libre."},{"id":"s1","tipo":"separador"},{"id":"h1b","tipo":"encabezado","nivel":2,"texto":"Lo que se puede armar en un rato"},{"id":"l1","tipo":"lista","items":["🆕 **Lo que llegó esta semana** — se filtra por fecha de recepción y sale solo.","🔥 **Los más vendidos del mes** — el propio reporte elige los productos.","🏷️ **Lo que está en rebaja** — con el precio tachado en pantalla.","👗 **Una colección completa**, en el orden que tú definas."]},{"id":"t4","tipo":"texto","texto":"Y como sale del catálogo, **el precio y las tallas del video son los de verdad**. No el de la lista que alguien pasó a Canva hace tres semanas."},{"id":"s2","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📲 Enviar WhatsApp","align":"center","sub":"¿Quieres verlo con tus propios productos? Escríbenos","href":"https://wa.me/12058920417?text=Hola,%20quiero%20ver%20el%20video%20automatico%20con%20IA"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. El que más se usa es el de «llegó nuevo». Publicar los ingresos el mismo día que entran a piso cambia por completo la primera semana de vida de un estilo."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V8 · Renta de vestidos de gala', '👗 Nuevo: rentar en vez de vender, con el mismo sistema', 'La misma prenda, muchas veces. Y el calendario lo lleva Sacs.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}! Novedad de viernes para quien vende ocasión especial. 👗"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Renta de vestidos y trajes de gala"},{"id":"t2","tipo":"texto","texto":"Un vestido de gala se vende una vez. **Rentado deja dinero seis, ocho, doce veces** — y el problema nunca fue la idea, fue llevar la cuenta."},{"id":"t3","tipo":"texto","texto":"Ahora vive dentro de Sacs, con el mismo catálogo:"},{"id":"l1","tipo":"lista","items":["📅 **Calendario por prenda** — quién la tiene, qué días está apartada y cuándo regresa.","💵 **Depósito en garantía** — se registra al salir y se devuelve al volver, con su movimiento en caja.","🧵 **Estado a la devolución** — si vuelve con un daño, se cobra el ajuste y queda anotado en la ficha.","🔁 **Rotación real** — cuántas veces se ha rentado cada pieza y cuánto lleva recuperado."]},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-taller.jpg","alt":"Modista ajustando un vestido largo sobre maniquí en el taller","pie":"La misma prenda, muchas veces. El taller es parte del negocio."},{"id":"a1","tipo":"aviso","texto":"La métrica que aparece y que nadie tenía: **cuánto lleva generado cada pieza contra lo que costó**. Con eso se decide qué se compra la próxima temporada y qué se saca a venta de liquidación cuando ya se pagó sola."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Y si vendes y rentas al mismo tiempo, es el mismo inventario: una prenda apartada para renta no aparece disponible para venta ese fin de semana."},{"id":"b1","tipo":"boton","texto":"📅 Agendar una demo","href":"https://www.sacscloud.com/agendar/demo","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Funciona igual para trajes de novio, XV años y disfraces de temporada. Todo lo que sale y vuelve."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V9 · De la tela a la etiqueta', '🧵 Nuevo: si mandas maquilar, ahora lo controlas todo', 'Insumos, maquilero, costo real por prenda.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}! Esta es para quien no solo compra: **produce**. 🧵"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Módulo de fabricación"},{"id":"t2","tipo":"texto","texto":"Si mandas maquilar, hoy tu costo por prenda es una estimación. La tela va en una libreta, el avío en otra, lo que le pagaste al taller en el WhatsApp del taller."},{"id":"t3","tipo":"texto","texto":"El módulo cierra ese círculo:"},{"id":"l1","tipo":"lista","items":["🧶 **Insumos con existencia propia** — tela, avíos, etiquetas, bolsas. Se descuentan cuando entran a producción.","🏭 **Órdenes al maquilero** — qué se le entregó, qué debe regresar y cuándo.","📐 **Consumo por talla** — una talla grande lleva más tela, y el costo lo refleja.","🏷️ **Costo real por prenda terminada** — insumos + mano de obra + lo que se mermó."]},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/rezagados/rez-taller.jpg","alt":"Taller de confección con máquinas y prendas en proceso","pie":"El costo de una prenda propia no es lo que te cobró el taller."},{"id":"a1","tipo":"aviso","texto":"El número que cambia decisiones: **el costo real, con merma incluida**. Casi siempre está 12-18% arriba de lo que se traía en la cabeza — y con eso el margen de la marca propia deja de ser un supuesto."},{"id":"s1","tipo":"separador"},{"id":"t5","tipo":"texto","texto":"Y cuando la prenda termina, entra al catálogo como cualquier otra: con sus tallas, sus colores y su costo ya calculado."},{"id":"b1","tipo":"boton","texto":"📅 Agendar una demo","href":"https://www.sacscloud.com/agendar/demo","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. La sorpresa habitual está en los avíos. Nadie los cuenta y suelen ser la diferencia entre un margen sano y uno que no lo era."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V10 · Los reportes que solo existen en moda', '📊 Nuevo: los 10 reportes que un sistema genérico no tiene', 'Curva, sell-through, semanas de cobertura, marcaje.', 'automatizado', 'simple', 'novedades',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}! Cerramos la semana con lo menos vistoso y más útil. 📊"},{"id":"t2","tipo":"texto","texto":"Un sistema genérico te da ventas por producto, por día y por vendedor. Está bien. **Pero ninguna de esas tres preguntas es la que te quita el sueño.**"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Lo que sí preguntas"},{"id":"l1","tipo":"lista","items":["📐 **Curva de tallas real vs. la comprada** — por tienda, no promedio nacional.","📈 **Sell-through por estilo y semana de vida** — el reloj que decide el rebaje.","📦 **Semanas de cobertura** — cuánto te dura lo que tienes al ritmo actual.","🕳️ **Quiebres de talla** — qué estilos ya no tienen su talla central.","🔁 **Traspaso sugerido** — qué mover entre tiendas antes de comprar.","🏷️ **Marcaje y margen después del descuento** — no el de lista.","↩️ **Devoluciones por talla** — dónde tu tabla miente.","🎨 **Ventas por color y por temporada.**","👤 **Recompra por clienta** — quién volvió y en cuánto tiempo.","💤 **Inventario sin movimiento** por días en piso."]},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-nivelacion.jpg","alt":"Pantalla de Sacs mostrando el análisis por tallas y sucursales","pie":"Pantalla real de Sacs. No es una maqueta."},{"id":"a1","tipo":"aviso","texto":"Ninguno de estos se puede armar «con un Excel encima» del sistema, porque **el sistema genérico ni siquiera guarda la talla como un dato**: la guarda como parte del nombre del producto. Ahí se acaba la conversación."},{"id":"s1","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Si algo de esta lista es lo que te está costando trabajo hoy, esa es exactamente la conversación que vale la pena tener."},{"id":"b1","tipo":"boton","texto":"📅 Agendar una demo","href":"https://www.sacscloud.com/agendar/demo","align":"center","sub":"30 minutos, sin costo · eliges el horario y queda confirmada al momento"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. El que más impacta al principio no es la curva: es **semanas de cobertura**. Es el que evita comprar lo que ya tienes."}]'::jsonb, true) on conflict do nothing;

insert into crm_secuencia_pasos (secuencia_id, orden, dia, dia_semana, canal, email_template_id, activo)
select s.id, p.orden, 1, p.dsem, 'correo', t.id, true
from crm_secuencias s
cross join (values
  (115, 1, 'Rezagados L7 · Comprar a ciegas'),
  (116, 1, 'Rezagados L8 · La merma que sale de adentro'),
  (117, 1, 'Rezagados L9 · El dueño es el sistema'),
  (118, 1, 'Rezagados L10 · El costo del metro cuadrado'),
  (119, 3, 'Rezagados M7 · Cuenta un solo estilo'),
  (120, 3, 'Rezagados M8 · La talla que pidieron'),
  (121, 3, 'Rezagados M9 · Reordena un riel por color'),
  (122, 3, 'Rezagados M10 · Llama a tres'),
  (123, 5, 'Rezagados V7 · Video automático con IA'),
  (124, 5, 'Rezagados V8 · Renta de vestidos de gala'),
  (125, 5, 'Rezagados V9 · De la tela a la etiqueta'),
  (126, 5, 'Rezagados V10 · Los reportes que solo existen en moda')
) as p(orden, dsem, plantilla)
join email_templates t on t.nombre = p.plantilla
where s.nombre = 'Rezagados · top of mind'
  and not exists (select 1 from crm_secuencia_pasos x where x.secuencia_id = s.id and x.email_template_id = t.id);

commit;
