-- «Crecimiento · lo que sigue»: los siete correos.
--
-- EL TONO ES LA DECISIÓN. No dicen «te falta»: dicen «ya dominaste esto». El
-- cliente que recibe esto opera bien —vende, corta caja, mueve inventario— y
-- tratarlo como si le faltara algo insulta el trabajo que sí hizo. Lo que
-- sigue no es aprender el sistema, es qué más se puede quitar de encima.
--
-- SIN PRECIOS, a propósito. Se dice que son EXTENSIONES del plan y que lo que
-- implica cada una se ve por WhatsApp, sobre su caso y su número de sucursales.
-- Decirlo desde el primer correo evita el reclamo de después: si no se aclara,
-- el cliente asume que viene incluido.
--
-- LAS DOS OPCIONES, siempre juntas y en el mismo orden: agendar 45 minutos o
-- escribir por WhatsApp. Quien prefiere hablar agenda; quien prefiere escribir,
-- escribe. Obligar a una sola pierde a la mitad — y de una cadencia de
-- expansión, la mitad que se pierde es la que ya te iba a comprar.
begin;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 1 · Lo estás usando bien', '{{empresa|Tu marca}}: lo estás usando bien, y hay más', 'Esto no es un correo de «te falta». Es de «ya dominaste esto».', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este correo no es para venderte nada hoy."},{"id":"t2","tipo":"texto","texto":"Es para decirte algo que desde aquí se ve y desde adentro no: **estás usando Sacs bien**. Vendes, cortas caja, mueves inventario. Muchos clientes se quedan a la mitad de eso."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Y justamente por eso te escribo. Cuando alguien ya domina la operación del día a día, lo que sigue deja de ser «aprender el sistema» y pasa a ser otra cosa: **qué más se puede quitar de encima**."},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Lo que vamos a enseñarte estas semanas"},{"id":"l1","tipo":"lista","items":["🤖 **Axo**, el asistente con IA que hace el trabajo en vez de explicarte cómo hacerlo.","👥 **Empleados**, para asistencias, contratos, actas y clima laboral.","🏦 **Administración**, con gastos, cuentas por cobrar y por pagar.","📦 **Nivelación**, que te avisa qué mover entre sucursales y qué comprar.","🧩 **Personalizaciones**, para automatizar un proceso tuyo que hoy es a mano."]},{"id":"a1","tipo":"aviso","texto":"Uno por correo, cada dos semanas. Son **extensiones** de tu plan actual — no vienen incluidas, y no las vas a encontrar con un precio de lista: **cada una se ve contigo por WhatsApp**, según lo que necesites y cuántas sucursales tengas. Si alguna te interesa, no esperes al último."},{"id":"s1","tipo":"separador"},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20ver%20que%20mas%20puede%20hacer%20Sacs%20por%20mi%20operacion","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si ninguno te mueve, también está bien. Contéstame «ya estoy bien así» y dejo de mandarlos."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 2 · Axo hace el trabajo, no te lo explica', 'El asistente que ejecuta, no el que te dice dónde está el botón', 'Le pides una nivelación y la corre. Le pides configurar algo y lo configura.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, empecemos por el que más sorprende. 🤖"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Axo no es un chat de ayuda"},{"id":"t2","tipo":"texto","texto":"La diferencia es toda. Un asistente normal te dice: *«ve a Inventarios, luego a Nivelación, luego a Configuración…»*. Axo **te lleva a la pantalla** — y si se lo pides, lo hace él."},{"id":"l1","tipo":"lista","items":["⚙️ **Configura la nivelación por chat**: días de cobertura, ventana de análisis, tiempo de traslado.","🚀 **Lanza una corrida** y regenera el cubo de demanda.","🚫 **Excluye un producto de una tienda** sin que abras nada.","🧭 Y al terminar **te lleva a ver el resultado**, no te deja adivinando."]},{"id":"a1","tipo":"aviso","texto":"Con los **mismos permisos** que exige la pantalla: quien no puede correr una nivelación tampoco puede pedírsela al asistente. Y siempre con el botón de confirmar antes de tocar nada."},{"id":"s1","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Lo que se ahorra no es tiempo de clics. Es el tiempo de acordarse de dónde estaba cada cosa."},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20ver%20Axo%20funcionando%20en%20mi%20cuenta","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Sirve para quien no es el dueño. Una encargada puede pedirle cosas que no sabría configurar sola."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 3 · Tus colaboradores, en un lugar', 'Asistencias, contratos y actas dejan de vivir en un cuaderno', 'El módulo de Empleados: todo el control de tu equipo dentro de Sacs.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, hoy el que casi nadie pide y todos necesitan. 👥"},{"id":"t2","tipo":"texto","texto":"La operación de una tienda se lleva en el sistema. **La de su gente, casi siempre en un cuaderno** — o en la cabeza de quien administra."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Lo que entra al módulo"},{"id":"l1","tipo":"lista","items":["🕘 **Asistencias**: entradas, salidas, retardos y faltas, con su reporte.","📄 **Contratos** y sus vencimientos, sin buscar en una carpeta.","⚠️ **Actas administrativas**, escritas y firmadas donde quedan guardadas.","🌡️ **Clima laboral**, para saber cómo está tu equipo antes de que renuncie.","📁 **El expediente completo** de cada quien, en una sola pantalla."]},{"id":"a1","tipo":"aviso","texto":"La diferencia se nota el día que la necesitas: cuando hay que sostener una decisión con alguien, tener el acta y las asistencias a la mano **cambia por completo esa conversación**."},{"id":"s1","tipo":"separador"},{"id":"t2b","tipo":"texto","texto":"Y para el dueño hay algo más: dejar de ser el único que sabe quién llegó tarde el mes pasado."},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20ver%20el%20modulo%20de%20Empleados","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 4 · A dónde se fue el dinero', 'Gastos, cuentas por cobrar y por pagar, dentro de Sacs', 'Ya sabes cuánto vendiste. La otra mitad también se puede ver.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este es de los que más rápido se pagan solos. 🏦"},{"id":"t2","tipo":"texto","texto":"Sacs ya te dice **cuánto vendiste**. Lo que casi siempre vive aparte —en Excel, en el banco, en la cabeza del contador— es la otra mitad: a dónde se fue."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Administración"},{"id":"l1","tipo":"lista","items":["💸 **Gastos** por categoría y por sucursal, con sus comprobantes.","📥 **Cuentas por cobrar**: quién te debe, desde cuándo y cuánto.","📤 **Cuentas por pagar**: a quién le debes y qué vence esta semana.","🏛️ **Cuentas de efectivo y bancos**, con la conciliación contra tus movimientos reales."]},{"id":"a1","tipo":"aviso","texto":"Cuando venta y gasto viven en el mismo lugar, la pregunta «¿este mes ganamos?» deja de contestarse con una corazonada a fin de mes."},{"id":"s1","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Y si ya usas una parte —muchos llevan gastos y nada más— vale la pena ver lo demás: casi siempre es lo que le falta al reporte que ya revisas."},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20ver%20el%20modulo%20de%20Administracion","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 5 · Que el sistema te diga qué mover', 'Deja de decidir qué transferir y qué comprar a ojo', 'El dashboard de nivelación, con tus reglas.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este es el que cambia cómo se compra. 📦"},{"id":"t2","tipo":"texto","texto":"Hoy alguien decide qué mandar a cada sucursal y qué pedirle al proveedor. Lo decide bien —lleva años haciéndolo— pero lo decide **a ojo, y una cabeza a la vez**."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Nivelación"},{"id":"t3","tipo":"texto","texto":"El sistema mira lo que tienes, lo que se está vendiendo en cada punto y las reglas que tú definas. Y te dice, producto por producto:"},{"id":"l1","tipo":"lista","items":["🔁 **Qué transferir entre sucursales** — la talla que sobra allá y falta acá.","🏭 **Qué mandar desde el CEDIS** y en qué orden de prioridad.","🛒 **Qué comprar de verdad**, después de haber movido lo que ya pagaste."]},{"id":"a1","tipo":"aviso","texto":"Ese último punto es el que más dinero libera: **antes de comprar, acomodar**. Casi siempre una parte de lo que ibas a pedir ya está en tu propia bodega, en la tienda equivocada."},{"id":"i1","tipo":"imagen","src":"https://www.sacscloud.com/email/trial/trial-nivelacion.jpg","alt":"Pantalla de nivelación de Sacs con el análisis por sucursal","pie":"Pantalla real. Las reglas las pones tú."},{"id":"s1","tipo":"separador"},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20ver%20el%20dashboard%20de%20nivelacion","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Funciona con las reglas de tu negocio, no con un promedio de la industria. Si tu tienda del centro vende distinto, la nivelación lo respeta."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 6 · Si tu proceso es distinto, se programa', 'Ese paso que haces a mano se puede automatizar', 'Personalizaciones: cualquier flujo de tu negocio, dentro de Sacs.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, el último de la lista, y el menos conocido. 🧩"},{"id":"t2","tipo":"texto","texto":"Todo sistema obliga a acomodarse un poco. Pero hay cosas que **no deberían acomodarse**: la forma particular en que tu negocio hace algo, y que es justo lo que te distingue."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Qué se puede personalizar"},{"id":"t3","tipo":"texto","texto":"Prácticamente cualquier flujo. Algunos que ya corren en cuentas reales:"},{"id":"l1","tipo":"lista","items":["🔗 **Un paso de autorización** antes de que algo avance.","📨 **Un aviso automático** a quien tiene que enterarse, por correo o WhatsApp.","📑 **Un documento propio** que hoy se llena a mano cada vez.","🔄 **Una conexión** con un sistema que ya usas y no quieres dejar."]},{"id":"a1","tipo":"aviso","texto":"La pregunta útil no es «¿Sacs lo hace?» sino **«¿esto que hago cada semana a mano, se puede automatizar?»**. Casi siempre sí — y lo que implica se ve contigo, sobre tu proceso."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Si hay algo así en tu operación, cuéntamelo. Aunque sea para decirte que no vale la pena."},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20tengo%20un%20proceso%20que%20hago%20a%20mano%20y%20quiero%20saber%20si%20se%20puede%20automatizar","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Crecimiento 7 · ¿Alguno te movió?', 'Cinco cosas en seis semanas. ¿Alguna te sirvió?', 'Y si ninguna, dímelo y dejo de mandarlas.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, te mandé cinco cosas en las últimas semanas:"},{"id":"l1","tipo":"lista","items":["🤖 **Axo** — el asistente que ejecuta.","👥 **Empleados** — asistencias, contratos, actas, clima.","🏦 **Administración** — gastos, cobrar y pagar, bancos.","📦 **Nivelación** — qué mover y qué comprar.","🧩 **Personalizaciones** — automatizar un proceso tuyo."]},{"id":"t2","tipo":"texto","texto":"No espero que te interesen todas. Con que **una** te haya hecho pensar «esto sí me serviría», este correo valió la pena."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Y si es así, la sesión es de 45 minutos: te enseño esa —solo esa— con tu propia cuenta abierta, y te digo con franqueza si te conviene o no. **Todas son extensiones de tu plan**, así que lo que implica cada una lo vemos ahí mismo, sobre tu caso."},{"id":"a1","tipo":"aviso","texto":"**Si ninguna te movió, contéstame «ya estoy bien así»** y dejo de mandarte esta serie. Prefiero eso a seguir ocupándote la bandeja."},{"id":"s1","tipo":"separador"},{"id":"b1a","tipo":"boton","texto":"📅 Agendar 45 minutos","href":"https://www.sacscloud.com/agendar/crecimiento","align":"center","sub":"45 minutos · sin costo · con alguien que conoce tu cuenta"},{"id":"b1b","tipo":"boton","texto":"💬 O escríbenos por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20me%20intereso%20una%20de%20las%20cosas%20que%20me%20mandaste","align":"center","sub":"Si prefieres preguntar sin agendar nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Y si algo de lo que ya tienes no te está funcionando como esperabas, también quiero saberlo. Eso pesa más que cualquier módulo nuevo."}]'::jsonb, true) on conflict do nothing;

commit;
