-- 13-sep-2026 · El botón de WhatsApp de los avisos in-app abre el chat CON el mensaje escrito.
-- Antes abría un chat en blanco: el cliente tenía que explicar de cero de qué aviso venía, y
-- de este lado llegaba un «hola» sin contexto. Ahora cada aviso trae su propia frase.

update inapp_campanas set contenido = '{"titulo": "Ya sabes cuánto vendiste. ¿Y cuánto gastaste?", "botones": [{"texto": "Ver cómo funciona", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Preguntar", "accion": "whatsapp_ventas", "destino": "Hola, vi lo de gastos y cuentas por cobrar en Sacs. ¿Cómo lo activo?"}], "mensaje": "Gastos, cuentas por cobrar y por pagar, y la conciliación con tus bancos — en el mismo lugar donde ya vive la venta. «¿Este mes ganamos?» deja de contestarse con una corazonada."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · a dónde se fue el dinero';
update inapp_campanas set contenido = '{"titulo": "Tus prendas, puestas en un modelo", "botones": [{"texto": "Que me lo enseñen", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Mandar una foto", "accion": "whatsapp_ventas", "destino": "Hola, vi lo del catálogo con IA y el probador virtual. Les mando una foto de una prenda para ver cómo queda."}], "mensaje": "Sin sesión de fotos: la foto que ya tienes sale puesta en una persona. Y tu clienta puede ver cómo se le vería a ella con el probador virtual, con lo que sí hay en su talla."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · catálogo con IA';
update inapp_campanas set contenido = '{"titulo": "Axo puede hacerlo por ti", "botones": [{"texto": "Que me lo enseñen", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Preguntar", "accion": "whatsapp_ventas", "destino": "Hola, vi lo del asistente Axo en Sacs. ¿Cómo funciona?"}], "mensaje": "No te explica dónde está el botón: te lleva a la pantalla, y si se lo pides, lo configura él. Con los mismos permisos que ya tienes."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · el asistente que ejecuta';
update inapp_campanas set contenido = '{"titulo": "Hay un escalón más arriba del tuyo", "botones": [{"texto": "Ver qué trae", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Preguntar", "accion": "whatsapp_ventas", "destino": "Hola, vi el aviso del plan que sigue. ¿Qué trae y cuánto sería en mi caso?"}], "mensaje": "Subir de plan no es empezar de nuevo: conservas tu catálogo, tus clientes y tu histórico — lo que cambia es qué puedes hacer con ellos. Te decimos qué trae el que sigue en tu caso, y si te conviene o no."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · el plan que sigue';
update inapp_campanas set contenido = '{"titulo": "Lo estás usando bien. Hay más.", "botones": [{"texto": "Agendar 45 minutos", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Preguntar por WhatsApp", "accion": "whatsapp_ventas", "destino": "Hola, vi el aviso en Sacs sobre lo que más puede hacer el sistema. ¿Me cuentan?"}], "mensaje": "Te vamos a ir mostrando lo que Sacs también puede hacer por tu operación: automatizar con IA, llevar a tus colaboradores, administrar gastos y cobranza, o decirte qué mover entre sucursales. Son extensiones de tu plan — lo que implica cada una lo vemos contigo."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · qué más puede hacer Sacs';
update inapp_campanas set contenido = '{"titulo": "Antes de comprar, acomodar", "botones": [{"texto": "Ver cómo funciona", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Preguntar", "accion": "whatsapp_ventas", "destino": "Hola, vi lo de la nivelación entre sucursales en Sacs. ¿Me enseñan cómo funciona?"}], "mensaje": "La nivelación te dice qué transferir entre tus sucursales y qué pedirle al proveedor de verdad — después de haber movido lo que ya pagaste."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · qué mover y qué comprar';
update inapp_campanas set contenido = '{"titulo": "La misma prenda, cobrada muchas veces", "botones": [{"texto": "Ver cómo funciona", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Preguntar", "accion": "whatsapp_ventas", "destino": "Hola, vi lo de rentar prendas con Sacs. ¿Cómo funciona?"}], "mensaje": "Calendario por pieza, depósito en garantía, estado a la devolución y cuánto lleva generado cada prenda contra lo que costó. Con el mismo inventario que ya tienes."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · rentar en vez de vender';
update inapp_campanas set contenido = '{"titulo": "Tu equipo también cabe en Sacs", "botones": [{"texto": "Que me lo enseñen", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Preguntar", "accion": "whatsapp_ventas", "destino": "Hola, vi lo de llevar a mis colaboradores en Sacs (asistencias, contratos). ¿Me explican?"}], "mensaje": "Asistencias, contratos, actas administrativas y clima laboral, en el expediente de cada quien. El día que hay que sostener una decisión con alguien, tenerlo a la mano cambia esa conversación."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · tus colaboradores';
update inapp_campanas set contenido = '{"titulo": "¿Qué haces a mano cada semana?", "botones": [{"texto": "Contarlo en una sesión", "accion": "url_sacs", "destino": "https://www.sacscloud.com/agendar/crecimiento"}, {"texto": "Contarlo por WhatsApp", "accion": "whatsapp_ventas", "destino": "Hola, tengo un proceso que hago a mano cada semana y vi que se puede automatizar en Sacs. Se los cuento:"}], "mensaje": "Casi cualquier flujo de tu negocio se puede automatizar dentro de Sacs: una autorización, un aviso, un documento que hoy se llena a mano. Cuéntanos cuál es el tuyo."}'::jsonb, updated_at = now() where nombre = 'Crecimiento · un proceso tuyo, automatizado';
