-- Pasos 4 a 17 de «Rezagados · top of mind» (los 3 primeros van en
-- migration-2026-08-rezagados-primeros-pasos.sql; los 12 últimos en
-- migration-2026-08-rezagados-completar-30.sql).
--
-- 5 lunes de insight con gráfica, 5 miércoles de tip, 4 viernes de novedad.
begin;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L2 · El denominador', 'La cuenta que casi todos hacen mal', 'Tu sell-through da 90% y no significa lo que crees.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, hoy una cuenta de una sola línea que cambia todas las demás. 🧮"}, {"id": "t2", "tipo": "texto", "texto": "El **sell-through** es la métrica que manda en moda: qué porcentaje de lo que trajiste ya se vendió."}, {"id": "t3", "tipo": "texto", "texto": "Y casi todo el mundo la calcula mal."}, {"id": "i1", "alt": "Comparación de las dos formas de calcular el sell-through", "pie": "El mismo estilo. Dos denominadores. Dos decisiones opuestas.", "src": "https://www.sacscloud.com/email/rezagados/rez-g-sellthrough.png", "tipo": "imagen"}, {"id": "t4", "tipo": "texto", "texto": "Si divides lo vendido entre **lo que te queda hoy**, te va a dar altísimo — y mientras más vendas, más alto. Es una métrica que se felicita sola."}, {"id": "t5", "tipo": "texto", "texto": "La buena divide entre **lo que recibiste**. Ese número te dice si la compra estuvo bien hecha, que es la única pregunta que importa."}, {"id": "a1", "tipo": "aviso", "texto": "La referencia del ramo: **arriba de 70% al año es sano**. Debajo de 50% antes de rebajas, hay que intervenir ya. Con el denominador equivocado nunca vas a saber en cuál de los dos estás."}, {"id": "s1", "tipo": "separador"}, {"id": "t6", "tipo": "texto", "texto": "Si quieres que lo veamos con tus estilos de la temporada pasada, agenda media hora. Sacamos el número bien calculado y de ahí sale la conversación sola."}, {"id": "b1", "sub": "30 minutos, sin costo · eliges el horario y queda confirmada al momento", "href": "https://www.sacscloud.com/agendar/demo", "tipo": "boton", "align": "center", "texto": "📅 Agendar una demo"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Pruébalo hoy con un estilo que sientas exitoso. Si el número cae mucho al cambiar el denominador, es que compraste de más — no que vendiste poco."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L3 · Semanas de cobertura', 'La pregunta que responde qué comprar y qué rematar', 'Un solo número por estilo, y las dos decisiones salen solas.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, hay una métrica que casi no se usa en moda mexicana y que resuelve dos decisiones a la vez. ⏳"}, {"id": "t2", "tipo": "texto", "texto": "Se llama **semanas de cobertura**: cuántas semanas te dura lo que tienes al ritmo al que se está vendiendo."}, {"id": "t3", "tipo": "texto", "texto": "La cuenta es tonta de simple: existencia ÷ venta semanal."}, {"id": "i1", "alt": "Tres estilos con distintas semanas de cobertura", "pie": "El mismo inventario. Tres historias completamente distintas.", "src": "https://www.sacscloud.com/email/rezagados/rez-g-cobertura.png", "tipo": "imagen"}, {"id": "t4", "tipo": "texto", "texto": "Y lo que la hace útil es que **las dos decisiones caen del mismo número**:"}, {"id": "l1", "tipo": "lista", "items": ["🔴 **Menos de 4 semanas** — se te va a acabar antes de que llegue la reposición. Es lo que hay que pedir ya.", "🟢 **Entre 8 y 16** — sano. Ni te sobra ni te falta.", "🟠 **Más de 20** — capital dormido. Ese es el que hay que empezar a mover, no el que menos te gusta."]}, {"id": "a1", "tipo": "aviso", "texto": "El cambio de mentalidad: dejas de decidir por lo que te gusta o por lo que te sobra a la vista, y empiezas a decidir por **cuánto tiempo te dura**. Es la misma información que ya tienes, leída al derecho."}, {"id": "s1", "tipo": "separador"}, {"id": "t5", "tipo": "texto", "texto": "¿Lo sacamos con tus estilos? En media hora salen los tres grupos y sabes exactamente qué pedir y qué mover."}, {"id": "b1", "sub": "30 minutos, sin costo · eliges el horario y queda confirmada al momento", "href": "https://www.sacscloud.com/agendar/demo", "tipo": "boton", "align": "center", "texto": "📅 Agendar una demo"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Si tienes varias tiendas, hazlo por tienda. El mismo estilo puede estar en rojo en una y en naranja en otra — y ahí no se compra: se traspasa."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L4 · Rebajar tarde', 'Cada semana que esperas te baja un escalón', 'La prenda no cambia. El precio al que la vendes, sí.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, una de las decisiones más caras del año se toma por no tomarla. 📉"}, {"id": "t2", "tipo": "texto", "texto": "Rebajar duele. Se siente como aceptar que te equivocaste en la compra, así que se pospone: *«a ver si sale la semana que entra»*."}, {"id": "t3", "tipo": "texto", "texto": "Pero el mercado no espera."}, {"id": "i1", "alt": "Escalera de precios: de precio lleno a saldo", "pie": "Cinco escalones. Cada semana de indecisión te baja uno.", "src": "https://www.sacscloud.com/email/rezagados/rez-g-rebajas.png", "tipo": "imagen"}, {"id": "t4", "tipo": "texto", "texto": "La prenda que hoy sale con 20% de descuento, en cuatro semanas ya solo sale con 40%. Y en ocho, es saldo."}, {"id": "t5", "tipo": "texto", "texto": "**No perdiste margen al rebajar. Lo perdiste al esperar.**"}, {"id": "a1", "tipo": "aviso", "texto": "Lo que hacen las marcas que manejan bien esto: no rebajan por calendario ni por corazonada, sino por **cobertura**. Si un estilo trae más de 20 semanas a mitad de temporada, se marca — aunque duela, aunque haya gustado."}, {"id": "s1", "tipo": "separador"}, {"id": "t6", "tipo": "texto", "texto": "Si quieres armar tu regla de rebaja —cuándo, cuánto y sobre qué— agenda media hora y la dejamos escrita."}, {"id": "b1", "sub": "30 minutos, sin costo · eliges el horario y queda confirmada al momento", "href": "https://www.sacscloud.com/agendar/demo", "tipo": "boton", "align": "center", "texto": "📅 Agendar una demo"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. La prueba de que esperar sale caro: mira una prenda que hoy esté en remate y calcula cuánto habrías ganado vendiéndola con 20% hace dos meses. Casi siempre es más que el total que dejará ahora."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L5 · Margen sobre costo', 'Multiplicar por dos no es 100% de margen', 'Es 50%. Y si presupuestas con el otro número, te falta la mitad.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, hoy la confusión más cara del sector, y la más fácil de arreglar. 💰"}, {"id": "t2", "tipo": "texto", "texto": "Compras una prenda en $500 y la vendes en $1,000."}, {"id": "t3", "tipo": "texto", "texto": "¿Cuánto ganaste?"}, {"id": "i1", "alt": "Comparación entre margen sobre costo y margen sobre venta", "pie": "La misma operación. Dos números que no significan lo mismo.", "src": "https://www.sacscloud.com/email/rezagados/rez-g-margen.png", "tipo": "imagen"}, {"id": "t4", "tipo": "texto", "texto": "La mayoría dice **100%**, porque duplicaste el costo. Y es cierto que el markup es del 100%."}, {"id": "t5", "tipo": "texto", "texto": "Pero tu **margen** es 50%: de cada peso que entra a la caja, cincuenta centavos son tuyos y cincuenta ya eran del proveedor."}, {"id": "a1", "tipo": "aviso", "texto": "¿Por qué importa? Porque la renta, la nómina y la luz se pagan con el margen, no con el markup. Si presupuestas tu año pensando que ganas el 100%, **te va a faltar exactamente la mitad** — y no vas a entender por qué."}, {"id": "s1", "tipo": "separador"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "La regla de bolsillo"}, {"id": "t6", "tipo": "texto", "texto": "Markup del 100% → margen del 50%. Markup del 150% → margen del 60%. Markup del 233% → margen del 70%."}, {"id": "t7", "tipo": "texto", "texto": "Si alguien te dice que trabaja «al 200 de margen», casi siempre quiere decir markup. Vale la pena preguntar."}, {"id": "s2", "tipo": "separador"}, {"id": "b1", "sub": "¿Dudas con tus números? Mándanos un mensaje", "href": "https://wa.me/12058920417?text=Hola,%20quiero%20revisar%20como%20estoy%20calculando%20mi%20margen", "tipo": "boton", "align": "center", "texto": "📲 Enviar WhatsApp"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Este error se multiplica por cada estilo y por cada temporada. Es de las pocas cosas que se arreglan en una tarde y se notan todo el año."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados L6 · El 35% que se devuelve', 'De cada 10 prendas que vendes en línea, 3.5 regresan', 'Y un tercio de esas es por la talla.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, si vendes en línea, este es el número que casi nadie te dice. 📦"}, {"id": "i1", "alt": "Diez prendas, tres y media devueltas", "pie": "Moda es la categoría con más devoluciones de México.", "src": "https://www.sacscloud.com/email/rezagados/rez-g-devoluciones.png", "tipo": "imagen"}, {"id": "t2", "tipo": "texto", "texto": "**El 35% de lo que se vende de moda en línea en México se devuelve.** Es la tasa más alta de todas las categorías — muy por encima de electrónicos, que anda en 12%."}, {"id": "t3", "tipo": "texto", "texto": "Y la causa número uno no es el color, ni el envío, ni que no gustó."}, {"id": "t4", "tipo": "texto", "texto": "**Es la talla.** Un tercio de todas las devoluciones."}, {"id": "s1", "tipo": "separador"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Por qué pasa, de verdad"}, {"id": "l1", "tipo": "lista", "items": ["📏 **Cada marca talla distinto** y el cliente lo sabe. Ante la duda, pide dos y regresa una — eso ya está contemplado en su compra.", "🇲🇽 **La tabla equivocada.** En México los jeans se venden en nones —3, 5, 7, 9— y muchas tiendas en línea muestran la tabla estadounidense en pares.", "🕳️ **La talla que no estaba.** Compra la que sí había, no la suya."]}, {"id": "a1", "tipo": "aviso", "texto": "Lo que separa a las marcas que lo resuelven: dejan de pelear contra la devolución y montan **cambio** en su lugar. La pieza no se pierde, la venta no se cae, y el cliente vuelve. Pero para eso hay que saber qué talla hay y en qué tienda — que es justo lo que casi nadie tiene a la mano."}, {"id": "s2", "tipo": "separador"}, {"id": "t5", "tipo": "texto", "texto": "Si quieres ver cuánto te está costando y qué se puede hacer, agenda media hora."}, {"id": "b1", "sub": "30 minutos, sin costo · eliges el horario y queda confirmada al momento", "href": "https://www.sacscloud.com/agendar/demo", "tipo": "boton", "align": "center", "texto": "📅 Agendar una demo"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Un ejercicio incómodo: cuenta cuántas devoluciones tuviste el mes pasado y multiplica por el costo del envío ida y vuelta. Ese número no aparece en ningún reporte de ventas."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M2 · Los tres montones', 'Parte tu inventario en tres montones', 'Veinte minutos y sabes qué pedir, qué mover y qué rematar.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, tip de miércoles. Este se hace con una hoja de cálculo y café. ☕"}, {"id": "t2", "tipo": "texto", "texto": "Saca la lista de tus estilos con dos columnas: **cuántas piezas tienes** y **cuántas vendiste la semana pasada**."}, {"id": "t3", "tipo": "texto", "texto": "Divide la primera entre la segunda. Ese número son las semanas que te dura."}, {"id": "i1", "alt": "Dos empleados haciendo conteo físico en el almacén de una tienda de moda", "pie": "Veinte minutos de conteo valen más que un mes de intuición.", "src": "https://www.sacscloud.com/email/rezagados/rez-almacen-conteo.jpg", "tipo": "imagen"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Ahora los tres montones"}, {"id": "l1", "tipo": "lista", "items": ["🔴 **Menos de 4 semanas** → PEDIR. Se te acaba antes de que llegue la reposición.", "🟢 **Entre 4 y 20** → DEJAR EN PAZ. Está haciendo su trabajo.", "🟠 **Más de 20 semanas** → MOVER. Ese es capital dormido, no un estilo que «todavía puede salir»."]}, {"id": "t4", "tipo": "texto", "texto": "Con esos tres montones ya tienes tu orden de compra y tu lista de rebajas. En veinte minutos."}, {"id": "a1", "tipo": "aviso", "texto": "El montón naranja es el que duele, y por eso casi nadie lo hace. Es el que compraste con ilusión. Pero cada semana que se queda ahí te cuesta el espacio y el dinero de lo que sí rota."}, {"id": "s1", "tipo": "separador"}, {"id": "b1", "sub": "Mándanos lo que te salió y lo revisamos", "href": "https://wa.me/12058920417?text=Hola,%20hice%20los%20tres%20montones%20y%20quiero%20platicar%20lo%20que%20salio", "tipo": "boton", "align": "center", "texto": "📲 Enviar WhatsApp"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Si tienes más de una tienda, hazlo por tienda. Un estilo puede estar rojo en una y naranja en otra: ahí no se compra, se traspasa."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M3 · Los cinco de siempre', 'Los cinco clientes que sostienen tu tienda', 'Sácalos hoy. Vas a reconocer los nombres.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, este tip toma diez minutos y cambia cómo ves tu base. 👥"}, {"id": "t2", "tipo": "texto", "texto": "Saca a tus **veinte clientes que más han comprado** en los últimos doce meses. Solo el nombre y el total."}, {"id": "t3", "tipo": "texto", "texto": "Ahora suma cuánto pesan esos veinte sobre tu venta del año."}, {"id": "i1", "alt": "Momento de cobro en una boutique: una vendedora dobla una prenda en una bolsa de papel", "pie": "La clienta que vuelve cuesta una fracción de la que llega por primera vez.", "src": "https://www.sacscloud.com/email/rezagados/rez-caja.jpg", "tipo": "imagen"}, {"id": "t4", "tipo": "texto", "texto": "En casi todas las marcas de moda ese número está entre el **15 y el 30 por ciento**. Veinte personas."}, {"id": "s1", "tipo": "separador"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Y ahora la pregunta incómoda"}, {"id": "t5", "tipo": "texto", "texto": "¿Cuándo fue la última vez que alguien les escribió por algo que no fuera una promoción masiva?"}, {"id": "t6", "tipo": "texto", "texto": "No hablo de campañas. Hablo de: *«llegó algo que te va a gustar, te lo aparto»*."}, {"id": "a1", "tipo": "aviso", "texto": "Ahí está la oportunidad más barata que tiene una marca de moda: no cuesta pauta, no cuesta descuento, y la clienta ya te conoce. Solo hace falta **saber quiénes son y qué compraron**."}, {"id": "s2", "tipo": "separador"}, {"id": "t7", "tipo": "texto", "texto": "Si quieres que veamos cómo tener esa lista siempre a la mano y usarla sin que se sienta spam, agenda media hora."}, {"id": "b1", "sub": "30 minutos, sin costo · eliges el horario y queda confirmada al momento", "href": "https://www.sacscloud.com/agendar/demo", "tipo": "boton", "align": "center", "texto": "📅 Agendar una demo"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. El ejercicio completo es sacar los veinte y ponerles al lado la fecha de su última compra. Si hay alguien de tus mejores clientes con seis meses sin volver, esa es tu llamada de mañana."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M4 · La foto de tu vitrina', 'Tómale una foto a tu vitrina y míralas juntas', 'Ocho semanas de fotos te dicen algo que estando adentro no ves.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, tip de esta semana, y es de los que se disfrutan. 📸"}, {"id": "t2", "tipo": "texto", "texto": "Todos los lunes, antes de abrir, tómale una foto a tu vitrina desde la banqueta. Siempre desde el mismo lugar."}, {"id": "i1", "alt": "Un visual merchandiser ajustando el vestido de un maniquí dentro del aparador al anochecer", "pie": "Desde adentro se ve el trabajo. Desde la banqueta se ve lo que ve tu clienta.", "src": "https://www.sacscloud.com/email/rezagados/rez-vitrina-noche.jpg", "tipo": "imagen"}, {"id": "t3", "tipo": "texto", "texto": "Al cabo de ocho semanas ponlas juntas en el teléfono y míralas en fila."}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Lo que vas a ver"}, {"id": "l1", "tipo": "lista", "items": ["🎨 **Si tu vitrina cambia de verdad** o solo se mueven las mismas piezas de lugar.", "⏱️ **Cuánto tiempo lleva ahí la misma prenda.** Casi siempre es más del que crees.", "🌈 **Si tu marca tiene un color** o cambia de personalidad cada mes.", "👗 **Si lo que está en la vitrina es lo que quieres vender** o lo que sobró."]}, {"id": "a1", "tipo": "aviso", "texto": "El sesgo que rompe: cuando estás adentro todos los días, la vitrina te parece nueva porque tú la moviste. La secuencia de fotos no tiene memoria ni cariño, y por eso te enseña lo que tu clienta ve al pasar por décima vez."}, {"id": "s1", "tipo": "separador"}, {"id": "t4", "tipo": "texto", "texto": "Y el cruce que lo vuelve serio: la prenda que lleva cinco semanas en la vitrina, ¿cuántas vendió en ese tiempo? Si la respuesta es «casi ninguna», tu mejor metro cuadrado está ocupado."}, {"id": "b1", "sub": "Cuéntanos qué encontraste", "href": "https://wa.me/12058920417?text=Hola,%20quiero%20platicar%20sobre%20lo%20que%20veo%20en%20mi%20vitrina", "tipo": "boton", "align": "center", "texto": "📲 Enviar WhatsApp"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Hazlo también con la mesa de entrada. Es el segundo espacio que más vende y el que menos se revisa."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M5 · El recorrido de cinco minutos', 'Camina tu tienda como si fueras tu clienta', 'Cinco minutos, y vas a encontrar tres cosas.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, tip corto y físico. Se hace hoy mismo. 🚶‍♀️"}, {"id": "t2", "tipo": "texto", "texto": "Sal de tu tienda, cuenta hasta diez en la banqueta, y vuelve a entrar **como si fuera la primera vez**."}, {"id": "t3", "tipo": "texto", "texto": "Camina el recorrido completo sin arreglar nada. Solo mira."}, {"id": "i1", "alt": "Encargada y dos vendedoras en una junta corta antes de abrir la tienda", "pie": "Cinco minutos antes de abrir valen más que una junta de una hora.", "src": "https://www.sacscloud.com/email/rezagados/rez-equipo.jpg", "tipo": "imagen"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Las tres cosas que siempre aparecen"}, {"id": "l1", "tipo": "lista", "items": ["🏷️ **Una prenda sin precio.** Siempre hay una. Y la gente no pregunta: se va.", "🕳️ **Un hueco.** Un espacio en un riel donde había algo y ya no. Se lee como «aquí ya no queda nada bueno».", "🚪 **Un punto muerto.** Un rincón por donde nadie pasa, y casi siempre tiene mercancía."]}, {"id": "t4", "tipo": "texto", "texto": "Ninguna de las tres sale en un reporte. Las tres cuestan venta hoy."}, {"id": "a1", "tipo": "aviso", "texto": "Hazlo con alguien de tu equipo y que cada quien anote por separado. Van a coincidir en dos cosas y a discrepar en una — y esa tercera suele ser la más interesante, porque significa que uno de los dos ya se acostumbró."}, {"id": "s1", "tipo": "separador"}, {"id": "b1", "sub": "Cuéntanos qué te encontraste", "href": "https://wa.me/12058920417?text=Hola,%20hice%20el%20recorrido%20y%20quiero%20platicar%20lo%20que%20encontre", "tipo": "boton", "align": "center", "texto": "📲 Enviar WhatsApp"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Repítelo un sábado a las seis de la tarde, con la tienda llena. Es otra tienda distinta y casi nadie la ve, porque a esa hora todos están cobrando."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados M6 · Pregúntale a quien se fue', 'La pregunta de una línea para quien no compró', 'Tu equipo ya sabe la respuesta. Nadie se la ha preguntado.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, este tip no cuesta nada y da la información más difícil de conseguir. 🗣️"}, {"id": "t2", "tipo": "texto", "texto": "Durante una semana, pídele a tu equipo que anote **una sola cosa**: cuando alguien se va sin comprar, ¿por qué?"}, {"id": "t3", "tipo": "texto", "texto": "Una palabra basta. En una libreta junto a la caja."}, {"id": "i1", "alt": "Una clienta saliendo del probador con dos prendas en la mano, decidiendo", "pie": "Lo que pasa aquí no aparece en ningún reporte de ventas.", "src": "https://www.sacscloud.com/email/rezagados/rez-probador.jpg", "tipo": "imagen"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Las respuestas casi siempre se repiten"}, {"id": "l1", "tipo": "lista", "items": ["📏 **«No estaba su talla»** — la más común, y la única que sí puedes resolver esta semana.", "🎨 **«No en ese color»** — te dice qué comprar la próxima vez.", "💵 **«Lo va a pensar»** — a veces es precio y a veces es que no encontró con qué combinarlo.", "🤷 **«Solo estaba viendo»** — pero si es la mayoría, el problema es el tráfico, no el surtido."]}, {"id": "a1", "tipo": "aviso", "texto": "Por qué importa tanto: **una venta que no ocurrió no se registra en ningún lado**. Tu sistema te dice perfectamente qué vendiste, y absolutamente nada de lo que estuviste a punto de vender. Esa libreta es el único lugar donde existe esa información."}, {"id": "s1", "tipo": "separador"}, {"id": "t5", "tipo": "texto", "texto": "Si la respuesta que más se repite es la talla, escríbenos: eso tiene solución concreta y rápida."}, {"id": "b1", "sub": "Mándanos lo que anotaron y lo vemos", "href": "https://wa.me/12058920417?text=Hola,%20hicimos%20la%20libreta%20de%20por%20que%20no%20compraron%20y%20quiero%20platicarlo", "tipo": "boton", "align": "center", "texto": "📲 Enviar WhatsApp"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Una semana basta. Más de dos y el equipo deja de anotar, así que mejor hacerlo corto, mirar el resultado y repetirlo en tres meses."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V3 · Sugerencia de outfits', 'Nuevo: la IA arma el outfit por tu vendedora', '«¿Con qué me lo pongo?» — la pregunta que sube el ticket 40%.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, viernes de función nueva. Esta ataca el momento más caro de tu piso de venta. 👗"}, {"id": "t2", "tipo": "texto", "texto": "La clienta ya tiene la prenda en la mano. Le gusta. Y pregunta:"}, {"id": "t3", "tipo": "texto", "texto": "**«¿Con qué me lo pongo?»**"}, {"id": "t4", "tipo": "texto", "texto": "Ahí se decide si sale con una pieza o con tres. Y hoy esa respuesta depende de si le tocó la vendedora que lleva tres años o la que entró el mes pasado."}, {"id": "i1", "alt": "Una clienta saliendo del probador con dos prendas, decidiendo", "pie": "El momento exacto donde el ticket se duplica o no.", "src": "https://www.sacscloud.com/email/rezagados/rez-probador.jpg", "tipo": "imagen"}, {"id": "s1", "tipo": "separador"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Lo que ahora hace Sacs"}, {"id": "t5", "tipo": "texto", "texto": "La IA analiza tu historial de compras y las combinaciones que de verdad se han vendido juntas, y **sugiere el outfit completo** — sobre tu inventario real, no sobre un catálogo genérico."}, {"id": "l1", "tipo": "lista", "items": ["🧠 **Aprende de tus ventas**, no de tendencias de otro país.", "✅ **Solo sugiere lo que hay**, con su talla, en esa tienda.", "👩‍💼 **Iguala al equipo**: la vendedora nueva propone como la que lleva años."]}, {"id": "m1", "tipo": "metricas", "items": [{"cifra": "+40%", "texto": "en ticket promedio"}, {"cifra": "3 piezas", "texto": "en vez de una"}, {"cifra": "0", "texto": "capacitación extra"}]}, {"id": "a1", "tipo": "aviso", "texto": "Dónde pega más fuerte: en los estilos que no se venden solos pero funcionan como acompañamiento. Esos casi nunca se sugieren porque nadie se acuerda de ellos — y son justo los que llevan meses parados."}, {"id": "s2", "tipo": "separador"}, {"id": "t6", "tipo": "texto", "texto": "¿Lo vemos con tu catálogo? Se nota en la primera semana."}, {"id": "b1", "sub": "Te lo enseñamos con tus prendas", "href": "https://wa.me/12058920417?text=Hola,%20quiero%20ver%20la%20sugerencia%20de%20outfits%20con%20mi%20catalogo", "tipo": "boton", "align": "center", "texto": "📲 Enviar WhatsApp"}, {"id": "b2", "sub": "30 minutos, sin costo · eliges el horario y queda confirmada al momento", "href": "https://www.sacscloud.com/agendar/demo", "tipo": "boton", "align": "center", "texto": "📅 Agendar una demo"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Se cotiza por sucursal y va aparte del plan base. Pregunta y te paso el número para tu caso."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V4 · Pre-órdenes VIP', 'Nuevo: vende la colección antes de que llegue', 'Tus mejores clientas reservan con anticipo. Tú compras sobre pedido.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, esta función cambia el orden de las cosas. Y el orden es donde está el dinero. 💎"}, {"id": "t2", "tipo": "texto", "texto": "Hoy compras la colección, llega, y **después** ves si gusta."}, {"id": "t3", "tipo": "texto", "texto": "Pagaste, guardaste y esperaste — con tu dinero adentro y sin saber."}, {"id": "s0", "tipo": "separador"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Lo que ahora hace Sacs"}, {"id": "t4", "tipo": "texto", "texto": "Abres la colección **solo a tus clientas VIP** antes del lanzamiento. Ellas reservan con anticipo, y tú sabes qué se va a vender antes de que llegue el pedido."}, {"id": "i1", "alt": "Visual merchandiser preparando el aparador con un vestido azul cobalto al anochecer", "pie": "La colección se vende antes de estar en la vitrina.", "src": "https://www.sacscloud.com/email/rezagados/rez-vitrina-noche.jpg", "tipo": "imagen"}, {"id": "l1", "tipo": "lista", "items": ["🔒 **Acceso anticipado** para quien tú elijas. Se siente como un privilegio, porque lo es.", "💳 **Apartado con anticipo**, así que hay compromiso real y no una lista de deseos.", "🔔 **Notificación automática** cuando llega su pieza.", "📊 **Demanda antes de comprar**: sabes qué tallas y colores pedir de más y cuáles casi no."]}, {"id": "a1", "tipo": "aviso", "texto": "El efecto secundario es el mejor: tus clientas VIP dejan de ser una etiqueta en el sistema y se vuelven las primeras en ver todo. Eso construye la relación que ninguna promoción compra."}, {"id": "s1", "tipo": "separador"}, {"id": "t5", "tipo": "texto", "texto": "Si tienes una colección próxima, es el momento de montarlo — se arma en días, no en semanas."}, {"id": "b1", "sub": "30 minutos, sin costo · eliges el horario y queda confirmada al momento", "href": "https://www.sacscloud.com/agendar/demo", "tipo": "boton", "align": "center", "texto": "📅 Agendar una demo"}, {"id": "b2", "sub": "¿Tienes colección en puerta? Escríbenos", "href": "https://wa.me/12058920417?text=Hola,%20quiero%20ver%20las%20pre-ordenes%20VIP%20para%20mi%20proxima%20coleccion", "tipo": "boton", "align": "center", "texto": "📲 Enviar WhatsApp"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Con veinte clientas VIP y una reserva promedio de dos piezas, ya financias parte del pedido antes de pagarlo. Esa es la cuenta que hace que valga la pena."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V5 · Pasarelas en tienda', 'Nuevo: monta un desfile en tu propia tienda', 'Con su orden de salida, sus outfits y sus piezas reservadas.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, esta es de las que no esperas de un sistema de punto de venta. ✨"}, {"id": "t2", "tipo": "texto", "texto": "Un desfile en tu tienda es la forma más rápida de convertir una noche en la venta de una semana. Y de que tus clientas traigan a sus amigas."}, {"id": "t3", "tipo": "texto", "texto": "El problema nunca fue la idea. Fue la logística."}, {"id": "i1", "alt": "Backstage de un desfile en tienda: modelos en fila esperando junto a un burro de ropa", "pie": "Lo complicado nunca fue el desfile. Fue lo de atrás.", "src": "https://www.sacscloud.com/email/rezagados/rez-pasarela.jpg", "tipo": "imagen"}, {"id": "s1", "tipo": "separador"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Lo que ahora hace Sacs"}, {"id": "l1", "tipo": "lista", "items": ["👠 **Arma los outfits** con piezas de tu inventario real, con su talla y su existencia.", "📋 **Orden de salida** por modelo y por look, para que nadie improvise esa noche.", "🔖 **Reserva en el momento**: la clienta ve el look, lo aparta desde la pasarela y queda ligado a su ficha.", "📈 **Mide qué look vendió**, no solo cuánto se vendió en total."]}, {"id": "a1", "tipo": "aviso", "texto": "Ese último punto es el que casi nadie tiene. Después de un evento todos saben cuánto vendieron; muy pocos saben **qué look** fue el que movió la noche — que es exactamente lo que hay que repetir en la vitrina el lunes."}, {"id": "s2", "tipo": "separador"}, {"id": "t4", "tipo": "texto", "texto": "Si tienes espacio y clientas, esto se monta con lo que ya tienes. Te contamos cómo."}, {"id": "b1", "sub": "Te decimos qué necesitas", "href": "https://wa.me/12058920417?text=Hola,%20quiero%20saber%20como%20montar%20una%20pasarela%20en%20mi%20tienda", "tipo": "boton", "align": "center", "texto": "📲 Enviar WhatsApp"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. No hace falta una tienda enorme. Los desfiles que mejor funcionan son los de treinta personas y ocho looks, en una tarde entre semana."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Rezagados V6 · Temporadas y colecciones', 'Nuevo: tu inventario entiende de temporadas', 'Primavera-Verano y Otoño-Invierno dejan de ser una etiqueta.', 'automatizado', 'simple', 'novedades',
        '[{"id": "t1", "tipo": "texto", "texto": "{{nombre|Hola}}, esta función es menos vistosa que otras y probablemente la que más te ahorre. 🗂️"}, {"id": "t2", "tipo": "texto", "texto": "En moda no vendes productos: vendes **temporadas**. Y casi ningún sistema lo entiende."}, {"id": "t3", "tipo": "texto", "texto": "Por eso tu reporte mezcla la blusa de esta primavera con la del año pasado como si fueran lo mismo — y no lo son ni en precio, ni en margen, ni en urgencia."}, {"id": "i1", "alt": "Equipo de tienda montando el piso de rebajas con racks de ropa de colores", "pie": "Cuando el sistema no sabe de temporadas, tú tienes que acordarte de todo.", "src": "https://www.sacscloud.com/email/rezagados/rez-rebajas.jpg", "tipo": "imagen"}, {"id": "s1", "tipo": "separador"}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Lo que ahora hace Sacs"}, {"id": "l1", "tipo": "lista", "items": ["📅 **Cada prenda pertenece a su temporada**, con fecha de entrada y de salida.", "🧮 **Sell-through por temporada**, no revuelto con el histórico.", "⏳ **Alerta de fin de temporada** antes de que sea saldo, no después.", "🔄 **Transición**: qué entra, qué se rebaja y qué se guarda para el año que viene."]}, {"id": "a1", "tipo": "aviso", "texto": "La diferencia práctica: dejas de decidir la rebaja por corazonada o por calendario del centro comercial, y empiezas a decidirla por **dónde va esa temporada contra la anterior**. Es la misma información, ordenada por donde de verdad se corta."}, {"id": "s2", "tipo": "separador"}, {"id": "t4", "tipo": "texto", "texto": "Si vas entrando a una transición de temporada, es el mejor momento para montarlo."}, {"id": "b1", "sub": "30 minutos, sin costo · eliges el horario y queda confirmada al momento", "href": "https://www.sacscloud.com/agendar/demo", "tipo": "boton", "align": "center", "texto": "📅 Agendar una demo"}, {"id": "fi", "tipo": "firma", "nombre": "Andrea Gutiérrez Araujo", "puesto": "Tu consultora en Sacs", "foto_url": "https://www.sacscloud.com/images/andrea-consultora.jpg"}, {"id": "pd", "tipo": "texto", "texto": "P.D. El caso que más se repite: mercancía de hace dos temporadas que sigue contando como inventario a valor lleno. En papel eres más rico de lo que eres."}]'::jsonb, true) on conflict do nothing;

insert into crm_secuencia_pasos (secuencia_id, orden, dia, dia_semana, canal, email_template_id, activo)
select s.id, p.orden, 1, p.dsem, 'correo', t.id, true
from crm_secuencias s
cross join (values
  (101, 1, 'Rezagados L2 · El denominador'),
  (102, 1, 'Rezagados L3 · Semanas de cobertura'),
  (103, 1, 'Rezagados L4 · Rebajar tarde'),
  (104, 1, 'Rezagados L5 · Margen sobre costo'),
  (105, 1, 'Rezagados L6 · El 35% que se devuelve'),
  (106, 3, 'Rezagados M2 · Los tres montones'),
  (107, 3, 'Rezagados M3 · Los cinco de siempre'),
  (108, 3, 'Rezagados M4 · La foto de tu vitrina'),
  (109, 3, 'Rezagados M5 · El recorrido de cinco minutos'),
  (110, 3, 'Rezagados M6 · Pregúntale a quien se fue'),
  (111, 5, 'Rezagados V3 · Sugerencia de outfits'),
  (112, 5, 'Rezagados V4 · Pre-órdenes VIP'),
  (113, 5, 'Rezagados V5 · Pasarelas en tienda'),
  (114, 5, 'Rezagados V6 · Temporadas y colecciones')
) as p(orden, dsem, plantilla)
join email_templates t on t.nombre = p.plantilla
where s.nombre = 'Rezagados · top of mind'
  and not exists (select 1 from crm_secuencia_pasos x where x.secuencia_id = s.id and x.email_template_id = t.id);

commit;
