-- «Winback · los que se fueron»: los quince correos.
--
-- CUATRO FASES, y el orden es todo el diseño:
--
--   1-4   ESCUCHAR      no se ofrece NADA. Solo la pregunta de qué pasó.
--   5-9   LO QUE CAMBIÓ tampoco se pide nada. Se cuenta qué se arregló.
--  10-14  LA OFERTA     el año sin costo, con la garantía y el porqué honesto.
--   15    LA PUERTA     se cierra bien, sin última oferta.
--
-- Mandar la oferta en el correo 1 habría sido el mismo error que los hizo irse:
-- resolver con dinero algo que era de confianza. Un año gratis ofrecido antes
-- de preguntar qué falló se lee como desesperación, y a quien ya se fue eso lo
-- confirma en su decisión.
--
-- LOS CUATRO PRIMEROS NO LLEVAN OFERTA Y TRES NI SIQUIERA BOTÓN. El correo 1
-- pide que contesten el correo con una línea, nada más. Bajar el umbral hasta
-- ahí es lo único que funciona con alguien que ya no te debe nada.
--
-- EL TONO ES MODESTO A PROPÓSITO. No dice «volvimos mejores»: dice «te fallamos
-- y no preguntamos por qué». El correo 13 llega a decir que la oferta nos
-- conviene — porque fingir generosidad con alguien que ya nos vio fallar es la
-- forma más rápida de perderlo otra vez.
begin;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 1 · Nos dimos cuenta', 'Dejaste de usar Sacs y no te preguntamos por qué', 'Sin oferta. Solo la pregunta.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este correo no trae ninguna promoción. Lo digo de entrada para que no lo leas esperándola."},{"id":"t2","tipo":"texto","texto":"Revisando cuentas nos dimos cuenta de que **dejaste de usar Sacs**. Y lo peor no es eso: es que nos dimos cuenta tarde y nunca te preguntamos por qué."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"No sé si fue el sistema, el acompañamiento, el precio, o simplemente que tu negocio tomó otro camino. Cualquiera de las cuatro es una respuesta legítima y todas nos sirven."},{"id":"a1","tipo":"aviso","texto":"Lo que sí sé es que si no preguntamos, lo vamos a repetir con el siguiente. **Eso es lo que quiero evitar**, y por eso escribo."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Contéstame este correo con una línea. Aunque sea «no funcionó y ya». Con eso me basta."},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si prefieres no contestar, también está bien. En unos días te vuelvo a escribir una vez más y luego te dejo en paz."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 2 · Nuestro director quiere hablar contigo', 'Nuestro director quiere escuchar qué pasó', 'Media hora, con quien toma las decisiones.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, insisto una vez y con algo distinto."},{"id":"t2","tipo":"texto","texto":"No te escribo yo esta vez por mi cuenta: **la dirección de Sacs quiere hablar contigo directamente.** Media hora, para escuchar qué pasó."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Por qué el director y no un vendedor"},{"id":"t3","tipo":"texto","texto":"Porque lo que tengas que decir probablemente no es un detalle operativo que arregle un consultor. Es algo de fondo — cómo trabajamos, qué prometimos, en qué te fallamos — y eso lo tiene que oír quien puede cambiarlo."},{"id":"a1","tipo":"aviso","texto":"No es una junta de ventas disfrazada. **No hay nada que firmar ni que decidir** — es escucharte. Si al final quieres seguir sin nosotros, seguimos sin nosotros."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Agendar 30 minutos con dirección","href":"https://www.sacscloud.com/agendar/direccion","align":"center","sub":"Media hora · sin costo · sin agenda de venta"},{"id":"b2","tipo":"boton","texto":"💬 O contéstame por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20prefiero%20contarles%20por%20aqui%20que%20paso","align":"center","sub":"Si prefieres escribirlo, también sirve","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 3 · No es para convencerte', 'Esto no es para que regreses', 'Aclarando la intención, porque suele malinterpretarse.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, quiero aclarar algo porque estos correos se malinterpretan seguido."},{"id":"t2","tipo":"texto","texto":"**No te escribo para que regreses.** Te escribo para entender por qué te fuiste, que no es lo mismo."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"La diferencia importa: si el objetivo fuera que regreses, ya te habría mandado una oferta. Y una oferta antes de entender qué falló es exactamente el error que nos trajo hasta aquí."},{"id":"a1","tipo":"aviso","texto":"Un cliente que se va sin decir por qué es un problema que se repite. Uno que dice por qué es **la única forma de arreglarlo** — para ti si algún día vuelves, y para el que viene si no."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Media hora con la dirección, o dos líneas por WhatsApp. Lo que te sea más fácil."},{"id":"b1","tipo":"boton","texto":"📅 Agendar 30 minutos con dirección","href":"https://www.sacscloud.com/agendar/direccion","align":"center","sub":"Media hora · sin costo · sin agenda de venta"},{"id":"b2","tipo":"boton","texto":"💬 O contéstame por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20les%20cuento%20en%20dos%20lineas%20que%20paso","align":"center","sub":"Dos líneas bastan","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 4 · Aunque sea una frase', '¿Me contestas con una frase?', 'Bajo el umbral todo lo que puedo.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, última vez que insisto con esto, y voy a pedirte lo mínimo."},{"id":"t2","tipo":"texto","texto":"No una reunión. No un formulario. **Una frase.**"},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Elige la que más se acerque y contéstame con ella:"},{"id":"l1","tipo":"lista","items":["«El sistema no hacía lo que necesitaba»","«Nadie nos acompañó y nos quedamos atorados»","«Salía muy caro para lo que usábamos»","«Cambió mi negocio, no fue por ustedes»","«Otra cosa» — y ahí sí cuéntame"]},{"id":"a1","tipo":"aviso","texto":"Cualquiera de las cinco me sirve. La que más me duele —la segunda— es la que más necesito escuchar, así que no te la guardes por educación."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"💬 O contéstame por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20les%20contesto:%20","align":"center","sub":"Contéstame por aquí, es más rápido","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. A partir de aquí dejo de preguntar. Lo que siga es otra cosa, y no te va a pedir nada."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 5 · Lo que arreglamos', 'Lo que cambiamos desde que te fuiste', 'Sin pedirte nada. Solo por si te interesa.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, cambié de tema. Esto no pide nada."},{"id":"t2","tipo":"texto","texto":"De las conversaciones con clientes que se fueron —algunos contestaron— salieron tres cosas que estaban mal, y las tres se atendieron:"},{"id":"s0","tipo":"separador"},{"id":"l1","tipo":"lista","items":["🚪 **Se entraba solo.** Hoy hay un acompañamiento de arranque real, con una persona asignada, no un correo de bienvenida.","🔇 **Nadie avisaba si dejabas de usarlo.** Ahora el sistema lo detecta y alguien llama.","🧩 **Lo que no venía, no venía.** Hoy se puede personalizar casi cualquier flujo del negocio."]},{"id":"a1","tipo":"aviso","texto":"No te lo cuento para que vuelvas. Te lo cuento porque **si te fuiste por alguna de esas tres, era culpa nuestra** y me parece justo que sepas que ya no pasa."},{"id":"s1","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Si quieres verlo, avísame. Y si no, este correo se queda como está: un aviso, no una propuesta."},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 6 · Ya no dependes de nosotros', 'Lo que antes había que pedirnos, ahora lo haces tú', 'El cambio que más se nota.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, sigo con lo que cambió, y este es el que más se nota en el día a día."},{"id":"t2","tipo":"texto","texto":"Antes, varias cosas dependían de que nos escribieras: configurar una regla, mover algo de inventario a nivel sistema, ajustar un flujo. **Eso era un cuello de botella nuestro que pagabas tú.**"},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Hoy"},{"id":"l1","tipo":"lista","items":["🤖 **Axo** configura por chat lo que antes requería un ticket.","⚙️ Las reglas de tu operación las defines tú, sin esperar a nadie.","📊 Los reportes que pedías por correo salen solos."]},{"id":"a1","tipo":"aviso","texto":"La medida honesta de un buen sistema no es cuánto te ayuda su soporte. Es **cuántas veces al mes necesitas escribirle**."},{"id":"s1","tipo":"separador"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Sigo sin pedirte nada. Falta poco para que sí, y te aviso cuando llegue."}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 7 · El acompañamiento es otro', 'Ya nadie arranca solo', 'Lo que más nos reclamaron, y qué hicimos.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este es el punto donde más nos equivocamos, así que voy a ser específico. 🤝"},{"id":"t2","tipo":"texto","texto":"Antes se entregaba el acceso y se daba por hecho que el cliente encontraría el camino. Quien tenía tiempo, lo encontraba. **Quien no, se quedaba a la mitad y dejaba de entrar.**"},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Cómo funciona ahora"},{"id":"l1","tipo":"lista","items":["👤 **Una persona asignada** desde el primer día, con nombre.","📋 **Un plan de arranque** por escrito: qué se carga primero y quién lo hace.","📞 **Sesiones de acompañamiento** durante la implementación, no un video.","✅ **Un punto de «listo»** acordado — para saber cuándo terminó, en vez de que se diluya."]},{"id":"a1","tipo":"aviso","texto":"Si tu razón de irte fue «nos dejaron solos», esto es exactamente lo que se cambió. Y lo digo sin orgullo: **debió estar así desde el principio.**"},{"id":"s1","tipo":"separador"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 8 · Lo que hacen hoy las marcas como la tuya', 'Lo que hacen hoy las marcas parecidas a la tuya', 'Por si sirve de referencia, aunque no vuelvas.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, hoy algo que sirve aunque nunca vuelvas."},{"id":"t2","tipo":"texto","texto":"Las marcas de moda que mejor operan hoy hacen tres cosas que hace dos años casi nadie hacía:"},{"id":"s0","tipo":"separador"},{"id":"l1","tipo":"lista","items":["📐 **Compran por curva de tienda**, no por curva de marca. El promedio no existe en ninguna sucursal.","🔁 **Nivelan antes de recomprar.** Primero acomodan lo que ya pagaron entre sus tiendas.","📸 **Publican desde el catálogo**, no desde una carpeta de fotos aparte."]},{"id":"a1","tipo":"aviso","texto":"Te lo cuento porque son prácticas, no funciones. Se pueden hacer con Sacs, con otro sistema o con disciplina y una hoja de cálculo. **Lo que cuesta caro es no hacerlas.**"},{"id":"s1","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Si alguna te suena a algo que te está pasando, escríbeme y lo platicamos — sin que eso signifique nada más."},{"id":"b1","tipo":"boton","texto":"💬 O contéstame por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20platicar%20sobre%20algo%20de%20lo%20que%20me%20mandaron","align":"center","sub":"Sin compromiso de nada","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 9 · Tus datos siguen ahí', 'Lo que cargaste sigue guardado', 'Por si algún día lo necesitas, o por si quieres llevártelo.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, un aviso práctico que probablemente no sabías."},{"id":"t2","tipo":"texto","texto":"**Todo lo que cargaste sigue guardado**: tu catálogo, tus clientes, tu histórico de ventas. No se borró cuando dejaste de usarlo."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Eso significa dos cosas, y las dos son tuyas:"},{"id":"l1","tipo":"lista","items":["📤 **Te lo puedes llevar.** Si lo necesitas para otro sistema o para tu contador, te lo exportamos. Sin costo y sin condiciones.","🔓 **Si algún día vuelves, no empiezas de cero.** Está todo donde lo dejaste."]},{"id":"a1","tipo":"aviso","texto":"Lo primero lo digo en serio: **pídelo y te lo mandamos**, aunque nunca vuelvas a hablarnos. Tus datos son tuyos y no son una palanca de negociación."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"💬 O contéstame por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20que%20me%20exporten%20mis%20datos","align":"center","sub":"Te los mandamos, sin condiciones","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 10 · Un año completo, sin costo', 'Un año de Sacs sin costo, en el plan más completo', 'Y no hay letra chica. Te explico por qué lo hacemos.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, llevo nueve correos sin pedirte nada. Este es el que sí trae algo, y quiero que sepas exactamente qué es."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Un año completo de Sacs, sin costo"},{"id":"t2","tipo":"texto","texto":"No un descuento. No un mes de prueba. **Un año entero**, en nuestro plan más avanzado, con todo incluido:"},{"id":"l1","tipo":"lista","items":["🚀 **El plan más completo**, no una versión recortada.","🤝 **Acompañamiento de arranque**, con una persona asignada y un plan por escrito.","🛡️ **Garantía de implementación**: si no queda operando, no seguimos.","📦 **Tus datos de vuelta**, donde los dejaste."]},{"id":"s1","tipo":"separador"},{"id":"h2","tipo":"encabezado","nivel":2,"texto":"Por qué haríamos esto"},{"id":"t3","tipo":"texto","texto":"Porque te fallamos y un descuento no arregla eso. Y porque —siendo honesto— **nos conviene**: un cliente que se fue y vuelve a quedarse nos enseña más que diez nuevos, y si el año sale bien, al terminarlo decides con datos y no con una promesa."},{"id":"a1","tipo":"aviso","texto":"Si al final del año no te sirve, te vas otra vez y esta vez sabremos por qué. **Ese es el trato completo, no hay más.**"},{"id":"s2","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Platicarlo con dirección","href":"https://www.sacscloud.com/agendar/direccion","align":"center","sub":"Media hora · sin costo · sin agenda de venta"},{"id":"b2","tipo":"boton","texto":"💬 O escríbeme por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20saber%20mas%20del%20ano%20sin%20costo","align":"center","sub":"O pregúntame lo que quieras por aquí","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 11 · Qué significa «con acompañamiento»', 'Qué incluye exactamente el acompañamiento', 'Para que no suene a frase de folleto.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, «con acompañamiento» es de esas frases que no dicen nada, así que la desarmo."},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Lo que se hace, y quién lo hace"},{"id":"l1","tipo":"lista","items":["1️⃣ **Una sesión para entender tu operación** antes de tocar el sistema. Qué vendes, cuántas sucursales, de dónde sale tu inventario.","2️⃣ **Nosotros cargamos tu catálogo.** No te mandamos una plantilla de Excel para que la llenes tú.","3️⃣ **Configuramos tus reglas contigo**: tallas, precios, sucursales, permisos de tu equipo.","4️⃣ **Capacitamos a quien lo va a usar**, no solo a quien firma.","5️⃣ **Revisamos a los 15 y a los 30 días** que siga funcionando."]},{"id":"a1","tipo":"aviso","texto":"Con **una persona asignada, con nombre**, que te contesta a ti. No una bandeja de soporte donde tu caso es un número."},{"id":"s1","tipo":"separador"},{"id":"t2","tipo":"texto","texto":"Esto no es un extra del año gratis: es cómo debió haber sido la primera vez."},{"id":"b1","tipo":"boton","texto":"📅 Agendar 30 minutos con dirección","href":"https://www.sacscloud.com/agendar/direccion","align":"center","sub":"Media hora · sin costo · sin agenda de venta"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 12 · La garantía', 'Si no queda operando, no seguimos', 'La parte que nos obliga a nosotros, no a ti.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, la parte del trato que nos ata a nosotros. 🛡️"},{"id":"s0","tipo":"separador"},{"id":"h1","tipo":"encabezado","nivel":2,"texto":"Garantía de implementación"},{"id":"t2","tipo":"texto","texto":"Al terminar el arranque tu operación tiene que estar **corriendo de verdad**: tu catálogo cargado, tu equipo vendiendo en el sistema, tus reportes saliendo."},{"id":"t3","tipo":"texto","texto":"Si no llega a ese punto, **no seguimos y no te cuesta nada** — ni siquiera el tiempo que ya invertimos. Y si te llevas aprendizajes de tu operación, te los quedas."},{"id":"a1","tipo":"aviso","texto":"Lo pongo por escrito porque la primera vez la promesa fue verbal, general, y por eso nadie la pudo reclamar. **Una garantía que no se puede reclamar no es una garantía.**"},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"El punto de «listo» se acuerda contigo antes de empezar, no lo definimos nosotros al final."},{"id":"b1","tipo":"boton","texto":"📅 Agendar 30 minutos con dirección","href":"https://www.sacscloud.com/agendar/direccion","align":"center","sub":"Media hora · sin costo · sin agenda de venta"},{"id":"b2","tipo":"boton","texto":"💬 O escríbeme por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20entender%20la%20garantia%20de%20implementacion","align":"center","sub":"¿Dudas de la garantía? Pregúntame","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 13 · Por qué a ti', 'Por qué te lo ofrecemos a ti y no a cualquiera', 'La respuesta honesta, aunque no suene bonita.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, una pregunta que yo también me haría: **¿por qué a mí?**"},{"id":"s0","tipo":"separador"},{"id":"t2","tipo":"texto","texto":"La respuesta honesta tiene dos partes, y la segunda no suena bonita."},{"id":"t3","tipo":"texto","texto":"**La primera:** ya conoces el sistema. No hay que enseñarte qué es un catálogo con tallas ni por qué importa un corte de caja. Empezar contigo cuesta menos que empezar de cero con alguien nuevo."},{"id":"t4","tipo":"texto","texto":"**La segunda:** te fuiste, y eso es información que necesitamos. Un año contigo dentro, viendo qué funciona y qué no, vale más para nosotros que el año que regalamos."},{"id":"a1","tipo":"aviso","texto":"No es caridad y no es un premio. **Es un intercambio**, y prefiero decírtelo así a fingir generosidad."},{"id":"s1","tipo":"separador"},{"id":"t5","tipo":"texto","texto":"Si te parece un mal trato, dímelo y lo ajustamos. Y si te parece que no vale tu tiempo, también es una respuesta."},{"id":"b1","tipo":"boton","texto":"📅 Agendar 30 minutos con dirección","href":"https://www.sacscloud.com/agendar/direccion","align":"center","sub":"Media hora · sin costo · sin agenda de venta"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 14 · Sigue en pie', 'La oferta sigue en pie', 'Sin fecha límite y sin presión.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, correo corto."},{"id":"t2","tipo":"texto","texto":"**El año sin costo sigue en pie.** No tiene fecha límite ni se acaba el viernes — no voy a inventarte una urgencia que no existe."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Sé que el momento importa: si estás en temporada alta, cambiar de sistema es lo último que quieres hacer. Si es tu caso, dímelo y lo retomamos cuando te sirva."},{"id":"a1","tipo":"aviso","texto":"Lo único que se acaba es mi insistencia: **te queda un correo más de mi parte** y ahí paro."},{"id":"s1","tipo":"separador"},{"id":"b1","tipo":"boton","texto":"📅 Agendar 30 minutos con dirección","href":"https://www.sacscloud.com/agendar/direccion","align":"center","sub":"Media hora · sin costo · sin agenda de venta"},{"id":"b2","tipo":"boton","texto":"💬 O escríbeme por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20me%20interesa%20pero%20no%20es%20buen%20momento","align":"center","sub":"¿No es buen momento? Dímelo y lo retomamos después","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"}]'::jsonb, true) on conflict do nothing;

insert into email_templates (nombre, asunto, preview_text, tipo, layout, categoria, bloques, activo)
values ('Winback 15 · Aquí le paro', 'Este es el último. Gracias por leer.', 'Sin reproche y sin última oferta.', 'automatizado', 'simple', 'relacion',
        '[{"id":"t1","tipo":"texto","texto":"{{nombre|Hola}}, este es el último correo que te mando de esta serie."},{"id":"t2","tipo":"texto","texto":"No hay una oferta final ni un «última oportunidad». Solo cierro bien."},{"id":"s0","tipo":"separador"},{"id":"t3","tipo":"texto","texto":"Te escribí quince veces en unos meses. Empecé preguntando qué pasó, seguí contándote lo que cambiamos y terminé ofreciéndote un año sin costo. **Si nada de eso te movió, la respuesta está clara** y la respeto."},{"id":"a1","tipo":"aviso","texto":"Lo que dije sigue siendo cierto aunque no contestes: **tus datos siguen guardados y te los exportamos cuando quieras**, sin condiciones. Eso no era parte de una negociación."},{"id":"s1","tipo":"separador"},{"id":"t4","tipo":"texto","texto":"Y si algún día cambian las cosas —creces, abres otra sucursal, tu sistema actual se queda corto— me escribes y seguimos donde nos quedamos. Sin explicaciones."},{"id":"t5","tipo":"texto","texto":"Gracias por haber sido cliente. De verdad."},{"id":"b1","tipo":"boton","texto":"💬 O escríbeme por WhatsApp","href":"https://wa.me/12058920417?text=Hola,%20quiero%20retomar%20lo%20que%20platicamos","align":"center","sub":"La puerta queda abierta, sin fecha","color":"#2AB5A0"},{"id":"fi","tipo":"firma","nombre":"Andrea Gutiérrez Araujo","puesto":"Tu consultora en Sacs","foto_url":"https://www.sacscloud.com/images/andrea-consultora.jpg"},{"id":"pd","tipo":"texto","texto":"P.D. Si de todo esto solo me contestas una cosa, que sea qué falló. Sigue siendo lo que más nos serviría."}]'::jsonb, true) on conflict do nothing;

commit;
