-- 13-sep-2026 · El caso del día 5 de la cadencia de leads pasa a Liveshow Merchandising.
-- Decisión del dueño: a un lead de moda le pega más un caso donde el reto sea el suyo.
-- Liveshow no es de moda, pero habla de lo que sí comparte con una boutique: el día pico.
-- Las cifras salen de conocimiento/casos.ts (publicadas), no de una estimación.

update email_templates set
  nombre = 'Cadencia · Caso Liveshow Merchandising',
  asunto = 'Cien cajas vendiendo a la vez, sin internet',
  preview_text = 'Lo que un festival de 75,000 personas le enseña a tu boutique sobre sus días pico.',
  bloques = '[{"id": "t1", "tipo": "texto", "texto": "Déjame contarte de un caso que no es de moda — y por qué es justo el que más te conviene conocer.\n\nLiveshow Merchandising vende la mercancía oficial de conciertos y festivales: playeras, sudaderas, gorras. Todo su año se juega en unas cuantas noches, cuando setenta y cinco mil personas quieren comprar al mismo tiempo y la fila no puede parar."}, {"id": "t2", "tipo": "texto", "texto": "Antes, una caída del sistema les costó el veinte por ciento de las ventas en dos horas. Hoy operan más de cien puntos de venta simultáneos y procesaron ciento cincuenta mil transacciones en una temporada, sin un solo error."}, {"id": "h1", "tipo": "encabezado", "nivel": 2, "texto": "Lo que hoy opera con Sacs"}, {"id": "l1", "tipo": "lista", "items": ["Cobro sin internet — cuando la señal se cae, la caja sigue vendiendo y todo se sincroniza después", "Más de cien puntos de venta a la vez, con el inventario de todos a la vista en el mismo tablero", "Las auditorías manuales de doce horas desaparecieron: el corte sale solo al cerrar"]}, {"id": "i1", "tipo": "imagen", "src": "https://www.sacscloud.com/images/case-liveshow.webp", "alt": "Punto de venta operando en un festival con Sacs", "pie": "Cien cajas vendiendo a la vez, sin internet y sin perder un ticket."}, {"id": "h2", "tipo": "encabezado", "nivel": 2, "texto": "¿Y tu boutique qué?"}, {"id": "t3", "tipo": "texto", "texto": "Tu negocio también tiene sus noches de festival: el Buen Fin, una venta nocturna, el arranque de temporada, un liveshow. Son los días en que entra la mayor parte del dinero del mes… y justo cuando el control se rompe.\n\nSi el sistema aguanta cien cajas en un festival, aguanta tu mejor sábado — con tallas, colores y apartados encima."}, {"id": "a1", "tipo": "aviso", "texto": "Andrea, tu consultora, acompañó estos procesos de inicio a fin — es la misma que te va a acompañar a ti."}, {"id": "bt", "tipo": "boton", "align": "center", "texto": "Agendar mi sesión consultiva →", "sub": "20 minutos · sin costo · con tu boutique", "href": "https://www.sacscloud.com/contacto"}, {"id": "pd", "tipo": "texto", "texto": "P.D. Lo que se rompe en un pico de venta no es el cobro: es saber qué te queda. Eso se ve en veinte minutos con tus propias prendas."}]'::jsonb,
  html_compilado = null,
  texto_plano = null,
  updated_at = now()
where id = '0a5e5a09-1122-447e-acc7-750eca29d769';
