# Configuración por giro del barrido nacional de Google Maps.
# stems: consultas ("<stem> <ciudad>"); cat_ok: la categoría de Maps debe contener alguna (si hay lista);
# cat_fuera / nombre_fuera: exclusiones propias; subgiro: str o función(cuenta)->str.
import re
def _sub(reglas, default):
    def f(c):
        n = c['nombre_maps'] + ' ' + c['nombre']
        for rx, s in reglas:
            if re.search(rx, n, re.I): return s
        return default
    return f
GIROS = {
 'boutiques': dict(stems=['boutique de ropa de mujer','boutique de ropa'],
    cat_ok=('tienda de ropa','boutique','tienda de moda','tienda de ropa de mujer','tienda de ropa de hombre','tienda de ropa de niños','tienda de ropa infantil'),
    cat_fuera=('mayorista','fábrica','uniformes','segunda mano','vintage','ropa de trabajo','ropa de deportes','lencería','ropa interior','premamá','ropa de playa','tallas grandes','tienda de vestidos de novia'),
    nombre_fuera=r'novia|bridal|\bxv\b|quince|renta|alquiler|smoking|esmoquin|mayoreo|uniforme|vintage|outlet|tallas? extra|plus size|curvy|julio\b|ivonne|optima|studio f|cklass|price shoes|andrea\b|vestidos? de',
    nombre_ok=r'boutique|moda|ropa|fashion|store|closet|vestir|shop',
    subgiro=_sub([(r'hombre|caballero|\bmen\b', 'caballero'), (r'ni[nñ]|kids|infantil|beb[eé]', 'infantil'), (r'dama|mujer|women|femenin|girl|chic', 'dama')], 'dama')),
 'zapaterias': dict(stems=['zapatería','tienda de zapatos'],
    cat_ok=('zapatería','tienda de calzado','tienda de zapatos','tienda de botas','tienda de tenis','tienda de ropa'),
    cat_fuera=('reparación','zapatero','ortopedi','deportes','fábrica'),
    nombre_fuera=r'flexi\b|price shoes|andrea\b|cklass|nine west|steve madden|capa de ozono|dorothy gaynor|\bpakar\b|emyco|skechers|\bnike\b|adidas|\bpuma\b|\bvans\b|converse|crocs|\bcuadra\b|reparaci|ortop|dr\.? scholl|charly|innovasport|mart[ií]\b|dportenis|calzado industrial|seguridad industrial|\btaf\b|birkenstock|\bimpuls\b|galer[ií]a del calzado|lob footwear|\blob\b|^outlet$|aldo\b|zara|bershka|pull ?& ?bear|stradivarius|h&m|c&a|forever 21|old navy|nine west|clarks|hush puppies|timberland|dr\.? martens|florsheim|bata\b|sfera|julio\b|ivonne|cuidado con el perro',
    subgiro=_sub([(r'bota|vaquer|western', 'botas'), (r'ni[nñ]|kids|infantil|beb[eé]', 'infantil'), (r'hombre|caballero', 'caballero'), (r'dama|mujer|women', 'dama'), (r'tenis|sneaker', 'tenis')], 'familiar')),
 'joyeria': dict(stems=['joyería','joyería fina'],
    cat_ok=('joyería','joyer','tienda de bisutería','diseñador de joyas','tienda de oro','orfebre','plater'),
    cat_fuera=('empeño','comprador de oro','compra de oro','reparación','prestamista','servicio de reparación'),
    nombre_fuera=r'empe[nñ]o|compro oro|compra de oro|pandora|swarovski|\btous\b|bizzarro|cristal joyas|\bnice\b|kevin|taller de reparaci|reparaci[oó]n|prendamex|monte de piedad|nacional monte|pawn|casa de empe|tiffany|cartier|bulgari|rolex|^centro joyero$|^centro joyero (metropolitano|san juan)|magno centro joyero|kukulcan|vende plata sin invertir',
    nombre_ok=r'joy|jewel|plater|oro\b|gold|bisuter|gema|diamant|anillo',
    subgiro=_sub([(r'plata|silver|taxco', 'plata'), (r'oro\b|gold|fina|diamante|anillos? de compromiso', 'fina'), (r'bisuter|accesorio|fantas', 'bisuteria')], 'general')),
 'relojerias': dict(stems=['relojería','tienda de relojes'],
    cat_ok=('relojería','tienda de relojes','joyería'),
    cat_fuera=('servicio de reparación','reparación'),
    nombre_fuera=r'taller|reparaci|servicio t[eé]cnico|servitiempo|\bemwa\b|\bberger\b|\bpeyrelongue\b|liverpool|watch my watch|casio store|fossil|\bswatch\b|tissot|bizzarro|tag heuer|breitling|omega|hublot|panerai|smart ?watch|c[oó]mputo|fotograf|pilas|celular|apple|samsung|garmin|casio',
    nombre_ok=r'reloj|watch|tiempo', nombre_ok_obligatorio=True,
    subgiro='general'),
 'western': dict(stems=['tienda vaquera','botas vaqueras'],
    cat_ok=('tienda de botas','sombrerería','tienda de ropa','zapatería','tienda de ropa de hombre','tienda de ropa vaquera','talabarter','tienda de artículos de cuero'),
    cat_fuera=('atracción','reparación'),
    nombre_fuera=r'\bcuadra\b|reparaci|ortop|\bflexi\b|price shoes|andrea\b|zapater[ií]as? (3|tres) hermanos|la gran barata|calzado industrial|^wrangler$|^levi|huarach|^botas$|^tiendas r$|comercializadora|multimarcas|tejidos|^zapater[ií]a$',
    nombre_ok=r'vaquer|western|bota|cowboy|sombrer|rodeo|ranch|cuadra|jerez|caporal|charr|rancher|piel', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'sombrer', 'sombrereria'), (r'bota', 'botas')], 'tienda vaquera')),
 'charro': dict(stems=['trajes de charro','artículos charros'],
    cat_ok=('tienda de ropa','sombrerería','sastre','tienda','talabarter','tienda de artículos de cuero','tienda de disfraces','tienda de ropa de hombre'),
    cat_fuera=('lienzo','asociación','restaurante','atracción','escuela'),
    nombre_fuera=r'lienzo charro|asociaci[oó]n|restaurante|escuela|cantina|\bbar\b|mariscos|team store|estadio|campo charro|auto ?partes|productos secos|remates|cachucha|guayabera|serigraf|uniformes|\bhats?\b|^sombrero loco|^el charro$|^charro$|taquer|carnitas|birria|tacos|abarrote|ferreter',
    nombre_ok=r'charr|escaramuza|jaripeo|mariachi|sombrer|talabarter|vaquer|western|bordad', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'sombrer', 'sombrereria'), (r'escaramuza', 'escaramuza'), (r'mariachi', 'mariachi')], 'charreria')),
 'tallas': dict(stems=['ropa tallas grandes','ropa tallas extra'],
    cat_ok=('tallas grandes','tienda de ropa','boutique','tienda de ropa de mujer','tienda de ropa de hombre'),
    cat_fuera=('mayorista','fábrica','uniformes','segunda mano','ropa de trabajo','ropa de deportes','lencería','ropa interior'),
    nombre_fuera=r'novia|renta|alquiler|mayoreo|uniforme|\bjulio\b|liverpool|^outlet land|\bpaca\b|fajas|^fashion$|^leal$|^ropa extra$|^ropa tallas extra$|^zaar$|^plano cero',
    nombre_ok=r'talla|extra|plus|curv|\bxl\b|\bxxl\b|gord|grande|big|king|queen|real para|ropa extra|tallas grandes', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'hombre|caballero|big ?& ?tall|king', 'caballero')], 'dama')),
 'scrubs': dict(stems=['uniformes médicos','uniformes quirúrgicos'],
    cat_ok=('tienda de uniformes','uniforme','tienda de ropa de trabajo','tienda de ropa','tienda de material médico','tienda de suministros médicos','fábrica de ropa','proveedor de ropa','tienda de artículos médicos'),
    cat_fuera=('escolar','hospital','clínica','farmacia','laboratorio','dentista'),
    nombre_fuera=r'escolar|hospital\b|cl[ií]nica|farmacia|laboratorio|dental|dentista|insumos m[eé]dicos|equipo m[eé]dico|ortop|empresarial|industrial|screen print|serigraf|textil|^rayo$|^en$|^el rey$|multi$|hospitalario|deportiv|combate|f[uú]tbol|soccer|^uniformes$|^uniforme$|seguridad|tactic|militar|dermat|insumos',
    nombre_ok=r'uniform|scrub|m[eé]dic|quir[uú]r|hospital|enfermer|piyama|filipina|bata|cirug|cl[ií]nic|doctor|dr\b|nurse|health|salud|vestir|textil|confecc|ropa|boutique|creaciones', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'chef|gastron|industrial|empresarial|ejecutiv', 'uniformes generales')], 'medicos')),
 'vintage': dict(stems=['ropa vintage','tienda de ropa de segunda mano'],
    cat_ok=('vintage','segunda mano','tienda de ropa','boutique','tienda de ropa usada','tienda de ropa de mujer','tienda de artículos de segunda mano','bazar','thrift'),
    cat_fuera=('mayorista','fábrica','uniformes','antigüedades','muebles','anticuario','libros','discos','electrónica','empeño'),
    nombre_fuera=r'muebles|antig[uü]edad|anticuario|libros|discos|empe[nñ]o|electr[oó]nic|celular|pacas? de|gucci|levi|innvictus|veterinar|videojuego|lencer|corseter|boneter|mayoreo|distribuid|yazbek|optima|eurocotton|camisetas|playeras|^tiendas re$|remate|outlet|jeans|clothing co|^vintage$|^bazar$|c[aá]ritas|cruz roja|dif\b|juguet|zapat|calzado|tenis|sneaker|novedades|^ventas |\bbike\b|^ropa de segunda mano$|^ropa americana$|^ropa de paca$|mega ?box',
    nombre_ok=r'vintage|segunda|second|thrift|bazar|usad|retro|garage|closet|ropavejer|\bpaca|2nd|2do|preloved|pre-loved|reventa|resale|ropa usada|bazaar|bazar',
    nombre_ok_obligatorio=True,
    subgiro=_sub([(r'segunda|second|usad|thrift|bazar', 'segunda mano'), (r'paca', 'pacas')], 'vintage')),
 'deportiva': dict(stems=['tienda de ropa deportiva','uniformes deportivos'],
    cat_ok=('tienda de deportes','tienda de ropa de deportes','tienda de uniformes','tienda de ropa','tienda de artículos deportivos','uniformes deportivos','ropa deportiva','tienda de camisetas','fábrica de ropa'),
    cat_fuera=('gimnasio','club','escuela','estadio','bicicleta','ciclismo','armas','pesca','caza','trofeos','nutrición','suplementos','escolar'),
    nombre_fuera=r'decathlon|mart[ií]\b|innovasport|\bnike\b|adidas|\bpuma\b|under armour|charly\b|dportenis|sport city|skechers|netshoes|new balance|reebok|asics|gimnasio|\bgym\b|crossfit|suplement|nutrici|bicicleta|\bbike\b|armas|pesca|trofeo|liverpool|coppel|sears|innvictus|pirma|new era|lululemon|converse|\blob\b|sport ?depot|yazbek|escolar|industrial|\bcaza\b|\btiro\b|campismo|sultanes|team store|unitam|^art[ií]culos deportivos$|^deportes$|camisetas|playeras|rugido|\bnfl\b|\bnba\b|\bmlb\b|fanatics|mart[ií] ?$|bicicl|motocicl|\bmoto\b|arma|ferreter',
    subgiro=_sub([(r'uniform|equipos?\b|escuadr', 'uniformes'), (r'futbol|fútbol|soccer|balón|balon', 'futbol'), (r'\bgym\b|fitness|leggin|activewear|yoga', 'fitness')], 'ropa deportiva')),
 'telas': dict(stems=['tienda de telas','telas y mercería'],
    cat_ok=('tienda de telas','mercería','tienda de tejidos','tienda de artículos de costura','tienda de manualidades','tienda de textiles','mayorista de telas','tienda de hilos','tienda de lanas','comercio'),
    cat_fuera=('tapicería','cortinas','muebles','centro comercial','departamental','fábrica de ropa','tienda de ropa'),
    nombre_fuera=r'parisina|modatelas|\bbayon\b|tapicer|cortina|muebl|colch|departamental|nuevo mundo departamental|coppel|liverpool|papeler|pl[aá]stic|\blonas?\b|vinil|no tejidos|decor|^casa$|^plast|gancedo|distribuidora|comercializadora|grupo textil|^textiles$|^estambres$|^tela$|^telas$|reflejante|industrial|\bsa de cv\b|s\.a\. de c\.v',
    nombre_ok=r'tela|textil|mercer|hilo|lana|estambre|manualidad|bonet|costura|fabrics|casimir|tejid', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'mercer|hilo|estambre|manualidad|bonet', 'merceria'), (r'casimir|sastrer', 'casimires')], 'telas')),
 'disfraces': dict(stems=['tienda de disfraces','renta de disfraces'],
    cat_ok=('tienda de disfraces','disfra','tienda de artículos para fiestas','tienda de ropa','alquiler de disfraces','tienda de artículos de broma'),
    cat_fuera=('salón','organizador','centro comercial','parque'),
    nombre_fuera=r'sal[oó]n|inflables|brincolin|payaso|show\b|animaci[oó]n|botarga|papeler|regalos|cinematogr|vestuario|^disfraces$|^tienda de disfraces$|mens black|party ?land|party ?city|globos|pi[nñ]ater',
    nombre_ok=r'disfra|costume|fantas[ií]a|carnaval|halloween|fiesta|party|cosplay|m[aá]scara|botarga', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'renta|alquiler', 'renta'), (r'botarga', 'botargas')], 'venta')),
 'sublimado': dict(stems=['sublimación de playeras','playeras personalizadas'],
    cat_ok=('tienda de camisetas','serigraf','estampado','sublimaci','impresión','tienda de regalos personalizados','artículos promocionales','bordado','tienda de ropa','fábrica de ropa','tienda de uniformes','imprenta','impresora'),
    cat_fuera=('centro comercial','papelería'),
    nombre_fuera=r'papeler[ií]a|copias|lonas|rotulaci|gran formato|se[nñ]al[ée]tica|imprenta|yazbek|distribuid|vinil|l[aá]ser|publicidad|dise[nñ]o gr[aá]fico|^grafik|^shirts$|^impresos|^impresiones|print ?house|print ?shop|print store|ecoprint|tarjetas|invitaciones|tazas|^playeras personalizadas$|^serigraf[ií]a$|^bordados$|^sublimaci[oó]n$|uniformes? (industrial|empresarial|escolar)|drunk devil|corte l[aá]ser|cnc|3d',
    nombre_ok=r'playera|sublim|estamp|serigraf|personaliz|bordad|t-?shirt|camiseta|promocional|textil', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'bordad', 'bordado'), (r'serigraf', 'serigrafia'), (r'promocional|regalo', 'promocionales')], 'sublimado')),
 'outlets': dict(stems=['outlet de ropa','outlet de ropa de marca'],
    cat_ok=('tienda de ropa','outlet','boutique','tienda de ropa de mujer','tienda de ropa de hombre','tienda de calzado','zapatería','tienda de ropa de niños','tienda de saldos'),
    cat_fuera=('centro comercial','mayorista','fábrica','uniformes','segunda mano','muebles','electr'),
    nombre_fuera=r'nike|adidas|puma|levi|tommy|calvin|guess|polo|lacoste|under armour|skechers|crocs|reebok|liverpool|palacio|premium outlets|punta norte|las plazas|centro comercial|plaza\b.*outlet$|muebl|electr[oó]nic|electrodom|colch|\bgap\b|banana republic|american eagle|hollister|aeropostale|carter|oshkosh|columbia|north face|coach|kate spade|michael kors|samsonite|lego|ripley|pull ?& ?bear|bershka|zara|shasa|cuidado con el perro|\bjulio\b|ivonne|c&a|old navy|suburbia|sears|coppel|milano|del sol|innovasport|mart[ií]\b|flexi|price shoes|andrea\b|cklass|capa de ozono|aurrer|interceramic|cesantoni|tecnopiso|pallet|perfumer|balenciaga|\bboss\b|dockers|converse|new era|innvictus|adolfo dom|ferrioni|dd.s discount|oggi|yazbek|mayorista|mayoreo|^outlet$|^outlets?( store| shop)?$|^ropa de moda$|^fashion outlet$|^outlet fashion store$|^marcas outlet$|^outlet premium|premium outlet|^premium |the family outlet|calcent|socks|calcet|pisos?\b|azulej|llantas|refaccion|muebler|hogar|tenis|sneaker|vans|dc shoes|\bgap\b|tommy|nautica|dockers|us polo|steve madden|nine west|aldo|sfera|bershka|pull|zara|shasa|ferreter|abarrot|super|^optima|baby creysi|^vanity|luuna|true religion|t\.?j\.? ?maxx|porto blanco|marshalls',
    nombre_ok=r'outlet|saldo|remate|barat|descuento|liquidaci|precio|bodega|ganga|oferta|mayoreo|ropa|boutique|moda|fashion|store|tienda', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'zapat|calzad|shoe|tenis', 'calzado'), (r'ni[nñ]|kids|infantil|beb[eé]', 'infantil')], 'ropa')),
 'fabricantes': dict(stems=['maquiladora de ropa','fábrica de ropa','confección de ropa'],
    cat_ok=('fábrica','maquiladora','confecci','proveedor de ropa','fabricante','taller de confección','productor','mayorista','industria textil','textil','tienda de ropa','diseñador de moda','empresa'),
    cat_fuera=('sastre','arreglos de ropa','modista','taller de costura','centro comercial','escuela','tienda de telas','uniformes','tienda de máquinas','servicio de reparación'),
    nombre_fuera=r'sastrer|arreglos|compostura|modista|m[aá]quinas de coser|singer|brother|escuela|academia|universidad|instituto|renta|uniform|bordad|pl[aá]stic|met[aá]l|autom|el[eé]ctric|motores|puertas|empaque|papel|cart[oó]n|qu[ií]mic|aliment|rompope|cerve|refresc|hospital|safety|medical|m[eé]dic|lamosa|kimberly|mondel|\blear\b|aptiv|borgwarner|smurfit|kappa|rheem|teleflex|joyson|hughes|pochteca|materias primas|distribuidor|mayoreo|dep[oó]sito|franquicia|sorteadora|modular|corporativo|oficinas|^tienda de ropa|\bplanta\b|industria(?!.{0,25}(textil|ropa|confec|vesti|moda))|industrial(?!.{0,25}(textil|ropa|confec|vesti|moda))|maquiladora industrial|^maquiladora de ropa$|^maquila de corte|^maquilas de m[eé]xico$|^bulk$|credum|sistemas|tecnol|log[ií]stic|transport|construc|inmobil|agr[ií]c|ganader|miner|petr[oó]l|acero|vidrio|madera|muebl|cable|arn[eé]s|harness|electr[oó]nic|aeroesp|maquinaria|herramient|pintura|jab[oó]n|cosm[eé]t|farmac|impres|serigraf|sublim|playeras? (personaliz|estamp)|mercer|hilos|av[ií]os|botanas|blancos|pillow|almohada|comercializadora|colch|^textiles$|vianney|punt roma|restauraci|reparaci|costura express|^costuras|sint[eé]tic|pieles|derivados|lotes|^tamaulipas centro|guayabera|t[ií]pica|artesan',
    nombre_ok=r'confecci|textil|ropa|moda\b|fashion|apparel|jeans|denim|mezclilla|pantal|playera|blusa|vestido|camisa|prenda|costura|tejid|sportwear|sportswear|sweater|su[eé]ter|chamarra|lencer|calzado|zapato|\bbota|tenis|jersey|leggin|corset|faja|manufacturera de ropa|garment|knit|punto\b', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'jean|denim|mezclilla|pantal', 'mezclilla'), (r'playera|t-?shirt|camiseta', 'playeras'), (r'infantil|ni[nñ]|beb[eé]', 'infantil'), (r'dama|mujer|blusa|vestido', 'dama'), (r'caballero|hombre|camisa', 'caballero')], 'confeccion')),
 'distribuidores': dict(stems=['ropa al mayoreo','mayorista de ropa'],
    cat_ok=('mayorista','tienda de ropas mayorista','proveedor de ropa','tienda de ropa','fábrica','distribuidor','tienda de ropa de mujer','boutique','tienda de camisetas','tienda de uniformes','tienda de ropa infantil','comercio','tienda de ropa interior','tienda de calzado','zapatería'),
    cat_fuera=('centro comercial','outlet','escuela','tienda de telas','uniformes escolares'),
    nombre_fuera=r'liverpool|coppel|walmart|costco|sam.?s|escuela|academia|telas\b|mercer|renta|novia|julio\b|ivonne|abarrot|city club|naturista|tornill|pl[aá]stic|flores|pollo|carne|dulce|metal|refacci|blancos|hogar|vasos|bolsas|yazbek|ct internacional|hilos|escolar|automotri|farmac|papeler|desechable|ferreter|electr|celular|cosm[eé]t|perfum|juguet|bodegas alianza|scorpion|\barmy\b|militar|t[aá]ctic|cedis|alimento|bebida|licor|vinos|limpieza|qu[ií]mic|pintura|construc|acero|maderer|llanta|bater[ií]a|gas\b|agua\b|hielo|tortill|panader|mueble|colch|regalos|fiesta|globos|piñat|mascota|veterin|semilla|fertiliz|agro|ganad|pesca|art[ií]culos de limpieza|cerve|refresc|caf[eé]\b|tabaco|cigarr|vape|pakar|oggi|^optima|bargain|^zoy$|grupo t & m|mayoreo de todo|floral|hilatex|en l[ií]nea|estampado|artesanal|m[ií]stico',
    nombre_ok=r'jeans|denim|ropa|moda\b|fashion|boutique|collection|colecci|kids|shoes|calzado|uniform|playera|blusa|vestid|lencer|interior|textil|creaciones|bonet|pantal|camisa|prenda|trendy|outfit|closet|mezclilla|leggin|faja|pijama|sweater|su[eé]ter|chamarra|sudadera|gorra|calcet|sock|zapat|tenis|bota', nombre_ok_obligatorio=True,
    subgiro=_sub([(r'zapat|calzad|shoe|tenis', 'calzado'), (r'jean|denim|mezclilla', 'mezclilla'), (r'infantil|ni[nñ]|kids|beb[eé]', 'infantil'), (r'lencer|interior|\bbra\b', 'lenceria'), (r'uniform', 'uniformes'), (r'playera|t-?shirt|camiseta|bonet', 'playeras')], 'ropa')),
 'jeans': dict(stems=['tienda de jeans','tienda de mezclilla'],
    cat_ok=('tienda de jeans','tienda de ropa','boutique','tienda de ropa de mujer','tienda de ropa de hombre','tienda de pantalones','mayorista de ropa','fábrica de ropa','tienda de ropa vaquera'),
    cat_fuera=('sastre','arreglos','modista','taller de costura','tienda de telas','centro comercial','grandes almacenes'),
    nombre_fuera=r'levi|wrangler|lee\b|oggi|\bgap\b|american eagle|hollister|abercrombie|pull ?& ?bear|bershka|zara|h&m|c&a|old navy|tommy|calvin|guess|diesel|true religion|seven|lucky brand|\bjulio\b|ivonne|shasa|cuidado con el perro|sfera|studio f|cklass|price shoes|andrea\b|liverpool|coppel|suburbia|sears|arreglos|compostura|sastrer|telas\b|maquila|bordad|reparaci|silver ?jeans|furor|britos|f[aá]brica|optima\b|aldo conti|high life|allsaints|springfield|rock hampton|polo team|yazbek|men.?s fashion|fajas|pirates of the bay|eunina|^tienda de ropa de mezclilla$|^tienda de jeans$|lacoste|nautica|dockers|scappino|massimo|bimba|mango\b|forever 21|ropa casual estrella',
    nombre_ok=r'jeans?\b|mezclilla|denim|pantal|jean\b|levis|vaquer|blue|tienda de ropa',
    nombre_ok_obligatorio=True,
    subgiro=_sub([(r'dama|mujer|women|lady|ladies|chica', 'dama'), (r'caballero|hombre|\bmen\b|boy', 'caballero'), (r'mayoreo|mayorista|wholesale|distribuid', 'mayoreo')], 'jeans')),
 'trajesbano': dict(stems=['tienda de trajes de baño','trajes de baño'],
    cat_ok=('tienda de trajes de baño','tienda de bañadores','tienda de artículos de natación','tienda de ropa de playa','tienda de ropa','boutique','tienda de ropa de mujer','tienda de ropa interior','tienda de ropa de deportes','tienda de artículos de playa','tienda de lencería','fábrica de ropa'),
    cat_fuera=('alberca','piscina','escuela de natación','club de natación','centro comercial','grandes almacenes','hotel','club','tienda de deportes acuáticos','buceo'),
    nombre_fuera=r'alberca|piscina|nataci[oó]n|swim(ming)? ?(school|club|team)|acu[aá]tic|buceo|\bsurf\b(?!.*(shop|store))|hotel|resort|spa\b|speedo|arena\b|\bnike\b|adidas|\bpuma\b|liverpool|coppel|suburbia|sears|\bjulio\b|ivonne|shasa|zara|h&m|c&a|old navy|victoria.?s secret|oysho|calzedonia|women.{0,3}secret|decathlon|innovasport|mart[ií]\b|sport city|reparaci|f[aá]brica|maquila|mayoreo|mayorista|distribuid|ilusi[oó]n|vicky form|playtex|leonisa|squalo|yamamay|intimissimi|tezenis|etam\b|^ba[nñ]os\b|sanitari|azulej|muebles|regadera|tina|^ropa\b.*baratin|salvavidas|^bikini$|^trajes de ba[nñ]o$|^swimwear$|^tienda de trajes de ba[nñ]o$',
    nombre_ok=r'ba[nñ]o|ba[nñ]ador|bikini|swim|beach|playa|tankini|sol\b|verano|summer|mar\b|ola|surf|resort ?wear|pareo|body|lencer|interior|fitness',
    nombre_ok_obligatorio=True,
    subgiro=_sub([(r'bikini', 'bikinis'), (r'lencer|interior|corseter', 'lencería y baño'), (r'playa|beach|surf', 'ropa de playa')], 'trajes de baño')),
}
