const { abrir } = require('./rec.cjs'); const prep = require('./prep.cjs');
(async()=>{
  const r = await abrir(1344, 720); const { p } = r;
  await r.go('facturacion-electronica/list/index', 'Timbradas');
  await prep.menuColapsado(r); await prep.ocultarFlotantes(r); await p.waitForTimeout(800);
  await r.iniciar('factura-hero');
  await r.quieto(1.0);
  const [tx,ty] = await r.punto('Timbradas'); await r.toque(tx,ty,{clic:false});
  await r.transicion(async()=>{ await p.mouse.click(tx,ty); await p.waitForTimeout(2500); }, 'TIMBRADO');
  await prep.ocultarFlotantes(r); await r.quieto(0.7);
  const fila = await p.evaluate(()=>{ let best=null; const walk=root=>{ root.querySelectorAll('*').forEach(el=>{ if(el.shadowRoot) walk(el.shadowRoot); if(el.classList&&el.classList.contains('cliente-nombre')){ const b=el.getBoundingClientRect(); if(b.width>0&&(!best||b.y<best[1])) best=[b.x+b.width/2,b.y+b.height/2]; } }); }; walk(document); return best; });
  await r.toque(fila[0], fila[1], {clic:false});
  r.st.vis = 0;
  await r.transicion(async()=>{ await p.mouse.click(fila[0], fila[1]); await p.waitForTimeout(2000); }, 'Jeans wide leg', { extra: 2500 });
  await prep.ocultarFlotantes(r);
  await r.quieto(1.4);
  await r.scroll(470, 1.5); await r.quieto(1.6);
  await r.terminar('factura-hero', { recorteIzq: 64, salida: [1600,900] });
  await r.cerrar();
})().catch(e=>{ console.error('FALLO', e.message); process.exit(1); });
